### PR TITLE
[WIP]9.0 base custom attributes

### PR DESCRIPTION
**Pull request by flotho**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This module has no sense having https://github.com/OCA/server-tools/pull/492

**Comment by flotho** [comment]
Hi @pedrobaeza do you mean that the module has to be marked as obsolete and dependencies have to be migrated in favor of https://github.com/OCA/server-tools/pull/492 ?

**Comment by pedrobaeza** [comment]
Yeah, this module has to be removed in fact.

**Comment by flotho** [comment]
close because of : https://github.com/OCA/product-attribute/issues/100#issuecomment-242181046

**Pull request closed without merging**
