### PR TITLE
[ENH] Module product_pricelist_fixed_price:

### PR DESCRIPTION
**Pull request by NL66278**
```
- Backport improvements from 7.0 branch
```

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for backporting my module to 6.1!

But you have to provide a migration script that allows people coming from previous versions of the module to not lose their data.

**Comment by lfreeke** [comment]
:+1:  approve after test

**Comment by pedrobaeza** [comment]
This can't be merged while there isn't migration scripts :-1:

**Comment by NL66278** [comment]
I updated the code to automatically update data from older versions, if present.

**Comment by pedrobaeza** [comment]
Thanks for the migration script. Can you please use migration machinery to do it in order to not have possible side effects?

**Comment by NL66278** [comment]
I do not think there can be any side effect, because I first check wether there is anything to upgrade, before doing the upgrade.

I know there is some migration machinery, but as this is totally undocumented and cryptic, I think just a simple sql query + update is the ideal tool to use.

**Comment by pedrobaeza** [comment]
OK, I give my approval as is :+1:

**Comment by yvaucher** [comment]
This needs a rebase.

Please do a

`git rebase -i origin/6.1`

**Comment by NL66278** [comment]
It is doubtfull wether Travis can be fully satisfied by any updates at the moment. Errors occur already when loading the standaard Odoo/OpenERP code.

**Comment by pedrobaeza** [comment]
As Travis issues are unrelated (pylint and an incompatible module), we can merge this. We can fix that afterwards.

**Comment by NL66278** [comment]
Thank you, Pedro!

**Pull request merged**
