### PR TITLE
[13.0][FIX] product_lot_sequence: Avoid generate extra sequences on duplicates

### PR DESCRIPTION
**Pull request by remi-filament**
Forward port of #1042 (or backward port of #1111 )

### CODE REVIEW

**Review by benj-filament — APPROVED** [review]

**Comment by HviorForgeFlow** [comment]
I would appreciate to keep commit authorship

**Comment by remi-filament** [comment]
@HviorForgeFlow fixed, sorry about that it was easier to just modifiy the necessary lines but I cherry picked the commit instead !

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by HviorForgeFlow** [comment]
@OCA/product-maintainers can merge that? Thanks!

**Pull request merged**
