### PR TITLE
[16.0][TEST] Do not merge. Test uom_category_active CI

### PR DESCRIPTION
**Pull request by legalsylvain**
Hi. This is a Test PR.

Context : I have a weird error in my PR : https://github.com/OCA/product-attribute/pull/1657

The error is 
```
2024-10-31 13:13:22,733 485 ERROR odoo odoo.addons.uom_category_active.tests.test_uom_category_active: FAIL: TestProductCategoryActive.test_archive_reference_uom
Traceback (most recent call last):
  File "/__w/product-attribute/product-attribute/uom_category_active/tests/test_uom_category_active.py", line 33, in test_archive_reference_uom
    with self.assertRaises(UserError):
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/opt/odoo/odoo/tests/common.py", line 382, in _assertRaises
    with ExitStack() as inner:
  File "/usr/lib/python3.10/contextlib.py", line 576, in __exit__
    raise exc_details[1]
  File "/usr/lib/python3.10/contextlib.py", line 561, in __exit__
    if cb(*exc_details):
AssertionError: UserError not raised
```

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi @angelmoya. The module you proposed here https://github.com/OCA/product-attribute/pull/1337 has the test failing. Could you take a look ? 

thanks !

**Comment by simahawk** [comment]
IMO we should comment the test and create a specific issue. That test looks incomplete as is not clear what is testing.

**Comment by simahawk** [comment]
Commented here https://github.com/OCA/product-attribute/pull/1761 
Issue opened here https://github.com/OCA/product-attribute/issues/1762

**Comment by simahawk** [comment]
Ah sorry @legalsylvain I didn't see you reworked it here https://github.com/OCA/product-attribute/pull/1760, my bad :sweat: I'll review that, sorry for the noise!

**Comment by simahawk** [comment]
https://github.com/OCA/product-attribute/pull/1760 is getting merged

**Pull request closed without merging**
