### PR TITLE
[16.0][IMP][FIX]Product_profile: Support Create multi

### PR DESCRIPTION
**Pull request by bosd**
Fixes the warning "The model odoo.addons.product_profile is not overriding the create method in batch"

### CODE REVIEW

**Review by bealdav — APPROVED** [review]
Thanks a lot, good catch

**Comment by bosd** [comment]
Tests are still red. 😢
Assume that the v16 branch here need some ❤️

**Comment by bosd** [comment]
This is odd. On github website, there are 2 tests for Odoo and 2 test for OCB.
One of them fails.

On github mobile.. The failing tests are not there..

**Comment by bealdav** [comment]
https://github.com/OCA/product-attribute/blob/16.0/.github/workflows/test.yml#L38-L50  

Test are about include or exclude product_dimension

**Review by Dranyel-Bosd — COMMENTED** [review]
LGTM :+1:  :sparkles:

**Comment by rousseldenis** [comment]
@bosd

**Review by Dranyel-Bosd — APPROVED** [review]
LGTM :+1:

**Comment by bosd** [comment]
@rousseldenis Can you mergethis?

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
