### PR TITLE
[FIX] product_profile in case new value empty

### PR DESCRIPTION
**Pull request by bealdav**
ping @sebastienbeau

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi,
Thanks for this PR.
I find it technically ok, but maybe not in this module.
In 99,9% of the case, it will be ok, but maybe in some cases, not calling super will have an unexpected side effect. (because sometimes write function not only write, (but does a log, for exemple).
I mean, avoiding realizing a write if vals are empty can be an interesting feature but maybe in a generic module like 'model_avoid_emty_write', with inheritance in 'model.base'.
What do you think ? Any other PoV ? I personnaly don't use this module for the time being, so my PoV is limited.
regards.

**Comment by bealdav** [comment]
@legalsylvain Ok, do you accept my PR if I had a comment in thi code to schedule me to do the module you ask me in next month.
It's a really good idea but it's an important fix and I have no time for now to do it.
cc @sebastienbeau @hparfr 
thanks for your feedback

**Comment by bealdav** [comment]
@legalsylvain Ok I scrap previous commit and transform in cosmetic commit to avoid change write behavior, as you said me.
Now PR is safe

**Comment by legalsylvain** [comment]
:+1: thanks !

**Comment by bealdav** [comment]
ping @hparfr

**Comment by hparfr** [comment]
👍 
startswith is definitely more readable  :triumph:

**Pull request merged**
