### PR TITLE
[13.0][IMP] product_pricelist_direct_print: Improve inheritability

### PR DESCRIPTION
**Pull request by sergio-teruel**
Ported from v12.0 (https://github.com/OCA/product-attribute/pull/754)
TT27676

cc @Tecnativa @carlosdauden @CarlosRoca13

### CODE REVIEW

**Comment by pedrobaeza** [comment]
What about the other commit?

**Review by CarlosRoca13 — COMMENTED** [review]
Please add the summary field as it is done in the changes of version 12
- https://github.com/OCA/product-attribute/pull/754/files#diff-8e5437316f55cfc1c6194c2a6c1623d6be9ac606e2d171240bc06b139941a087R57
- https://github.com/OCA/product-attribute/pull/754/files#diff-97e89267f5bfe93ef2ff86b34a720a4095a30a1fcf8d97f76c3442823baf31e6R88

**Comment by sergio-teruel** [comment]
Added last commit as separated commit.

**Review by CarlosRoca13 — APPROVED** [review]
LGTM :+1:

**Review by carlosdauden — APPROVED** [review]

**Pull request merged**
