### PR TITLE
[15.0][MIG] product_pricelist_item_list_view: backport from v16

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
This module adds a new menu item "Pricelist rules" to list and search every pricelist rule.
This is useful when you have many rules and you want to search among them.
For instance, if you have many fixed price rules associated to product variants, without this module you could not easily find a variant's price.

cc @ForgeFlow

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
@LoisRForgeFlow you migrated it to v16. Can you please do a review?

**Review by LoisRForgeFlow — APPROVED** [review]
Code review LTGM!

**Review by JordiMForgeFlow — APPROVED** [review]
code + functional 👍🏼

**Pull request merged**
