### PR TITLE
[12.0][MIG] product_pricelist_direct_print

### PR DESCRIPTION
**Pull request by alexey-pelykh**

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@chienandalu @sergio-teruel @carlosdauden since you're familiar with the topic, please review this PR

**Review by chienandalu — COMMENTED** [review]
Keep in mind that there are ongoing improvements being made in this PR: https://github.com/OCA/product-attribute/pull/396

**Comment by alexey-pelykh** [comment]
Sure, then should be here until #396 is merged in

**Comment by alexey-pelykh** [comment]
@chienandalu #396 has been merged and this PR has been updated as well - please re-review

**Review by tbaden — APPROVED** [review]
code review: lgtm

**Review by chienandalu — APPROVED** [review]

**Comment by rafaelbn** [comment]
Only if possible

codecov/patch — 72.38% of diff hit (target 100%)
Details
@codecov
codecov/project — 81.98% (-18.02%) compared to 847d76d

**Review by rafaelbn — APPROVED** [review]
:+1: 

Maybe improve is possible codecov

**Pull request merged**
