### PR TITLE
[13.0][IMP] stock_account_product_cost_security: additional permission

### PR DESCRIPTION
**Pull request by chienandalu**
It could be the case that even if users are allowed to see product costs, they shouldn't be able to edit them.

cc @Tecnativa TT39711

please review @sergio-teruel @LudLaf

### CODE REVIEW

**Review by LudLaf — APPROVED** [review]
Module tested. Working as expected.

**Review by sergio-teruel — APPROVED** [review]

**Comment by andres-pcg** [comment]
@pedrobaeza @chienandalu This merge is breaking Odoo test since openupgrade is not in the requirements file for this repo.
Screen Shot 2022-10-12 at 12 50 49 PM

**Comment by pedrobaeza** [comment]
This is only needed for updating the module, not for fresh installs, so it shouldn't be in the requirements. Please add it because you will find these requirement through whole Odoo. It's a must.

**Comment by andres-pcg** [comment]
The instance that was broken was a current working database, not a new one. The only thing we did was updating submodules (including this one) and it broke the whole workflow. There's no openupgrade in the requirements for any of the OCA repos (v13) we're currently using.

**Comment by andres-pcg** [comment]
If this repo or any of its dependencies depends on a library, it should be added to the requirements file @pedrobaeza

**Comment by pedrobaeza** [comment]
Please read again. It's just the reverse case.

**Comment by andres-pcg** [comment]
I've found some repos with this dependency, but in different branches. eg: https://github.com/OCA/server-tools/blob/14.0/requirements.txt

**Comment by andres-pcg** [comment]
Anyways, I manually added the dependency to that repo. Thank you for the feedback @pedrobaeza

**Pull request merged**
