### PR TITLE
[10.0][BACKPORT] product_secondary_unit

### PR DESCRIPTION
**Pull request by hparfr**
Backport product_secondary_unit from v12

### CODE REVIEW

**Review by tonygalmiche — APPROVED** [review]
I tested on my computer locally and also with runbot
I checked the code
everything is ok for me
Thank you for this work

**Review by rousseldenis — APPROVED** [review]
Code review.
Could you squash ?

**Comment by hparfr** [comment]
@rousseldenis Rebased

**Comment by emagdalenaC2i** [comment]
@rousseldenis Seems there is an issue merging this PR

**Pull request merged**
