### PR TITLE
[10.0][FIX] travis: Update to latest template

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@pedrobaeza This seems to solve travis issues

**Review by pedrobaeza — APPROVED** [review]
I'm not anymore OCA's community manager for being the wildcard for this kind of things, but OK to do it at least once more :)

**Comment by rousseldenis** [comment]
> I'm not anymore OCA's community manager for being the wildcard for this kind of things, but OK to do it at least once more :)

That's because for all those kind of PR's you had used to be the first on it.

Copy that. I will ping the PSC next time. Thanks !

**Pull request merged**
