### PR TITLE
[MIG] mig product template tags: Migration to 14.0

### PR DESCRIPTION
**Pull request by michotm**

### CODE REVIEW

**Review by tonygalmiche — APPROVED** [review]
LGTM : Functional review only with runbot

image

**Review by emagdalenaC2i — COMMENTED** [review]
LGTM But I think you should sqash and sort your commits
See https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

**Comment by michotm** [comment]
> LGTM But I think you should sqash and sort your commits
> See https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

Could you give me more indication ? I add only 3 commits 
- 1 for pre-commit (black, pylint ....)
- 2 for the fix of the migration in 14
- 3 to improve the module with sql unicity constraint + tests

**Comment by sebastienbeau** [comment]
@michotm 
You should squash administrative commit (this is not your additionnal commit but the automatic gitbot commit)


> Squash administrative commits (if any) with the previous commit for reducing commit noise. They are named as "[UPD] README.rst", "[UPD] Update $MODULE.pot", "Update translation files" and similar names, and comes from OCA-git-bot, oca-travis or oca-transbot. IMPORTANT: Don't squash legit translation commits, authored by their translators, with the message "Translated using Weblate (...)".

> source : https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#tasks-to-do-in-the-migration

**Review by patrickrwilson — APPROVED** [review]
LGTM

**Pull request merged**
