### PR TITLE
[FIX] product_pricelist_direct_print: Fix bootstrap v4 elements

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT22178
@carlosdauden @Tardo  review please!

### CODE REVIEW

**Review by Tardo — APPROVED** [review]

**Review by carlosdauden — APPROVED** [review]

**Comment by emagdalenaC2i** [comment]
@pedrobaeza There are other PR in this repo approved and ready to merge. Could you please check and merge #571 #570 #568 and #541

**Comment by pedrobaeza** [comment]
Sorry, it's not my responsibility anymore. Please ping PSC members.

**Comment by emagdalenaC2i** [comment]
we did it

**Comment by pedrobaeza** [comment]
Yes, then ask to merge to one of this people.

**Pull request merged**
