### PR TITLE
[16.0][MIG] product_attribute_value_menu: Migration to 16.0

### PR DESCRIPTION
**Pull request by neuby001**

### CODE REVIEW

**Comment by neuby001** [comment]
> Please check-in the following files:
> setup/product_attribute_value_menu/odoo/addons/product_attribute_value_menu

I did a pre-commit but this file was not created

**Comment by JordiMForgeFlow** [comment]
Hi @neuby001 

Could you add also the FW of #1351 ? Thank you! :)

**Comment by dsolanki-initos** [comment]
Hello @neuby001, I've noticed that the README.rst steps for the configuration is not proper, Kindly update it accordingly.
Functional review LGTM.

**Comment by carolinafernandez-tecnativa** [comment]
Code review LGTM

Please squash administrative commits https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate

Last commit should be: 
image

Thanks :)

**Review by pedrobaeza — APPROVED** [review]
Commit history normalized, so merging:

/ocabot merge nobump

**Pull request merged**
