### PR TITLE
[10.0][FIX] Issue #503

### PR DESCRIPTION
**Pull request by joergfederspiel**
- fixed typo in context for menu "Partner Pricelists" by adding missing apostrophe before "visible_product_tmpl_id"
- removed "default_product_tmpl_id" from context to avoid Odoo Client Error for menu "Partner Pricelists"

### CODE REVIEW

**Comment by rousseldenis** [comment]
@joergfederspiel Could you rebase as travis has been fixed ?

**Comment by joergfederspiel** [comment]
> @joergfederspiel Could you rebase as travis has been fixed ?

@rousseldenis with rebase you mean I should execute `git rebase 10.0` on my bugfix branch?

**Comment by rousseldenis** [comment]
> > @joergfederspiel Could you rebase as travis has been fixed ?
> 
> @rousseldenis with rebase you mean I should execute `git rebase 10.0` on my bugfix branch?

Yes.

git fetch OCA(or the name you gave to OCA remote)
git rebase OCA/10.0

**Comment by rousseldenis** [comment]
Maybe wrong. You should have just one commit here

**Comment by joergfederspiel** [comment]
I checked out the bugfix/issue_503 branch, added the oca remote and executed the commands you mentioned in your post. After that I had to commit and then I pushed the result.

Is there anything wrong?

**Comment by rousseldenis** [comment]
> I checked out the bugfix/issue_503 branch, added the oca remote and executed the commands you mentioned in your post. After that I had to commit and then I pushed the result.
> 
> Is there anything wrong?

Yes. Your rebase command should not generate a merge command and the result here should show only one commit.

**Comment by joergfederspiel** [comment]
> > I checked out the bugfix/issue_503 branch, added the oca remote and executed the commands you mentioned in your post. After that I had to commit and then I pushed the result.
> > Is there anything wrong?
> 
> Yes. Your rebase command should not generate a merge command and the result here should show only one commit.

And what should I do now? Is there any solution to fix this?

**Pull request closed without merging**
