### PR TITLE
[13.0][MIG] product_stock_state

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Standard Migration

CC @Forgeflow @rousseldenis

### CODE REVIEW

**Comment by rousseldenis** [comment]
@HviorForgeFlow module migration has been merged yesterday :smile:

**Comment by rousseldenis** [comment]
https://github.com/OCA/product-attribute/tree/13.0/product_state

**Comment by rousseldenis** [comment]
@HviorForgeFlow Sorry, morning, didn't see 'stock'

**Review by AdriaGForgeFlow — APPROVED** [review]
Code review :+1:

**Pull request closed without merging**
