### PR TITLE
[10.0] MIG product-supplierinfo-revision

### PR DESCRIPTION
**Pull request by zeroheure**
Actualy, it's the 11 version — there was really nothing to do except version number.
Additionaly a few updates in the README.rst

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You should preserve commit history, but reversing the remotes indicated in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0 in the technical part.

**Comment by zeroheure** [comment]
I followed the Migration-to-version-10.0 explanations. But the module wasn't in the repository.

**Comment by pedrobaeza** [comment]
Because that guide is for migrating a module from 9.0 to 10.0. As you are moving one module from 11.0 to 10.0. that's why I told you to follow the other guide reversing 10.0 per 11.0 on this line:

> git format-patch --keep-subject --stdout origin/11.0..origin/10.0 -- $MODULE | git am -3 --keep

**Comment by zeroheure** [comment]
Sorry, I didn't understood. I will do it.  Thanks for the help.

**Comment by zeroheure** [comment]
@pedrobaeza I think I've done some mistakes, because now I got the complete REPO history from 11  instead of module history only.

**Comment by pedrobaeza** [comment]
You have to replace `$MODULE` by the name of the module. Maybe is that the problem?

**Comment by zeroheure** [comment]
I double checked the history before : I can't find the mistake :
(abbreviated)
1. clone repo in v10
1. checkout  origin/11
1. format-patch with origin/10.0..origin/11.0 -- product-supplierinfo-revision

Should I have used product_supplierinfo_revision (underscore instead of hyphen) ?

**Comment by pedrobaeza** [comment]
Indeed, the name of the module is `product_supplierinfo_revision`, not `product-supplierinfo-revision` :wink:

**Comment by zeroheure** [comment]
looks like I forgot everything this summer :-)

**Pull request closed without merging**
