### PR TITLE
[14.0][ADD] product_weight_logistics_uom

### PR DESCRIPTION
**Pull request by hparfr**
Glue module between product_logistics_uom and product_weight

Depends of : 
- [x] product_weight #768 
- [x] product_logistics_uom #764

### CODE REVIEW

**Review by sebastienbeau — APPROVED** [review]
LGTM (code review)

**Comment by hparfr** [comment]
ping @Kev-Roche

**Review by Kev-Roche — APPROVED** [review]
LGTM code review

**Pull request merged**
