### PR TITLE
[12.0][IMP] product_pricelist_direct_print: Hide pricelist name option

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT22566
@carlosdauden review please
Commit done in v11.0 after v12 migartion

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by emagdalenaC2i — APPROVED** [review]

**Comment by emagdalenaC2i** [comment]
There is a warning in travis (tests/test_product_pricelist_direct_print.py line 14-16)
2020-02-27 17:46:25,853 5739 WARNING openerp_test odoo.models: product.category.create() with unknown fields: type

**Comment by emagdalenaC2i** [comment]
@sergio-teruel You can also add changes in #499 and #501

**Comment by simahawk** [comment]
@sergio-teruel please consider @emagdalenaC2i comment https://github.com/OCA/product-attribute/pull/581#issuecomment-592173058 (for a new PR of course).

**Comment by pedrobaeza** [comment]
@simahawk please don't forget next time to bump version number with the merge command

**Comment by simahawk** [comment]
Good catch, my bad :sweat_smile: 
I stopped the build to re-do the merge :wink:

**Pull request merged**
