### PR TITLE
[14.0] [MIG] product_dimension

### PR DESCRIPTION
**Pull request by emagdalenaC2i**

### CODE REVIEW

**Review by bealdav — APPROVED** [review]

**Review by benbrich — APPROVED** [review]
Functional Review LGT! Thanks for the work

**Comment by emagdalenaC2i** [comment]
@OCA/product-maintainers please, could you merge this PR?

**Comment by clementmbr** [comment]
Hi @emagdalenaC2i and others,
FYI, I've just made this [new PR](https://github.com/OCA/product-attribute/pull/775 ) to make product_dimension compatible with @hparfr's module [product_logistics_uom](https://github.com/OCA/product-attribute/pull/764) in v12.0 : https://github.com/OCA/product-attribute/pull/775

**Pull request merged**
