### PR TITLE
[18.0][MIG] product_packaging_dimension: Migration to 18.0

### PR DESCRIPTION
**Pull request by LucasTran380381**
depend: PR 
- https://github.com/OCA/product-attribute/pull/1751

### CODE REVIEW

**Comment by rousseldenis** [comment]
@LucasTran380381 Thanks for this. Don't hesitate to put link to depending PR's in this one's description in order to easy review.

**Review by sebalix — APPROVED** [review]

**Review by nguyenminhchien — APPROVED** [review]
Lgtm

**Review by trisdoan — APPROVED** [review]

**Comment by simahawk** [comment]
@LucasTran380381 the dependency PR got merged.

**Comment by LucasTran380381** [comment]
> @LucasTran380381 the dependency PR got merged.

@simahawk removed PR dependency unreleased

**Review by jbaudoux — APPROVED** [review]

**Pull request merged**
