### PR TITLE
[17.0] [MIG] product_pricelist_supplierinfo: Migration to 17.0

### PR DESCRIPTION
**Pull request by mdurepos**

### CODE REVIEW

**Review by bizzappdev — CHANGES_REQUESTED** [review]
Thank you for the PR,
You will have to follow the OCA standard for migration
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0#how-to

Functional test LGTM

**Comment by suniagajose** [comment]
hi @mdurepos 

can you apply the changes suggested by @bizzappdev ???

thanks,

**Comment by mdurepos** [comment]
@suniagajose working on it. I will reopen another PR with the new branch.

**Comment by mdurepos** [comment]
@suniagajose PR #1632

**Pull request closed without merging**
