### PR TITLE
Fix smart button alignment in brand form view

### PR DESCRIPTION
**Pull request by zeroheure**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@zeroheure I'm not sure this is a fix.

Base version :

image

This version :

image


Moreover, people maybe have inherited from this, so I would tend to not accept this one. @oerp-odoo @loxamir @pedrobaeza Any advice?

**Comment by pedrobaeza** [comment]
Yes, I agree in not changing it and I don't see bad previously

**Comment by rousseldenis** [comment]
@zeroheure IMHO The double group was done intentionally in order to override with flexibility the view. Closing this. Don't hesitate to get feedback if you want.

**Comment by zeroheure** [comment]
Well, the README contains a todo about alignment. This was a fix for it.
In the base version, partner field is not aligned with other fields or widgets, plus there is a vertical bar between partner label and partner form (Odoo widget design). Working every day with this is unpleasant.
More over this was an attempt to push small patches instead of a big one with lots of changes. See my proposal #632
(Agree for double group.)

**Pull request closed without merging**
