### PR TITLE
[15.0][mig] product_seasonality

### PR DESCRIPTION
**Pull request by damdam-s**

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]

**Comment by damdam-s** [comment]
@rousseldenis a refactoring of this is coming to separate "product_allowed_list"(without dates) from seasonal config (with dates)

**Comment by simahawk** [comment]
@damdam-s I would include the refactoring commit here, it's pointless to have v15 w/out it no?

**Review by simahawk — CHANGES_REQUESTED** [review]
blocking just to see how it evolves on #1063

**Comment by damdam-s** [comment]
> @damdam-s I would include the refactoring commit here, it's pointless to have v15 w/out it no?

yes of course but I follow the migration process :) migrate 1:1 and then propose the refactoring

**Comment by simahawk** [comment]
For refactoring I always find better this approach:

1. open a new PR w/ product_seasonality AS IS + installable = False -> we fast track it
2. rebase this PR and add the refactoring here (or in the other PR and close this)

**Review by jcoux — APPROVED** [review]

**Pull request closed without merging**
