### PR TITLE
[15.0][MIG] product_multi_image

### PR DESCRIPTION
**Pull request by flachica**
Dependency below, please review

https://github.com/OCA/connector-prestashop/pull/151
https://github.com/OCA/sale-workflow/pull/2005
https://github.com/OCA/connector-ecommerce/pull/70
https://github.com/OCA/server-tools/pull/2334
https://github.com/OCA/product-attribute/pull/1070
https://github.com/OCA/product-attribute/pull/1069

### CODE REVIEW

**Comment by rousseldenis** [comment]
@flachica Thanks for this. Could you add link in PR description to https://github.com/OCA/server-tools/pull/2334 ?

**Comment by jacekmichalski** [comment]
@rousseldenis or @pedrobaeza Could you rerun Github Actions, the logs have expired and I would like to know why runboat has failed.

**Comment by pedrobaeza** [comment]
A rebase is needed from the original author.

**Comment by flachica** [comment]
> A rebase is needed from the original author.

Rebased

**Review by jacekmichalski — APPROVED** [review]
Everything seems fine

**Comment by jacekmichalski** [comment]
@rousseldenis could you review the code?

**Comment by jacekmichalski** [comment]
@pedrobaeza maybe you could review the code?

**Comment by pedrobaeza** [comment]
Sorry, not using it.

**Comment by jacekmichalski** [comment]
@hailangvn could you review the code? We need one more code review. I would be greatful! Thanks in advance! ;-)

**Review by rousseldenis — APPROVED** [review]

**Comment by jacekmichalski** [comment]
@pedrobaeza can you merge this one?

**Pull request merged**
