### PR TITLE
[13.0] [IMP] product_pricelist_direct_print: forward port of xlsx and just defined products

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT27988

@pedrobaeza this is the improvement related to https://github.com/OCA/product-attribute/pull/788

### CODE REVIEW

**Comment by rousseldenis** [comment]
@CarlosRoca13 Please add reporting-engine to oca_dependencies.txt

**Comment by CarlosRoca13** [comment]
@rousseldenis ups! added

**Review by sergio-teruel — APPROVED** [review]

**Review by ferranmateu — APPROVED** [review]
Functional review OK!

**Review by carlosdauden — APPROVED** [review]

**Pull request merged**
