### PR TITLE
[12.0] [ADD] product_pricelist_print_website_sale: New module that extend product_pricelist_direct_print

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT27367

This module depends on: 

- [x] https://github.com/OCA/product-attribute/pull/754

@carlosdauden @sergio-teruel

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Don't use plurals in module names: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#modules

I suggest `product_pricelist_print_website_sale` as technical name for highlighting the technical dependency and can be extended later for adding other features that depend on this one.

**Comment by CarlosRoca13** [comment]
Changed! @pedrobaeza

**Review by carlosdauden — APPROVED** [review]

**Comment by sergio-teruel** [comment]
@CarlosRoca13 Plase do a rebase. The v12.0 PR Has already been merged

**Comment by CarlosRoca13** [comment]
Travis is red by the module `product_weight`

**Comment by CarlosRoca13** [comment]
@sergio-teruel Now travis is green

**Review by sergio-teruel — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]
Tested! :+1:

**Pull request merged**
