### PR TITLE
[ADD] New module <product_last_price_info>

### PR DESCRIPTION
**Pull request by oihane**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I'm seeing that we can use the trick of declaring this view with the same ID in both modules that use it and avoid this dummy module.

**Comment by oihane** [comment]
Yes, that's true, but then the modules won't be installed automatically, user will be forced to install the required ones by hand

**Comment by pedrobaeza** [comment]
Well, I prefer that option, because this way you need to setup multiple repositories.

**Comment by oihane** [comment]
Ok, I close this, and change the others

**Pull request closed without merging**
