### PR TITLE
[17.0][MIG] product_net_weight

### PR DESCRIPTION
**Pull request by rf-ife**

### CODE REVIEW

**Comment by bosd** [comment]
@rf-ife Thanks for your contribution.
Can you please retain module history and follow the oca migration guide?
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0

By the way. Are you at the oca days?? I noticed some ife stickers over there :)

**Comment by rf-ife** [comment]
> @rf-ife Thanks for your contribution. Can you please retain module history and follow the oca migration guide? https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0
> 
> By the way. Are you at the oca days?? I noticed some ife stickers over there :)

**Comment by rf-ife** [comment]
@bosd do you mean to add the HISTORY.rst file ?

about oca days,  I couldn't attend this time, but some colleagues are there :)

**Comment by bosd** [comment]
> @bosd do you mean to add the HISTORY.rst file ?

Actually not, I am pointing at the commits from other contributes on the previous version of the module

**Comment by bosd** [comment]
Anyway, I think you can close this one

**Comment by rf-ife** [comment]
> Anyway, I think you can close this one

okay done.
but this PR includes some small changes and a German translation file in addition to this one: https://github.com/OCA/product-attribute/pull/1677.

**Comment by bosd** [comment]
In that case, you can open a separate pr with the improvements.


For the translations, those are handled via weblate.
Please update the translation there.
https://odoo-community.org/resources/translate

**Pull request closed without merging**
