### PR TITLE
[13.0][IMP] product_assortment: add icon to menu

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT31313

imagen

@sergio-teruel @pedrobaeza

### CODE REVIEW

**Review by pedrobaeza — COMMENTED** [review]
Do you have the SVG?

**Review by joao-p-marques — APPROVED** [review]

**Comment by CarlosRoca13** [comment]
@pedrobaeza I don't know how to generate it as svg...

I tried `oca-gen-addon-icon --addon-dir=. --icon-set-params "fas fa-boxes" --icon-color orange --format svg` but I don't achieve the expected icon

**Comment by pedrobaeza** [comment]
Ok, let's continue for now with this:

/ocabot merge patch

**Pull request merged**
