### PR TITLE
[MIG][10.0] product_dimension

### PR DESCRIPTION
**Pull request by thomaspaulb**

### CODE REVIEW

**Comment by thomaspaulb** [comment]
Attended reviews of https://github.com/OCA/product-attribute/pull/195

I tried to make a PR to the branch of @gurneyalex, but it would have a lot of conflicts.

**Review by flotho — APPROVED** [review]
Hi @thomaspaulb 
Thanks for this PR, really awaiting for Gurney too.
LGTM

**Review by gaelTorrecillas — APPROVED** [review]

**Comment by flotho** [comment]
Hi @gurneyalex , @pedrobaeza , how is responsible of this repo for merging ?
Regards

**Comment by flotho** [comment]
thanks @pedrobaeza

**Comment by flotho** [comment]
@pedrobaeza where can I follow up the merge process?
Is there any place where /ocabot exposing publicly its jobs ?

regards

**Comment by pedrobaeza** [comment]
The bot gives you the branch to access and check CIs progress next to the last commit

**Comment by flotho** [comment]
@pedrobaeza , thanks for answering,
actually, if I follow this https://github.com/OCA/product-attribute/commits/10.0-ocabot-merge-pr-491-by-pedrobaeza-bump-no , 
Am I correct if I consider that the  latest commit is giving the information ? 
image
Thanks

**Comment by pedrobaeza** [comment]
Yes, that's what I have said :wink:

**Comment by flotho** [comment]
Great, hope that my newbie questions would help some other readers ;-)

**Pull request closed without merging**
