### PR TITLE
[15.0][FIX] product_manufacturer: Change SavepointCase to TransactionCase

### PR DESCRIPTION
**Pull request by victoralmau**
Change SavepointCase to TransactionCase

Please @pedrobaeza can you review it?

@Tecnativa

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
I think this one is going to fail also, but let's try:

/ocabot merge patch

**Comment by rousseldenis** [comment]
@pedrobaeza We need to update copier for the problem of flake8 pre-commit url to have a functional merge. I can take care of even branches :-)

**Comment by pedrobaeza** [comment]
Yes, fixed in #1200

We are updating those that involve pull requests that we are merging:

/ocabot merge patch

Any help is always appreciated. It's a pity that this didn't come at the same time for not having to do the same twice, but we can't decide that...

**Comment by victoralmau** [comment]
Can you try the merging process again?

**Pull request merged**
