### PR TITLE
 [MIG] sale_product_template_tags: Migration to 15.0

### PR DESCRIPTION
**Pull request by BT-dmontull**

### CODE REVIEW

**Review by BT-aestebanez — APPROVED** [review]
LGTM: I think checks are red due to the module of this PR is not merged: https://github.com/OCA/product-attribute/pull/1029

**Review by BT-aestebanez — APPROVED** [review]
LGTM

**Comment by BT-dmontull** [comment]
@rousseldenis could you merge this one too? 
This module is to have the product_template_tags menu.
Thanks

**Review by rousseldenis — APPROVED** [review]
Code review

**Pull request merged**
