### PR TITLE
[14.0][PORT] product_variant_attribute_name_manager: partial port 1048

### PR DESCRIPTION
**Pull request by felipemotter**
Partial Port of #1048 and change the module description.

I withdrew the commits for no_variant because of the test coverage I did for the single variant only.

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by antoniospneto — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Review by rvalyi — APPROVED** [review]
LGTM

**Comment by felipemotter** [comment]
Hello @JordiBForgeFlow, can you restart the tests? From what I analyzed, the error happened because it was executed right at the time of the change of day and ended up confusing the logic of the tests.

**Review by francesco-ooops — APPROVED** [review]
looks ok to me! 

@felipemotter are you planning to reinstate the "no variant" feature?

It's not very clear to me how does that feature work

**Review by antoniospneto — APPROVED** [review]

**Comment by felipemotter** [comment]
@francesco-ooops  not really, to be honest I still don't quite understand the concept of no_variant, so I couldn't simulate tests for it.

**Comment by francesco-ooops** [comment]
> @francesco-ooops not really, to be honest I still don't quite understand the concept of no_variant, so I couldn't simulate tests for it.

@OriolVForgeFlow any input on this?

**Review by francesco-ooops — CHANGES_REQUESTED** [review]
edit: ok sorry I got confused. I realize now this is the cherry-picking of one commit in that PR, so I think it's ok to merge

**Review by francesco-ooops — APPROVED** [review]

**Comment by francesco-ooops** [comment]
@OCA/product-maintainers what do you say?

**Review by etobella — APPROVED** [review]
LGTM 
/ocabot merge minor

**Comment by francesco-ooops** [comment]
image

I think this module should be extended to include attribute sequence in sale configurator: 

image

and website sale: 

image

@felipemotter if you plan something like that ping me please!

**Comment by felipemotter** [comment]
Hello @francesco-ooops  I'm not pretend to change nothing about this. Sorry

**Pull request merged**
