### PR TITLE
[12.0][MIG] Migrated product_priority to v12.

### PR DESCRIPTION
**Pull request by sudhir-erpharbor**
Please review and give feedback.

### CODE REVIEW

**Review by tbaden — CHANGES_REQUESTED** [review]
please generate a readme from fragmented readme with the [maintainer tools](https://github.com/OCA/maintainer-tools) (oca-gen-addon-readme)

**Comment by nikul-serpentcs** [comment]
> please generate a readme from fragmented readme with the [maintainer tools](https://github.com/OCA/maintainer-tools) (oca-gen-addon-readme)

@tbaden It's Not needed, @OCA-git-bot generate automatically.

**Review by tbaden — APPROVED** [review]

**Review by AdriaGForgeFlow — APPROVED** [review]
LGTM :+1:

**Pull request merged**
