### PR TITLE
[16.0] [MIG] product_product_template_navigation

### PR DESCRIPTION
**Pull request by renda-dev**
Migration from 14.0 to 16.0 of **[product_product_template_navigation](https://github.com/OCA/product-attribute/tree/14.0/product_product_template_navigation)**

### CODE REVIEW

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Hi. Thanks for porting this module.

could you take this opportunity to rename the module's name, which does not correspond to the standard of other OCA modules? 

the other module that adds a link between a model and another, are suffixed by ``_link``. so ``product_product_template_link`` could be a better name.

See the current 60 OCA modules : 

image

**Comment by renda-dev** [comment]
> Hi. Thanks for porting this module.
> 
> could you take this opportunity to rename the module's name, which does not correspond to the standard of other OCA modules?
> 
> the other module that adds a link between a model and another, are suffixed by `_link`. so `product_product_template_link` could be a better name.
> 
> See the current 60 OCA modules :
> 
> image

Done! Thanks for the quick feedback :)

**Review by legalsylvain — APPROVED** [review]
Diff review.  Lgtm

**Review by francesco-ooops — APPROVED** [review]
Functional is ok, but why are we using the "archive" icon?

image

I think we could re-use the "variants" odoo standard icon, even if the buttons are not really specular

image

**Comment by francesco-ooops** [comment]
@OCA/product-maintainers could you please add this to https://github.com/OCA/product-attribute/issues/1157 specifying the new module name? 

also: should the PR have this name or the new module's name?

**Comment by renda-dev** [comment]
I totally agree with you @francesco-ooops, thanks for the suggestion! :)

**Pull request merged**
