### PR TITLE
[FIX][14.0]product_multi_image decode variant image

### LINKED ISSUE #1097: [14.0]Product multi image failed on variants
Trying to add multi image on product.product cause the following error :

image

## Module

product_multi_image

## Describe the bug

The issue is thrown on this line https://github.com/OCA/product-attribute/blob/14.0/product_multi_image/models/product_product.py#L34 so mostly it could also come from https://github.com/OCA/server-tools/blob/14.0/base_multi_image/models/owner.py#L59
Looks like Odoo is trying to save something that is not a base64 binary :
image

## To Reproduce
**Affected versions**: 14.0 up to date

1. install the module
2. add an image on a product.product (whatever the storage)
3. try to save the record

**Expected behavior**
expecting image to be save like for product.template

**Additional context**
adding an image on a product template works like a charm

### PR DESCRIPTION
**Pull request by flotho**
FIX #1097 
thanks @saxomanu

### CODE REVIEW

**Comment by flotho** [comment]
codecov concern the module product_supplier_info which is not part of this PR
image

**Comment by flotho** [comment]
Hi @hailangvn @saxomanu thanks to both of you, any review would be welcome

**Review by hailangvn — APPROVED** [review]
LGTM. Thank you for the work.

**Review by MPoch-PlanetaTIC — APPROVED** [review]
Tested ok.

**Comment by flotho** [comment]
cool, everything is green and apporved for merged !

**Comment by ioans73** [comment]
@OCA/product-maintainers could you merge please?

**Pull request merged**
