### PR TITLE
[13.0][MIG] product_state to v13 + improvements

### PR DESCRIPTION
**Pull request by benwillig**
As https://github.com/OCA/product-attribute/pull/512 is not very active, here is a new PR.

Also includes improvements from https://github.com/OCA/product-attribute/pull/574

### CODE REVIEW

**Review by Cedric-Pigeon — APPROVED** [review]
code review

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by emagdalenaC2i — COMMENTED** [review]
LGTM But see the last changes in #574

**Comment by BT-jstein** [comment]
@rousseldenis May I ask you to merge it?

**Comment by pedrobaeza** [comment]
Please see #657 for several fixes needed in the new approach (migration script shouldn't be needed, as you should come when migrating from 12.0.2.0.0).

**Pull request merged**
