### PR TITLE
[14.0][MIG] product_custom_info  13.0 -> 14.0

### PR DESCRIPTION
**Pull request by ilyasProgrammer**

### CODE REVIEW

**Comment by ilyasProgrammer** [comment]
@rousseldenis @chienandalu can someone help to figure out pre commit issue reason?

**Comment by francesco-ooops** [comment]
@OCA/product-maintainers Hi, does anyone know why precommit is failing?

**Review by francesco-ooops — APPROVED** [review]
LGTM

**Comment by rousseldenis** [comment]
@ilyasProgrammer I think you have still former files in setup.

Normally, if you have installed pre-commit locally, you can run `pre-commit run -a` and it should be fixed.

Either you can install setuptools-odoo for your user (`pipx install setuptools-odoo`) and run setuptools-odoo-make-default script : https://github.com/acsone/setuptools-odoo#setuptools-odoo-make-default-helper-script

**Comment by ilyasProgrammer** [comment]
moved here https://github.com/OCA/product-attribute/pull/1054

**Pull request closed without merging**
