### PR TITLE
[17.0] [MIG] product_supplierinfo_revision: Migration to 17.0

### PR DESCRIPTION
**Pull request by bizzappdev**

### CODE REVIEW

**Comment by florenciafrigieri2** [comment]
@bizzappdev Hello! Can you check why the runboat is still pending? So I can test it. Thanks!

**Review by jjscarafia — APPROVED** [review]
+1 tech review

**Review by florenciafrigieri2 — APPROVED** [review]
Functional review, the vendor pricelist are being correctly change.

**Comment by florenciafrigieri2** [comment]
@pedrobaeza Pedro, can you check this PR?

**Comment by pedrobaeza** [comment]
Well, there are changes that belongs to the migration commit (the README.rst and index.html ones), but let's merge it as it's not critical:

/ocabot merge nobump

**Pull request merged**
