### PR TITLE
[MIG][12.0] product_weight

### PR DESCRIPTION
**Pull request by tbaden**
Migration of product_weight to v12

### CODE REVIEW

**Comment by tbaden** [comment]
added missing commit history

**Comment by tbaden** [comment]
@pedrobaeza runbot is getting killed after 40 minutes without valid logs to check.
do you have any idea?

**Comment by pedrobaeza** [comment]
There's a problem right now with the sizing of the servers. Let's see if @gurneyalex can fix it soon.

Meanwhile, force a rebuild to see if you can get it.

**Review by florian-dacosta — CHANGES_REQUESTED** [review]
Hi,
Thanks for the PR.
There is a bug in case of multi level bom if the bom lines have a quantity different than 1
More explanation and the fix here : https://github.com/tbaden/product-attribute/pull/1

**Comment by tbaden** [comment]
@florian-dacosta thanks for the information, I'll attend these changes at the end of this week.

**Comment by pedrobaeza** [comment]
Any news on this?

**Comment by tbaden** [comment]
@pedrobaeza is that the right way to merge the fix into the PR?
btw. thanks for the reminder, somehow missed this one

**Comment by pedrobaeza** [comment]
Yes, but I see one line that can be removed commented on the original PR.

**Comment by tbaden** [comment]
fixed it.

**Review by pedrobaeza — APPROVED** [review]
Amended commit history and changes seems OK, so counting with implicit @florian-dacosta approval, I'm merging.

**Pull request merged**
