### PR TITLE
[17.0][MIG] product_pricelist_fixed_currency_rate: Migration to 17.0

### PR DESCRIPTION
**Pull request by kobros-tech**
I had to troubleshoot many bugs and they are not from my side.

I installed pandoc manually.
I modified a wrong code which is written in the documentation that describes how to use hooks.

### CODE REVIEW

**Review by LoisRForgeFlow — COMMENTED** [review]
Hi @kobros-tech 

Thanks for contributing. It looks good. One question though, any reason to covert all readme fragments to markdown?

**Comment by kobros-tech** [comment]
> Hi @kobros-tech
> 
> Thanks for contributing. It looks good. One question though, any reason to covert all readme fragments to markdown?

@LoisRForgeFlow 
when I run precommit command it converts marked down file like contributers file to be marked down then it gets deleted when I commit.

I don't know why but this is what happens.

**Comment by kobros-tech** [comment]
@kobros-tech 
@LoisRForgeFlow 
@mymage 
@Ivorra78 
@rvalyi

**Comment by LoisRForgeFlow** [comment]
> > Hi @kobros-tech
> > Thanks for contributing. It looks good. One question though, any reason to covert all readme fragments to markdown?
> 
> @LoisRForgeFlow when I run precommit command it converts marked down file like contributers file to be marked down then it gets deleted when I commit.
> 
> I don't know why but this is what happens.

I didn't realize that this was automated until now... thanks!

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Comment by kobros-tech** [comment]
@mymage 
@LoisRForgeFlow 
@OCA-git-bot 

I have added some tests for the new 17.0 version that were not covered in the previous 16.0 version.
There was a red flag asked me to test some values and I made the update on the commit for this reason.

**Review by mymage — APPROVED** [review]
LGTM functionally on runboat

**Comment by kobros-tech** [comment]
@LoisRForgeFlow 
@mymage 
Can we merge the pull request?

/ocabot merge patch

**Review by rousseldenis — APPROVED** [review]

**Comment by rousseldenis** [comment]
@kobros-tech For next time, it is better to put improvements  in separate commits than migration one. That allows to easily backport or forwardport.

**Comment by kobros-tech** [comment]
> @kobros-tech For next time, it is better to put improvements in separate commits than migration one. That allows to easily backport or forwardport.

Thanks for notification, I promise I will put this into my account.

**Pull request merged**
