### PR TITLE
14.0 mig product pricelist supplierinfo

### PR DESCRIPTION
**Pull request by mourad-ehm**

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
LGTM. Could you squash?

**Review by ferranmateu — APPROVED** [review]
Functional review OK!

**Comment by rousseldenis** [comment]
@mourad-ehm Could you check Travis ?

**Comment by desdelinux** [comment]
@mourad-ehm  @dreispt Could you check Travis?

**Comment by dreispt** [comment]
Superseded by #1000 🤷🏼‍♂️

**Pull request closed without merging**
