### PR TITLE
[13.0][MIG] product_dimension

### PR DESCRIPTION
**Pull request by EmailsGmails**

### CODE REVIEW

**Comment by grindtildeath** [comment]
@EmailsGmails 
Thanks for migrating this module. 
However, your PR doesn't respect OCA guidelines to keep git HISTORY as stated in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#howto
Can you please fix this?

**Comment by grindtildeath** [comment]
@EmailsGmails @Tatider Thanks again for the effort, but the last commit should still be split between the application of pre-commit and your work to migrate to version 13.0.
I did it on my fork as an example if you want to take a look at it: https://github.com/grindtildeath/product-attribute/commits/13.0-mig-product_dimension :wink:

**Comment by Tatider** [comment]
> @EmailsGmails @Tatider Thanks again for the effort, but the last commit should still be split between the application of pre-commit and your work to migrate to version 13.0.
> I did it on my fork as an example if you want to take a look at it: https://github.com/grindtildeath/product-attribute/commits/13.0-mig-product_dimension 😉

Thank you) Commits now split, and old migration scripts removed as in your's example. And I also added "readme/HISTORY.rst" file.

**Review by simahawk — APPROVED** [review]
LG

**Review by emagdalenaC2i — APPROVED** [review]
LGTM

**Pull request merged**
