### PR TITLE
[16.0][ADD] product_code_regex_validation

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**
Module to add regex validation of product codes based on a expression defined at product category level

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Works good!

**Review by LoisRForgeFlow — APPROVED** [review]
Code review :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Review by ChrisOForgeFlow — APPROVED** [review]
LGTM, great!

**Comment by JordiMForgeFlow** [comment]
@OCA/product-maintainers could we get this one merged? :)

**Pull request merged**
