### PR TITLE
[16.0][FIX] product_packaging_level: Preserve sequence order

### PR DESCRIPTION
**Pull request by santostelmo**
Restore original order to prevent altering behavior when packaging is reordered in the view.
(see explanation here : https://github.com/OCA/sale-workflow/pull/2939 )

That PR also fixes issue where sequence values could not be edited.
https://github.com/OCA/product-attribute/pull/1518#pullrequestreview-1895051140

### CODE REVIEW

**Comment by simahawk** [comment]
@santostelmo ping :)
Also: shall we close  #1518?

**Comment by santostelmo** [comment]
> @santostelmo ping :) Also: shall we close #1518?

IMO we can close 1518.

Tests falling in another module: product_supplierinfo_for_customer

**Comment by simahawk** [comment]
Please rebase

**Comment by santostelmo** [comment]
Rebased

**Review by cyrilmanuel — APPROVED** [review]

**Pull request merged**
