### PR TITLE
[ADD] stock_lot_is_archived

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Review by aliciagaarzo — COMMENTED** [review]
Hi, could you change the tests to cover all cases?

**Comment by rousseldenis** [comment]
> Hi, could you change the tests to cover all cases?

@aliciagaarzo Done. Thanks for the review

**Review by aliciagaarzo — APPROVED** [review]

**Review by hugo-cordoba — APPROVED** [review]
LGTM (Code review)

**Comment by lmignon** [comment]
@rousseldenis Can you reopen and merge this one?

**Pull request merged**
