### PR TITLE
[15.0][MIG] product_logistics_uom

### PR DESCRIPTION
**Pull request by flachica**

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]

**Review by HviorForgeFlow — CHANGES_REQUESTED** [review]
@flachica could you include https://github.com/OCA/product-attribute/pull/1170 ? Thanks!

**Comment by flachica** [comment]
> @flachica could you include #1170 ? Thanks!

Included @HviorForgeFlow

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by rousseldenis** [comment]
@flachica Could you just rename your last commit as the fix is two commits before ? Thanks

**Pull request merged**
