### PR TITLE
[16.0] [MIG] product_packaging_dimension

### PR DESCRIPTION
**Pull request by marielejeune**

### CODE REVIEW

**Comment by marielejeune** [comment]
Depends on https://github.com/OCA/product-attribute/pull/1160

**Review by apineux — APPROVED** [review]

**Review by lmignon — APPROVED** [review]
Thank you  @marielejeune LGTM (Code review + Functional tests)

**Review by rousseldenis — APPROVED** [review]

**Comment by jbaudoux** [comment]
`max_weight` should have been dropped in v16. I posted a comment here https://github.com/OCA/product-attribute/pull/1221#pullrequestreview-1364840332 in this regards

**Pull request merged**
