### PR TITLE
[17.0][mig] product state

### PR DESCRIPTION
**Pull request by mostafabarmshory**

### CODE REVIEW

**Review by fardinmardani — APPROVED** [review]
All things are Ok

**Comment by mostafabarmshory** [comment]
@fardinmardani 

Here is the same one. Would you check and write review on it, please?

https://github.com/OCA/product-attribute/pull/1458

**Comment by fardinmardani** [comment]
> @fardinmardani
> 
> Here is the same one. Would you check and write review on it, please?
> 
> #1458

Yes, you are right

**Comment by pedrobaeza** [comment]
Migration already existing: #1458, so closing

**Pull request closed without merging**
