### PR TITLE
[fix] prod image update broken

### PR DESCRIPTION
**Pull request by simahawk**
prod image update broken w/ no image on template #228

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@lasley @sergio-teruel, can you check this?

**Review by lasley — APPROVED** [review]
Yup, totally. Good fix @simahawk

**Comment by lasley** [comment]
@simahawk It would be awesome if you added a test case for this edge

**Review by sergio-teruel — APPROVED** [review]

**Comment by lasley** [comment]
@simahawk - Were you planning on porting this to v10?

**Comment by lasley** [comment]
Oh wait I just realized my PR is still in QA. ~~I'll port it!~~ I already ported it!

**Pull request merged**
