### PR TITLE
[17.0][MIG] product_code_mandatory: Migration to 17.0

### PR DESCRIPTION
**Pull request by fd-oerp**

### CODE REVIEW

**Comment by fd-oerp** [comment]
Hi @pedrocasi @Yvesldff 

Could you please review this PR and let me know if any corrections are needed?

Thank you

**Comment by fd-oerp** [comment]
Hi @sudhir-erpharbor 

Could you please review this PR and let me know if anything needs to be updated?

Thank you

**Comment by adriresu** [comment]
Tested locally and looks good to me! 👍

**Review by adriresu — APPROVED** [review]

**Comment by fd-oerp** [comment]
Hi,

May I have any update regarding this PR, please?
Please let me know if anything needs to be improved.

Thank you

**Comment by fd-oerp** [comment]
Hi, 

Could this PR proceed further, or please let me know if anything needs to be updated on my end?

Thank you

**Pull request closed without merging**
