### PR TITLE
12.0-[UPD] Update Config

### PR DESCRIPTION
**Pull request by victor-champonnois**
Running copier update

### CODE REVIEW

**Comment by carmenbianca** [comment]
@victor-champonnois You need to bump the template again.

**Comment by victor-champonnois** [comment]
@carmenbianca done

**Comment by rousseldenis** [comment]
@victor-champonnois Could you squash your commits ?

**Comment by victor-champonnois** [comment]
@rousseldenis commits squashed !

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
