### PR TITLE
[ADD] New module product_nutritional_info

### PR DESCRIPTION
**Pull request by manuelcalerosolis**
This module introduces the nutritional information field necessary for the sale of food products.

image

### CODE REVIEW

**Review by legalsylvain — COMMENTED** [review]
Hola @manuelcalerosolis 

thanks for sharing this module. this field is adding a unique text field ? Why didn't you introduced structured fields ?

**Comment by manuelcalerosolis** [comment]
> Hola @manuelcalerosolis
> 
> thanks for sharing this module. this field is adding a unique text field ? Why didn't you introduced structured fields ?

@legalsylvain nutritional information can be very varied, it does not have a fixed structure, the intention of this PR is to show the client this information at the time of sale, nothing more.

**Comment by pedrobaeza** [comment]
I prefer the scheme `base_custom_info` + `product_custom_info` + possible `website_custom_info`

**Comment by manuelcalerosolis** [comment]
> product_custom_info



> I prefer the scheme `base_custom_info` + `product_custom_info` + possible `website_custom_info`

Without a doubt it is a much more flexible model, I will look at it possibly should include more custom fields.

In any case, this PR has no more pretensions, if someone likes it, they can use it.

**Comment by pedrobaeza** [comment]
But this is not `nutritional info`. It's a text that it's included in website e-commerce... so better to be generic and:

- Host it on OCA/e-commerce, not here.
- Call the module `website_sale_product_extra_info` or similar.
- Call the field `website_other_info` or similar. There's already `website_description` field in standard.

**Comment by manuelcalerosolis** [comment]
> * website_description



> But this is not `nutritional info`. It's a text that it's included in website e-commerce... so better to be generic and:
> 
> * Host it on OCA/e-commerce, not here.
> * Call the module `website_sale_product_extra_info` or similar.
> * Call the field `website_other_info` or similar. There's already `website_description` field in standard.

I will move it as soon as possible.

Thanks.

**Comment by pedrobaeza** [comment]
I don't see any way the website part in this module, so the screenshot doesn't belong to this content.

**Comment by pedrobaeza** [comment]
And one last thing: please update your committer mail, as it still points to the old one:

Selección_050

**Comment by manuelcalerosolis** [comment]
> And one last thing: please update your committer mail, as it still points to the old one:
> 
> Selección_050

I forgot to remove it. Done!

**Pull request closed without merging**
