### PR TITLE
[17.0][FW] product_state: multiple ports from 14.0

### PR DESCRIPTION
**Pull request by henrybackman**
Port of the following PRs from 14.0 to 17.0:
- #1074
- #1124

### CODE REVIEW

**Comment by henrybackman** [comment]
Tests from another module `uom_category_active` are failing but I am not able to connect them to the changes done in this PR. Unsure how to proceed.

**Comment by ivantodorovich** [comment]
Even if unrelated, we'll need to investigate and fix it in order to merge this one :/

Having a quick look on the failing module.. I honestly don't understand how that test managed to originally succeed.
It seems contradictory to the actual code.

https://github.com/OCA/product-attribute/blob/5a79222e1ce32abfe5721f6e80a501f71d780605/uom_category_active/tests/test_uom_category_active.py#L28-L34

https://github.com/OCA/product-attribute/blob/5a79222e1ce32abfe5721f6e80a501f71d780605/uom_category_active/models/uom_category.py#L22-L25


My recommendation: remove the assertRaises lines in a separate PR, pinging the module author to check

**Comment by henrybackman** [comment]
@ivantodorovich Seems like this test failure is not related to this and affects all PRs:
- https://github.com/OCA/product-attribute/pull/1754

**Review by simahawk — APPROVED** [review]
CI fixed on https://github.com/OCA/product-attribute/pull/1760

**Review by grindtildeath — APPROVED** [review]

**Pull request merged**
