### PR TITLE
[13.0][NEW] stock_account_product_cost_security: New module to hide cost elements according to product cost security

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT21850

### CODE REVIEW

**Comment by sergio-teruel** [comment]
Rebase done after product_cost_security has been merged

**Review by emagdalenaC2i — APPROVED** [review]
LGTM and product_cost_security has been already merged

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@sbidoul @guewen this is insane. Adding this module creates a pylint problem in other module! Do you know this problem and know any workaround, please?

**Comment by sbidoul** [comment]
@pedrobaeza we have hit that same issue last week on a customer repo. Not had time to investigate yet. I think (not sure) the way `pre-commit` invokes `pylint` (i.e. by passing the full list of files) triggers a bug in in the `missing-manifest-dependency` check of `pylint-odoo`. cc/ @moylop260

**Comment by moylop260** [comment]
Maybe you like using `pre-commit` without `--all`
[  --all-files, -a       Run on all the files in the repo.](https://pre-commit.com/#pre-commit-run)

https://github.com/OCA/product-attribute/blob/9767e2da0962164b8730ad10ec9d3765cdd4959d/.travis.yml#L26

**Comment by pedrobaeza** [comment]
I don't get you, @moylop260. The problem here is that a false warning prevents green status. You can see it in current Travis (that it's executed for all files).

**Comment by moylop260** [comment]
> Adding this module creates a pylint problem in other module! Do you know this problem and know any workaround, please?

I didn't realize that you are talking about a false warning.
I thought that you are talking about avoid running checks for other modules.

Let me check the false warning...

**Comment by moylop260** [comment]
First step running it locally I didn't reproduce it:
 - Screen Shot 2020-02-11 at 13 15 02

Let me check it using a clean docker container...

**Comment by pedrobaeza** [comment]
Have you tried with this exact branch? It only happens with it.

**Comment by moylop260** [comment]
Yes, I'm using this branch.
You can check my bash using that sha.
I'm fetching all PR from git and I just did a checkout to this one.

I will finish the clean docker container soon...

**Comment by pedrobaeza** [comment]
Great, thanks for checking!

**Comment by moylop260** [comment]
FYI It was reproduced:
 - Screen Shot 2020-02-11 at 13 44 09

I'm using the following Docker clean environment:
```Dockerfile
FROM ubuntu:18.04
RUN apt-get update && apt-get install -y python3 python3-pip git
RUN pip3 install pre-commit
RUN git clone https://github.com/Tecnativa/product-attribute.git -b 13.0-PR-stock_account_product_cost_security
RUN (cd product-attribute && pre-commit run --all || true)
```
Now, I will looking for a fix for this.


NOTE: An unrelated aditional fix was required: https://github.com/OCA/pylint-odoo/pull/272
```bash
Traceback (most recent call last):
  File "/root/.cache/pre-commit/repov9q9gh9a/py_env-python3/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/root/.cache/pre-commit/repov9q9gh9a/py_env-python3/lib/python3.6/site-packages/pylint/__init__.py", line 20, in run_pylint
    Run(sys.argv[1:])
  File "/root/.cache/pre-commit/repov9q9gh9a/py_env-python3/lib/python3.6/site-packages/pylint/lint.py", line 1628, in __init__
    linter.check(args)
  File "/root/.cache/pre-commit/repov9q9gh9a/py_env-python3/lib/python3.6/site-packages/pylint/lint.py", line 943, in check
    self._do_check(files_or_modules)
  File "/root/.cache/pre-commit/repov9q9gh9a/py_env-python3/lib/python3.6/site-packages/pylint/lint.py", line 1075, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/root/.cache/pre-commit/repov9q9gh9a/py_env-python3/lib/python3.6/site-packages/pylint/lint.py", line 1158, in check_astroid_module
    walker.walk(ast_node)
  File "/root/.cache/pre-commit/repov9q9gh9a/py_env-python3/lib/python3.6/site-packages/pylint/utils.py", line 1300, in walk
    cb(astroid)
  File "/root/.cache/pre-commit/repov9q9gh9a/py_env-python3/lib/python3.6/site-packages/pylint_odoo/misc.py", line 197, in visit_module
    self.wrapper_visit_module(node)
  File "/root/.cache/pre-commit/repov9q9gh9a/py_env-python3/lib/python3.6/site-packages/pylint_odoo/misc.py", line 183, in wrapper_visit_module
    if not check_method():
  File "/root/.cache/pre-commit/repov9q9gh9a/py_env-python3/lib/python3.6/site-packages/pylint_odoo/checkers/modules_odoo.py", line 420, in _check_rst_syntax_error
    os.path.join(self.module_path, rst_file))
  File "/root/.cache/pre-commit/repov9q9gh9a/py_env-python3/lib/python3.6/site-packages/pylint_odoo/misc.py", line 373, in check_rst_syntax
    return rst_lint(fname)
  File "/root/.cache/pre-commit/repov9q9gh9a/py_env-python3/lib/python3.6/site-packages/restructuredtext_lint/lint.py", line 98, in lint_file
    content = f.read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3238: ordinal not in range(128)
```

**Comment by moylop260** [comment]
@guewen @sbidoul @pedrobaeza 
The issue is with isort compatibility it was fixed from:
 - https://github.com/OCA/pylint-odoo/pull/263

So a bumpversion of pylint-odoo>=3.1.0 is required here:

 - https://github.com/OCA/product-attribute/blob/9767e2da0962164b8730ad10ec9d3765cdd4959d/.pre-commit-config.yaml#L49
 - https://github.com/OCA/product-attribute/blob/9767e2da0962164b8730ad10ec9d3765cdd4959d/.pre-commit-config.yaml#L45

Or maybe, this package is not required to pinned it since that we are (OCA) the maintainers.

In fact, [MQT is using the last one even if there is not a release](https://github.com/OCA/maintainer-quality-tools/blob/31b49e656cec8c53eb79b5560be8900f5ee1e503/travis/travis_install_nightly#L11):
 - `git+https://github.com/OCA/pylint-odoo.git`

Could you consider change it?

**Comment by sbidoul** [comment]
Thanks for the investigation and the release @moylop260 !

Pinning versions is important for pre-commit because it caches environments based on it: https://pre-commit.com/#using-the-latest-version-for-a-repository

**Comment by simahawk** [comment]
hi everyone :)
What's the state? Who's waiting for what? :thinking:

**Comment by rousseldenis** [comment]
@sergio-teruel

**Comment by sergio-teruel** [comment]
@rousseldenis @simahawk rebase done... waiting for travis!!

**Comment by rousseldenis** [comment]
@sergio-teruel Could you run pre-commit ?

**Comment by sergio-teruel** [comment]
@rousseldenis ready!!!

**Pull request merged**
