### PR TITLE
12.0 mig product sale tax price included

### PR DESCRIPTION
**Pull request by legalsylvain**
Trivial migration of module ``product_sale_tax_price_included``

This module displays sale price vat exc, if taxes are vat incl, and displays sale price vat incl if taxes are vat excl

image

CC : @quentinDupont

### CODE REVIEW

**Review by lfreeke — APPROVED** [review]
Functional test :+1:

**Review by quentinDupont — CHANGES_REQUESTED** [review]
Works fine, migrate french trad in this [PR](https://github.com/legalsylvain/product-attribute/pull/3)

**Review by quentinDupont — APPROVED** [review]

**Review by gaikaz — APPROVED** [review]
Code review, LGTM
Let's ship it!

**Review by Du-ma — APPROVED** [review]
Nice :rooster:!

**Comment by Du-ma** [comment]
Love the module icon btw.

**Comment by quentinDupont** [comment]
> Love the module icon btw.

ahah yes me too but that was a mistake !
I just changed the icon in this PR https://github.com/legalsylvain/product-attribute/pull/4 @legalsylvain :smile:

**Comment by Du-ma** [comment]
@quentinDupont 
Should have been a feature :smile:

**Comment by legalsylvain** [comment]
Hi maintainers. Could you consider merge this PR with 4 approvals ? 

thanks !

**Comment by legalsylvain** [comment]
thanks @dreispt !

**Pull request merged**
