### PR TITLE
[14.0][MIG] product_pricelist_supplierinfo: Migration to 14.0

### PR DESCRIPTION
**Pull request by victoralmau**
Migration to 14.0

Please @CarlosRoca13 and @pedrobaeza can you review it?

@Tecnativa TT31816

### CODE REVIEW

**Review by CarlosRoca13 — APPROVED** [review]
Code review :+1:

**Review by pedrobaeza — APPROVED** [review]
Tested on runboat and code review

**Comment by pedrobaeza** [comment]
@sbidoul is there any problem with ocabot?

**Pull request merged**
