### PR TITLE
[IMP] product_secondary_unit: Remove product secondary units if a product is deleted

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa
TT22863
@carlosdauden @Tardo Review

### CODE REVIEW

**Review by carlosdauden — APPROVED** [review]

**Comment by rousseldenis** [comment]
@sergio-teruel Do you plan to backport this ?

**Review by rousseldenis — APPROVED** [review]
Makes sense!

**Comment by sergio-teruel** [comment]
@rousseldenis  Yes.. for v12

**Review by Tardo — APPROVED** [review]

**Pull request merged**
