### PR TITLE
[IMP] product_cost_security: clarify product cost edit required permissions

### PR DESCRIPTION
**Pull request by yajo**
As seen in https://github.com/OCA/margin-analysis/pull/198#pullrequestreview-1951828542, a user needs some other group that grants them permissions for editing products, apart from this one that allows them to edit product cost.

This might not seem obvious to the user, so it's better to document it.

Btw, I renamed the groups to be shorter. Still easy to understand, now that groups are grouped (🥁).

@moduon MT-5158

### CODE REVIEW

**Comment by rafaelbn** [comment]
@sergio-teruel @carlosdauden @Gelojr @fcvalgar please codul you review the improved readme and groups. For me is more intuitive for the new users 😄 ❤️ 

Let us know please! Thanks!

**Comment by Gelojr** [comment]
> @sergio-teruel @carlosdauden @Gelojr @fcvalgar please codul you review the improved readme and groups. For me is more intuitive for the new users 😄 ❤️
> 
> Let us know please! Thanks!

I think it's clear

**Comment by fcvalgar** [comment]
It's OK

**Review by Gelojr — APPROVED** [review]
LGTM

**Review by fcvalgar — APPROVED** [review]

**Review by edlopen — APPROVED** [review]
LGTM

**Review by rafaelbn — APPROVED** [review]
/ocabot merge minor

**Comment by rafaelbn** [comment]
I'm not PSC of this repo sorry. We should wait for a maintainer. We could add one of us as maintainer as we should and maintaing this module through versions @yajo

**Pull request merged**
