### PR TITLE
[13.0][IMP] product_secondary_unit: Allow to archive secondary units

### PR DESCRIPTION
**Pull request by sergio-teruel**
CC @Tecnativa TT34040

ping @carlosdauden @chienandalu

### CODE REVIEW

**Review by carlosdauden — APPROVED** [review]

**Review by victoralmau — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]

**Comment by sergio-teruel** [comment]
@kittiu Ok, for me, you ca do it... Remove cancel state from states list to unlink a review.
Only take into account that you can cancel a sale order and set to quotation...

**Comment by kittiu** [comment]
> @kittiu Ok, for me, you ca do it... Remove cancel state from states list to unlink a review. Only take into account that you can cancel a sale order and set to quotation...

Not sure this is right thread.

**Comment by sergio-teruel** [comment]
Upppsss sorry @kittiu I have lost the other thread!!!

**Pull request merged**
