### PR TITLE
[18.0][MIG] product_print_category: Migration to 18.0

### PR DESCRIPTION
**Pull request by BhaveshHeliconia**

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Diff review. LGTM. Thanks !

**Comment by remytms** [comment]
Thanks for porting this module to 18.0 !

Request from my side, can you edit the commit title [195f765](https://github.com/OCA/product-attribute/pull/1789/commits/195f7656de8d0454ac1ac588a88035225244a7f2) and remove the meniton to me (@remytms) because I get spammed each time a commit with mention to me is push on github. :)

I will do a review of the full code soon. :)

**Review by remytms — APPROVED** [review]
Code review, looks good to me.

**Pull request merged**
