### PR TITLE
[17.0][MIG] product_state: Migration to 17.0

### PR DESCRIPTION
**Pull request by NICO-SOLUTIONS**
Standard Migration to 17.0

### CODE REVIEW

**Comment by mostafabarmshory** [comment]
@pedrobaeza 

The migration did not merge with the branch 17.0.

I`ve made the same PR.

Would you check the problem and accept the PR please?

**Review by mostafabarmshory — APPROVED** [review]
Every things are ok

**Review by fardinmardani — APPROVED** [review]
All things are ok, I pull it and then run.
Everythings is ok.

**Pull request merged**
