### PR TITLE
[14.0][FW] product_assortment: multiple ports from 13.0

### PR DESCRIPTION
**Pull request by hailangvn**
This is to port the following PRs from 13.0 to 14.0:
* #878
* #898

### CODE REVIEW

**Comment by rousseldenis** [comment]
@Cedric-Pigeon

**Review by sebalix — APPROVED** [review]
LG to me, thank you

**Review by i-vyshnevska — APPROVED** [review]

**Comment by simahawk** [comment]
@hailangvn can you rebase?

**Comment by hailangvn** [comment]
@simahawk, the PR has been rebased. Thanks.

**Pull request merged**
