### PR TITLE
[17.0] mig product_net_weight

### PR DESCRIPTION
**Pull request by rvalyi**
This is the same PR as https://github.com/OCA/product-attribute/pull/1677 but with the pending adicional form layout fixes from https://github.com/OCA/product-attribute/pull/1735 extracted in a separate adicional commit.

I also sent a PR with this commit to https://github.com/osiell/product-attribute/pull/1 so I would say let's merge #1677 or this one depending on which one is faster...

cc @remihb @drewes @alexis-via @bosd @pedrobaeza

### CODE REVIEW

**Comment by legalsylvain** [comment]
Why i'm not pinged by the bot ?

**Review by Borruso — COMMENTED** [review]
//

**Review by Borruso — APPROVED** [review]

**Review by bosd — APPROVED** [review]
LGTM

**Review by rf-ife — APPROVED** [review]

**Pull request merged**
