### PR TITLE
[15.0][MIG] product_attribute_archive

### PR DESCRIPTION
**Pull request by JuanyDForgeflow**
@ForgeFlow
Standard Migration

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM! It works according the readme.

IMHO the archiving on the attribute should archive also the attribute values for that attribute. I understand that was not done for some functional reason so :+1:

**Review by DavidJForgeFlow — APPROVED** [review]
Functional review :+1: Code also LGTM

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
