### PR TITLE
[FIX] product_cost_security: use view-only security for product.supplierinfo

### PR DESCRIPTION
**Pull request by yajo**
This reverts commit 4928eefe9f5f6274268aae18835309870ae2b82c due to some cross-module incompatibilities (see https://github.com/OCA/product-attribute/pull/1654#issuecomment-2175691413).

Instead, it hides the field on view. This is not real security, but at least data will be available only for hacker salespersons.

@moduon MT-6548

### CODE REVIEW

**Review by rafaelbn — APPROVED** [review]
Functionally works 👍🏼 

I tested previous PR and it also works:

https://github.com/OCA/product-attribute/pull/1654#issuecomment-2175953404

Ping @chienandalu

**Review by chienandalu — COMMENTED** [review]
Thanks :)

**Comment by yajo** [comment]
After a brief post-mortem analysis, I can see the problem. It turns out that if you confirm a sale order that asks for a replenishment based on some stock orderpoint, a purchase order will be autocreated. `product.supplierinfo` records are checked to create that record.

FWIW https://github.com/odoo/odoo/pull/116799/files#diff-906d6e03445f06471f9090a266c93088f2b8a8f8d7d572e7ffcc7778acad061e takes a similar approach to this PR and just hides the purchase tab for non-purchase users upstream. Thus, this PR will have to be reverted for Odoo 17.

<details>

```
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/auto/addons/etl/controllers/dataset.py", line 15, in _call_kw
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 997, in get
    cache_value = field_cache[record._ids[0]]
KeyError: 34787

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1161, in __get__
    value = env.cache.get(record, self)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 1004, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'product.supplierinfo(34787,).price'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1632, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1659, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1863, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/auto/addons/website/models/ir_http.py", line 237, in _dispatch
    response = super()._dispatch(endpoint)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 716, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/auto/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/auto/addons/etl/controllers/dataset.py", line 19, in _call_kw
    return super()._call_kw(model, method, args, kwargs)
  File "/opt/odoo/auto/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/auto/addons/sale_management/models/sale_order.py", line 124, in action_confirm
    res = super().action_confirm()
  File "/opt/odoo/auto/addons/sale_financial_risk/models/sale.py", line 58, in action_confirm
    return super().action_confirm()
  File "/opt/odoo/auto/addons/sale/models/sale_order.py", line 827, in action_confirm
    self.with_context(context)._action_confirm()
  File "/opt/odoo/auto/addons/stock_customer_deposit/models/sale_order.py", line 32, in _action_confirm
    return super()._action_confirm()
  File "/opt/odoo/auto/addons/sale_stock/models/sale_order.py", line 149, in _action_confirm
    self.order_line._action_launch_stock_rule()
  File "/opt/odoo/auto/addons/sale_stock/models/sale_order_line.py", line 351, in _action_launch_stock_rule
    pickings_to_confirm.action_confirm()
  File "/opt/odoo/auto/addons/stock_picking_batch/models/stock_picking.py", line 120, in action_confirm
    res = super().action_confirm()
  File "/opt/odoo/auto/addons/stock/models/stock_picking.py", line 870, in action_confirm
    self.move_ids.filtered(lambda move: move.state not in ('draft', 'cancel', 'done'))._trigger_scheduler()
  File "/opt/odoo/auto/addons/stock/models/stock_move.py", line 2147, in _trigger_scheduler
    orderpoints.with_context(origins=orderpoints_context_by_company[company])._procure_orderpoint_confirm(
  File "/opt/odoo/auto/addons/stock/models/stock_orderpoint.py", line 552, in _procure_orderpoint_confirm
    self.env['procurement.group'].with_context(from_orderpoint=True).run(procurements, raise_user_error=raise_user_error)
  File "/opt/odoo/auto/addons/purchase_stock/models/stock.py", line 242, in run
    return super().run(procurements, raise_user_error=raise_user_error)
  File "/opt/odoo/auto/addons/mrp/models/stock_rule.py", line 230, in run
    return super(ProcurementGroup, self).run(procurements_without_kit, raise_user_error=raise_user_error)
  File "/opt/odoo/auto/addons/stock/models/stock_rule.py", line 476, in run
    getattr(self.env['stock.rule'], '_run_%s' % action)(procurements)
  File "/opt/odoo/auto/addons/purchase_stock/models/stock_rule.py", line 136, in _run_buy
    vals = self._update_purchase_order_line(procurement.product_id,
  File "/opt/odoo/auto/addons/purchase_stock/models/stock_rule.py", line 242, in _update_purchase_order_line
    seller = product_id.with_company(company_id)._select_seller(
  File "/opt/odoo/auto/addons/product/models/product_product.py", line 611, in _select_seller
    sellers = self._get_filtered_sellers(partner_id=partner_id, quantity=quantity, date=date, uom_id=uom_id, params=params)
  File "/opt/odoo/auto/addons/product/models/product_product.py", line 588, in _get_filtered_sellers
    sellers_filtered = self._prepare_sellers(params)
  File "/opt/odoo/auto/addons/purchase_requisition/models/product.py", line 18, in _prepare_sellers
    sellers = super(ProductProduct, self)._prepare_sellers(params=params)
  File "/opt/odoo/auto/addons/product/models/product_product.py", line 580, in _prepare_sellers
    return self.seller_ids.filtered(lambda s: s.partner_id.active).sorted(lambda s: (s.sequence, -s.min_qty, s.price, s.id))
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5583, in sorted
    ids = tuple(item.id for item in sorted(self, key=key, reverse=reverse))
  File "/opt/odoo/auto/addons/product/models/product_product.py", line 580, in <lambda>
    return self.seller_ids.filtered(lambda s: s.partner_id.active).sorted(lambda s: (s.sequence, -s.min_qty, s.price, s.id))
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1187, in __get__
    recs._fetch_field(self)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 3186, in _fetch_field
    self.check_field_access_rights('read', [field.name])
  File "/opt/odoo/auto/addons/product_cost_security/models/product_cost_security_mixin.py", line 63, in check_field_access_rights
    valid_fields = super().check_field_access_rights(operation, fields)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 2944, in check_field_access_rights
    raise AccessError(_(
AccessError: La operación solicitada no puede completarse debido a restricciones de seguridad.

Tipo de documento: Tarifa de proveedor (product.supplierinfo)
Operación: read
Ususario: 469
Campos:
- price (permitido para grupos'Costes del Producto / Acceso a ver el coste de productos')
```

</details>

**Comment by chienandalu** [comment]
Thanks for the research :)

For the `point_of_sale` compatibility I had to make some juggling on the `read` method as the field was required to load the data. Maybe something like that could be done with product.supplier_info.price

https://github.com/OCA/product-attribute/blob/16.0/pos_product_cost_security/models/product_product.py

**Pull request merged**
