### PR TITLE
[12.0][MIG] product_restricted_type

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Review by tbaden — APPROVED** [review]
thanks for the work 👍 
I did a code review: LGTM

**Review by LoisRForgeFlow — APPROVED** [review]
Functionally tested on runbot, works fine :+1:

**Review by nikul-serpentcs — APPROVED** [review]
Perfecto! :+1:

**Comment by rousseldenis** [comment]
@OCA/product-maintainers

**Review by lmignon — APPROVED** [review]

**Comment by flotho** [comment]
Hi, I didn't checked furthermore this PR, but is there any  possible conflicts with #491  ?

Regards

**Comment by legalsylvain** [comment]
Thanks.

**Pull request closed without merging**
