### PR TITLE
[15.0][MIG] product_pricelist_simulation: Migration to version 15.0

### PR DESCRIPTION
**Pull request by stefan-tecnativa**
cc @Tecnativa TT41452

@chienandalu @pilarvargas-tecnativa please review!

### CODE REVIEW

**Review by pilarvargas-tecnativa — COMMENTED** [review]
Just a small suggestion:
Perhaps the README.rst file could be improved by including in the CONFIGURE.rst file a short explanation of how to check or uncheck the "Show in simulation" checkbox in the price lists to give full information on the functionality of the module. This could be done by following the steps for creating a new price list.

**Comment by pilarvargas-tecnativa** [comment]
Code and functionality reviewed locally

**Review by pilarvargas-tecnativa — APPROVED** [review]

**Comment by stefan-tecnativa** [comment]
> Just a small suggestion: Perhaps the README.rst file could be improved by including in the CONFIGURE.rst file a short explanation of how to check or uncheck the "Show in simulation" checkbox in the price lists to give full information on the functionality of the module. This could be done by following the steps for creating a new price list.

The "Show in simulation" checkbox is checked by default when you install the module and try to create a new pricelist. However, the README can be improved by warning of this behavior.

**Review by chienandalu — APPROVED** [review]
LGTM :+1: Thanks!

**Pull request merged**
