### PR TITLE
[15.0][MIG] product_attribute_value_menu

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

### CODE REVIEW

**Review by DavidJForgeFlow — APPROVED** [review]
Functional review :+1: also code LGTM

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by JuanyDForgeflow — APPROVED** [review]
LGTM!

**Review by AaronHForgeFlow — APPROVED** [review]
Functional review

**Comment by JordiMForgeFlow** [comment]
Hi @JasminSForgeFlow 

Could you take into consideration also https://github.com/OCA/product-attribute/pull/1132? :)

**Comment by JasminSForgeFlow** [comment]
> Hi @JasminSForgeFlow
> 
> Could you take into consideration also #1132? :)

done, thanks

**Comment by JordiMForgeFlow** [comment]
Hi @JasminSForgeFlow 

Could you apply again the changes in #1132? small changes were added 4 days ago. The PR is now merged :)

**Comment by JasminSForgeFlow** [comment]
> Hi @JasminSForgeFlow
> 
> Could you apply again the changes in #1132? small changes were added 4 days ago. The PR is now merged :)

Done, Thanks

**Pull request merged**
