### PR TITLE
[14.0][ADD] product_category_product_link

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by bodedra** [comment]
@rousseldenis Thanks for your contribution.

Inside a product category form, we have "Products" smart button to navigate Products. It reads data from product.template object.

So would you please describe more how your new contribution help on this area?

**Comment by rousseldenis** [comment]
> @rousseldenis Thanks for your contribution.
> 
> Inside a product category form, we have "Products" smart button to navigate Products. It reads data from product.template object.
> 
> So would you please describe more how your new contribution help on this area?

I'm aware of that.

As described in readme, this add a technical field to retrieve products based on categ_id.

This is a base for a further module.

Will add a link to PR soon

**Comment by bodedra** [comment]
Make sense. Seems jump on this PR too early :smile:

**Comment by rousseldenis** [comment]
> Make sense. Seems jump on this PR too early 😄

No. Should have done both at same time. Disturbed during flow ;-)

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Tested with product_category_tax

**Review by bodedra — APPROVED** [review]

**Review by andreampiovesana — APPROVED** [review]
ready to merge

**Pull request merged**
