### PR TITLE
[14.0][MIG]product_net_weight

### PR DESCRIPTION
**Pull request by manuelregidor**
Standard migration

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Diff review. LGTM.

thanks !

**Review by rvalyi — APPROVED** [review]

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Comment by ValentinVinagre** [comment]
@HaraldPanten

**Review by HaraldPanten — APPROVED** [review]

**Comment by HaraldPanten** [comment]
@pedrobaeza @rvalyi could you merge this one?

**Comment by rvalyi** [comment]
> @pedrobaeza @rvalyi could you merge this one?

We are supposed to wait a bit. But given the module is trivial and the PR is approved by the module mantainer, let's go...

**Comment by HaraldPanten** [comment]
> > @pedrobaeza @rvalyi could you merge this one?
> 
> We are supposed to wait a bit. But given the module is trivial and the PR is approved by the module mantainer, let's go...

THX!!

**Comment by rousseldenis** [comment]
@manuelregidor @rvalyi runbot warnings were significant. @manuelregidor Could you fix digits ?

**Pull request merged**
