### PR TITLE
[MIG] product_medical: Migration to 14.0

### PR DESCRIPTION
**Pull request by dzungtran89**

### CODE REVIEW

**Comment by fshah-initos** [comment]
Code Review and Functionality Test Done.
LGTM

**Review by fshah-initos — APPROVED** [review]

**Comment by fshah-initos** [comment]
If somone could review this PR then this PR can be merged.

**Comment by fshah-initos** [comment]
If somone could review this PR then this PR can be merged.

**Comment by fshah-initos** [comment]
It would be great if we could get reviews here and merge the PR.

**Comment by fshah-initos** [comment]
It would be great if we could get reviews here and merge the PR.

**Comment by fshah-initos** [comment]
It would be great if we could get reviews here and merge the PR.

**Comment by fshah-initos** [comment]
It would be great if we could get reviews here and merge the PR.

**Comment by fshah-initos** [comment]
@TDu It would be great if you could add the reviews here

**Comment by fshah-initos** [comment]
It would be great if you could add the reviews here

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by TDu** [comment]
Thank you for migrating.
There seems to have been improvements on the module since this PR was opened, would be good to have them included.
https://github.com/OCA/product-attribute/commits/13.0/product_medical
Also translation commit can be squashed.

**Comment by fshah-initos** [comment]
@dzungtran89 Will you check the above comments and update the PR?

**Comment by dzungtran89** [comment]
> @dzungtran89 Will you check the above comments and update the PR?

sure, I'll ping you as soon as it's done

**Comment by dzungtran89** [comment]
hi @fshah-initos, I included the changes of 13.0 into this migration. Could you please have a look?

**Review by fshah-initos — APPROVED** [review]
LGTM

**Comment by fshah-initos** [comment]
It would be nice if we get the reviews here

**Comment by fshah-initos** [comment]
Seems it is ready can we merge this?

**Pull request merged**
