### PR TITLE
[11.0][IMP] product_multi_price: Several improvements

### PR DESCRIPTION
**Pull request by pedrobaeza**
* Adjusted terminology
* Better positioning of the prices list
* Adjusted README
* Remove useless constraint
* Make multi price name translatable
* Some guidelines

cc @Tecnativa TT20979

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Ready to be reviewed

**Review by chienandalu — COMMENTED** [review]
I wonder if there should be a translatable description field, specially to show the prices on reports

**Comment by pedrobaeza** [comment]
Yes, good idea. Make name translatable.

**Comment by chienandalu** [comment]
I meant another field. Translating name, could lead to issues with the proxy field, that searches by that name, don't you think?

**Comment by pedrobaeza** [comment]
Good question, and after meeting both, we have removed totally the compute proxy method.

**Comment by chienandalu** [comment]
Looks like romoving the proxy field makes the product compute_price method fail as it's expected to have a field with the same name of the price rule when we make the first compute. Maybe we keep it as a dummy field?

**Comment by pedrobaeza** [comment]
@chienandalu check https://github.com/OCA/product-attribute/compare/def30e7616f18982803360eee43a43e80dc78f97..103784460358825ec198a0c2a13b065300e52412 for a way of avoiding the field (mimicking the technique in product_pricelist_supplierinfo)

**Comment by chienandalu** [comment]
Oh, great :)

Some lint errors due to code removal: https://travis-ci.org/github/OCA/product-attribute/jobs/675338331#L312-L314

**Comment by pedrobaeza** [comment]
OK, let's see now

**Review by chienandalu — APPROVED** [review]
Ok now :)

**Pull request merged**
