### PR TITLE
8.0 product variant supplier

### PR DESCRIPTION
**Pull request by sebastienbeau**
This module give the possibility to specify a product supplier for a specific variant or for the product template

### CODE REVIEW

**Comment by sebastienbeau** [comment]
still not finish I am adding the readme and co

**Comment by pedrobaeza** [comment]
@sebastienbeau, you are duplicating the functionality that is already in this PR: https://github.com/OCA/product-variant/pull/19 (and in a more appropriated repo)

**Comment by sebastienbeau** [comment]
Ok, I see that you have extracted your module form our custom branch I am going to review you module

**Comment by pedrobaeza** [comment]
No, that module was before yours (remember you asked me). It's on https://github.com/serviciosbaeza/serviciosbaeza-odoo-addons

**Comment by sebastienbeau** [comment]
oups sorry typping fault !  your module form **Y**our custom branch I am going to review**Y**our module

**Pull request closed without merging**
