### PR TITLE
[15.0][MIG] stock_product_template_tags: Migration to 15.0

### PR DESCRIPTION
**Pull request by dhx**
Standard migration

### CODE REVIEW

**Review by jonasbuchholz — APPROVED** [review]

**Comment by dhx** [comment]
Hi @ivantodorovich this works in our setup in 15.0 without problems, do you see any problem merging this PR?

**Review by ivantodorovich — APPROVED** [review]

**Comment by dhx** [comment]
@pedrobaeza would be great if you could have look here if this looks OK to you as well.

**Pull request merged**
