### PR TITLE
[13.0][IMP] product_pricelist_direct_print_website_sale: Added new field

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT34038

To work correctly, this module depends of:

- [x] https://github.com/OCA/product-attribute/pull/991

ping @sergio-teruel @carlosdauden

### CODE REVIEW

**Review by Tardo — APPROVED** [review]
Code review

**Comment by pedrobaeza** [comment]
Can you please check Travis?

**Comment by CarlosRoca13** [comment]
@pedrobaeza Is failing because this PR depends on this other: https://github.com/OCA/product-attribute/pull/991

**Comment by pedrobaeza** [comment]
You can rebase now

**Comment by CarlosRoca13** [comment]
@pedrobaeza done!

**Comment by pedrobaeza** [comment]
@sergio-teruel @carlosdauden all yours!

**Review by sergio-teruel — APPROVED** [review]

**Pull request merged**
