### PR TITLE
[14.0][MIG]product_restricted_type: Migration to 14.0

### PR DESCRIPTION
**Pull request by GuillemCForgeFlow**
This pull request overwrites another one: https://github.com/OCA/product-attribute/pull/731

### CODE REVIEW

**Comment by GuillemCForgeFlow** [comment]
@ForgeFlow

**Comment by rousseldenis** [comment]
@GuillemCForgeFlow Thanks for this. The best is to ask original PR author to allow creating this one. Could you do it ?

**Comment by GuillemCForgeFlow** [comment]
> @GuillemCForgeFlow Thanks for this. The best is to ask original PR author to allow creating this one. Could you do it ?

Done. I wait for the reply.

**Comment by GuillemCForgeFlow** [comment]
It's been 6 days since I asked, and there's no reply yet. How should I proceed? @rousseldenis

**Review by HviorForgeFlow — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by JordiMForgeFlow** [comment]
FYI: This improvement could be included in the migration PR: https://github.com/OCA/product-attribute/pull/1055

**Comment by HviorForgeFlow** [comment]
@JordiMForgeFlow https://github.com/OCA/product-attribute/pull/1055 applied
@rousseldenis ready to merge

**Comment by rousseldenis** [comment]
@HviorForgeFlow Something more added ?

**Comment by HviorForgeFlow** [comment]
@rousseldenis just a rebase to fix pre-commit

**Pull request merged**
