### PR TITLE
[17.0][MIG] stock_production_lot_expired_date

### PR DESCRIPTION
**Pull request by Deriman-Alonso**
Standart Migration

### CODE REVIEW

**Review by luisDIXMIT — APPROVED** [review]
Tested on runboat, LGTM!

**Comment by christian-ramos-tecnativa** [comment]
@Deriman-Alonso Check your commits names and separate the pre-commit from the migration itself please. 
Looks good
Thanks

**Comment by Deriman-Alonso** [comment]
@Christian-RB Hi, That's done.
Thanks for the review.

**Review by christian-ramos-tecnativa — APPROVED** [review]

**Comment by peluko00** [comment]
Can you rebase @Deriman-Alonso  please

**Review by dreispt — APPROVED** [review]

**Pull request merged**
