### PR TITLE
[14.0][MIG] product_category_description: Migration to 14.0

### PR DESCRIPTION
**Pull request by klodr**
Simple version bump

### CODE REVIEW

**Comment by BriceCG** [comment]
I was waiting for this module
Thanks for merging

**Comment by R-ando** [comment]
It's good for me, thanks for merging

**Comment by Ihagatiana** [comment]
Thank you please merge

**Comment by idealsonDEV** [comment]
please merge

**Comment by razafimiandrisoa** [comment]
You can merge

**Review by alexis-via — APPROVED** [review]

**Review by BriceCG — APPROVED** [review]

**Review by BriceCG — APPROVED** [review]

**Review by R-ando — APPROVED** [review]

**Review by razafimiandrisoa — APPROVED** [review]

**Comment by klodr** [comment]
@simahawk Could you merge if you approuve and have rights to do so ?

**Pull request merged**
