### PR TITLE
product_gtin: port to v8

### PR DESCRIPTION
**Pull request by alexis-via**
Rename badly-named variable: ean13_len -> ean_len
Small code simplification

### CODE REVIEW

**Comment by rvalyi** [comment]
:+1: LGTM trivial fixes

**Comment by alexis-via** [comment]
@foutoucour 

I won't port it to the new API in this PR. But feel free to do it.

**Comment by foutoucour** [comment]
:-1:

**Comment by alexis-via** [comment]
@foutoucour 
The policy of OCA is not to force the use of the new API in all modules ported to v8. So you should not disapprove the PR only for that reason.
Odoo v8 has been released more than a month ago and the OCA product-attribute branch for v8 is still empty ; so we urgently need to get the modules out of **unported**, or OCA will loose its credibility. That's what I am trying to do with my contributions. A port to the new API can be done in another PR without problems.

**Comment by sbidoul** [comment]
I fully agree with @alexis-via here. Port to new API is not mandatory for 8.0.

:+1:

**Comment by lepistone** [comment]
I tried to migrate quite a few modules to the new API and I think that for a while we should not require it for oca modules. When it stabilzes and the core starts to use it more we can change our mind.

**Comment by rvalyi** [comment]
Hello, I also agree, that migrating the API is a "nice to have" but should not be mandatory yet. So I keep with my approval, further enhancements will be welcome later.

**Comment by pedrobaeza** [comment]
:+1:

I proceed with the merge, and anyone can port it to new API and make a PR if he/she wants.

**Pull request merged**
