### PR TITLE
12.0-add-configuration-files

### PR DESCRIPTION
**Pull request by victor-champonnois**

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
thanks !

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Are you sure you run the last OCA script ? 

- there are not tests in github workflows.
- there are some ``.rej`` files

**Comment by victor-champonnois** [comment]
@legalsylvain I just fetched the copier config from branch 14 and ran `copier update`. Is there something more I should do ?

**Comment by legalsylvain** [comment]
Oh I see. I know that there was no github folder before, but it was present, but with missing things.

So, OK for me, except the ``.rej`` files. What is that ?

**Comment by victor-champonnois** [comment]
@legalsylvain .rej seems to be caused by merge conflicts. I looked into them, I think they can be safely removed.

**Comment by legalsylvain** [comment]
Hi could you fix pre-commit ?

**Comment by legalsylvain** [comment]
(pre-commit run -a shoud fix most of the errors).

thanks !

**Comment by victor-champonnois** [comment]
@legalsylvain it's done. It's weird I had to change file permission for some python files.

**Comment by legalsylvain** [comment]
@dreispt : could we fast track this one ?

**Comment by legalsylvain** [comment]
could you rebase ? your branch miss the github action tests.

**Comment by victor-champonnois** [comment]
@legalsylvain rebased

**Comment by legalsylvain** [comment]
Sorry, but there is still a problem regarding the test that are missing.

**Comment by legalsylvain** [comment]
See OCA/pos github actions : https://github.com/OCA/pos/tree/12.0/.github/workflows (3 files)
in your branch : https://github.com/coopiteasy/product-attribute/tree/12.0-add-copier-precommit/.github/workflows (1 file)

Something is wrong when calling copier update. I don't know why but that has to be fixed.

**Comment by victor-champonnois** [comment]
I don't see where they are missing, could you show me ? I checked and I am on top of oca/12.0

**Comment by victor-champonnois** [comment]
@legalsylvain OK I see I didn't specify github as CI (Travis is the default). Now it's done. however I still don't have a stale.yml file, even though I said yes to `Create GitHub 'stale' action?`

**Comment by legalsylvain** [comment]
I don't know regarding the stale, but that's not a big deal. and stale will work because it exists in V16.

@OCA/community-maintainers : could we merge this one ?

**Review by legalsylvain — APPROVED** [review]

**Comment by legalsylvain** [comment]
superseded by : https://github.com/OCA/product-attribute/pull/1185

Should be closed.

**Pull request closed without merging**
