### PR TITLE
[12.0][FIX] product_state: Several fixes to new approach:

### PR DESCRIPTION
**Pull request by pedrobaeza**
- Hook is not considering archive products.
- Missing migration script that moves from previous version to this one.
- Incorrect creation of new states (without code).
- Performance in inverse state when installing the module / migrating from previous one.

@Tecnativa TT24914

### CODE REVIEW

**Review by rafaelbn — APPROVED** [review]
Production test :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Review by emagdalenaC2i — APPROVED** [review]
LGTM

**Comment by pedrobaeza** [comment]
@benwillig can you forward-port this to v13?

**Pull request merged**
