### PR TITLE
[MIG][16.0] uom_extra_data

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@alexis-via Could you fix pre-commit ?

**Comment by alexis-via** [comment]
done

**Comment by alexis-via** [comment]
ready to merge

**Comment by rousseldenis** [comment]
@alexis-via Could you split migration commit and pre-commit stuff ? Thanks

**Comment by alexis-via** [comment]
@rousseldenis No nit-picking please ! The is only a migration commit, there is no pre-commit stuff.

**Pull request closed without merging**
