### PR TITLE
[16.0][MIG] product_sticker: Migration to 16.0

### PR DESCRIPTION
**Pull request by Shide**
Standard migration, added @rafaelbn as a maintainer too.

MT-6566 @moduon @rafaelbn @yajo @fcvalgar @Gelojr @HaraldPanten please review if you want :)

### CODE REVIEW

**Review by edlopen — APPROVED** [review]
LGTM, thank you!

**Review by HaraldPanten — APPROVED** [review]
/ocabot merge nobump

**Comment by HaraldPanten** [comment]
Just remember to set the correct PR name. It could be useful for searching, etc.

**Review by fcvalgar — APPROVED** [review]
LGTM, thank you @Shide

**Comment by rafaelbn** [comment]
Thank you all! ❤️

**Pull request merged**
