### PR TITLE
[14.0][IMP] product_pricelist_assortment: rewrite base field in module, to translate it

### PR DESCRIPTION
**Pull request by solo4games**
Rewrite base field in this module, to be able to translate this field

### CODE REVIEW

**Comment by francesco-ooops** [comment]
@solo4games check [this](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message)

**Comment by gdgellatly** [comment]
I really don't get it. Why would we do this? Surely this is not right, it just feels like it will break any other modules using compute price or custom formulas and seems so unneeded. What am I missing?

**Comment by francesco-ooops** [comment]
@gdgellatly I don't know if this is the best technical solution, on the functional side the issue is that some fields in pricelist form cannot be translated in other languages, see https://github.com/OCA/product-attribute/pull/1369#issuecomment-1621428838

Do you have any suggestions on how to approach this?

**Comment by gdgellatly** [comment]
> @gdgellatly I don't know if this is the best technical solution, on the functional side the issue is that some fields in pricelist form cannot be translated in other languages, see [#1369 (comment)](https://github.com/OCA/product-attribute/pull/1369#issuecomment-1621428838)
> 
> Do you have any suggestions on how to approach this?

Hi, I have no idea, I only care about English and know nothing of translation. But from a code POV, to me this looks hugely unnecessary and pollutive. I would suggest however, if that in applying a perfectly normal and elegant inheritance solution (which IMHO this module does), that this somehow limits translation functionality, then the solution is not within the module itself, but in Odoo core. But that is just my opinion/suspicion. @pedrobaeza may have some thoughts.

**Comment by pedrobaeza** [comment]
Yes, if this is happening, you should notify/repair it at Odoo core ORM level.

**Pull request closed without merging**
