### PR TITLE
[16.0][FIX] product_pricelist_direct_print: inconsistent configuration fields

### PR DESCRIPTION
**Pull request by suker**
On printing wizard configuration, It should'nt display "attribute name fields" (latest pic) if "Show variants" is unchecked:

**Steps to reproduce:**

1. Check "Show Variants"
2. Check "Show Attribute Values"
3. Uncheck "Show Variants" (Show attribute values remains checked)
4. Attribute name fields are visible

**First and second step:**

image

**Third step**

image

@danielduqma 

[odoo-16/fl-v16#3075](https://git.factorlibre.com/odoo-16/fl-v16/-/issues/3075)

### CODE REVIEW

**Review by danielduqma — APPROVED** [review]
LGTM makes sense, thanks!

**Review by danielduqma — APPROVED** [review]
LGTM makes sense, thanks!

**Review by legalsylvain — APPROVED** [review]
make sense

**Comment by suker** [comment]
Thanks :smiley:

**Comment by adrip-s73** [comment]
@suker  please can you tell me the field "show_attribute_values" in which modulo is declared ?

**Pull request merged**
