### PR TITLE
[FIX] Added size=-1 for compatibility with integer indexes in Selecti…

### PR DESCRIPTION
**Pull request by gfcapalbo**
…on field.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
What is the rationale behind this?

**Comment by gfcapalbo** [comment]
Important FIx for allowing base_ext to work correctly. Selection fields in Odoo will usually have strings as indexes for every option, if the index is an INTEGER as in base and base_ext , it is mandatory to add size = -1 to the field attributes in order to allow the ORM to correctly evaluate the field and not return an UNKNOWN option.

**Comment by pedrobaeza** [comment]
Does this also happens on 7.0?

**Comment by gfcapalbo** [comment]
yes , untested , but the ORM code is unchanged. it will check for size=-1 to make integers work as indexes. As a matter of fact the 7.0 version had size=-1.
This is an undocumented Feature of selection field. It should be in the documentation of selection Fields I believe.  No fix needed for 7.0, it is already OK.

**Comment by pedrobaeza** [comment]
Yeah, indeed it should be documented. I didn't know about it.

**Comment by gfcapalbo** [comment]
Will this be approved? any thumbs up? @pedrobaeza  how can i advertise this?
I really don't want the defective version to stay in the main branch.
Here is the code in models.py that explains why we need size=-1 for selection fields with integer indexes

https://github.com/odoo/odoo/blob/8.0/openerp/models.py#L195-L196

**Comment by pedrobaeza** [comment]
OK, as this is a critical bug, I fast-track it with the corresponding acknowledge by my part.

**Comment by gfcapalbo** [comment]
thanks.

**Pull request merged**
