### PR TITLE
[14.0][MIG] product_total_weight_from_packaging

### PR DESCRIPTION
**Pull request by hparfr**
Depends of :

- [x] stock_packing_calculator https://github.com/OCA/stock-logistics-warehouse/pull/1050
- [x] product_packing_dimension https://github.com/OCA/product-attribute/pull/850

### CODE REVIEW

**Comment by rousseldenis** [comment]
@hparfr Could you put in PR's description depending PR's to help review?

**Review by claudiagn — COMMENTED** [review]
You need to put the module: stock_packaging_calculator in the runbot in order for it to work.

**Comment by hparfr** [comment]
@claudiagn the dependencies are now merged. You can update your review.

**Review by sebastienbeau — APPROVED** [review]
LGTM code review

**Comment by hparfr** [comment]
ping @Kev-Roche

**Review by Kev-Roche — APPROVED** [review]
LGTM

**Pull request merged**
