### PR TITLE
[14.0][MIG] product_categ_image

### PR DESCRIPTION
**Pull request by hailangvn**
This is just small migration together with other big one.

### CODE REVIEW

**Review by rousseldenis — CHANGES_REQUESTED** [review]
Could you solve this warning ?

image

**Comment by hailangvn** [comment]
Thanks @rousseldenis for triggering the merge. Yes, I will work on it soon.

**Comment by hailangvn** [comment]
Good day @rousseldenis. This PR has been rebased and updated.

**Comment by ventor-dev** [comment]
@hailangvn any updates to merge this?

**Comment by hailangvn** [comment]
Good day @ventor-dev, the warning has been resolved so this is ready to be merged.

**Review by ventor-dev — APPROVED** [review]

**Review by flotho — APPROVED** [review]
LGTM

**Comment by flotho** [comment]
hi @rousseldenis , request has been fullfilled. Any review possible ?

**Comment by flotho** [comment]
Hi @hailangvn I think a rebase could be a good idea to ease the merge.

**Comment by flotho** [comment]
Hi @rousseldenis , any review possible on this one

**Comment by hailangvn** [comment]
Thanks @flotho, @rousseldenis. This PR has been rebased.

**Review by flotho — APPROVED** [review]
hi @rousseldenis any chance you check the changes since your change request.
Looks ok

**Comment by hailangvn** [comment]
Rebased.

**Review by rvalyi — APPROVED** [review]

**Pull request merged**
