### PR TITLE
[13.0] [MIG] product_pricelist_direct_print_website_sale: Migration to v13.0

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT28443

Please @sergio-teruel @carlosdauden review this

### CODE REVIEW

**Comment by joao-p-marques** [comment]
Travis is red @CarlosRoca13

**Comment by pedrobaeza** [comment]
And please rename to proper name: `product_pricelist_direct_print_website_sale`.

**Comment by joao-p-marques** [comment]
Travis is still red :(

**Comment by CarlosRoca13** [comment]
@joao-p-marques I can't reproduce that error on local 😞

**Comment by CarlosRoca13** [comment]
@joao-p-marques can you review it now :)

**Review by joao-p-marques — APPROVED** [review]
Code and functional review :+1:

**Comment by pedrobaeza** [comment]
The OU change for the renaming is needed:

/ocabot merge nobump

**Comment by pedrobaeza** [comment]
I have done it directly for having all pieces:

https://github.com/OCA/OpenUpgrade/commit/ae8332fc1e3e790b2c316caef5889da630a08489

**Pull request merged**
