### PR TITLE
[9.0][NEW] product_list_price_tax_include: Write price in product template with taxes include

### PR DESCRIPTION
**Pull request by sergio-teruel**
Moved from sale-workflow: https://github.com/OCA/sale-workflow/pull/386

With this module you can write list price with taxes include.
You can write list price and price with tax is calculated or you can write list price with taxes and list price is also calculated.

cc@Tecnativa

### CODE REVIEW

**Review by rafaelbn — APPROVED** [review]
Tested in runbot

**Comment by rafaelbn** [comment]
@Tecnativa

**Review by luismontalba — APPROVED** [review]
Functionality tested on runbot

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Only one change: name should be product_pricelist_tax_included

**Review by cubells — APPROVED** [review]
cc @Tecnativa

renamed module.

code review and tested.

**Comment by lasley** [comment]
Looks like @pedrobaeza's rename comment has been attended to - merging.

**Pull request merged**
