### PR TITLE
[FIX] force rewrite of dimentional_uom_id on created new product

### PR DESCRIPTION
**Pull request by vrenaville**
When you create a product, the dimentional_uom_id must be write on the product

### CODE REVIEW

**Review by leemannd — APPROVED** [review]
Tests could be improved.

**Comment by pedrobaeza** [comment]
And the TODO seems to be a very big issue...

**Comment by leemannd** [comment]
@pedrobaeza The comment and technique used by @vrenaville is from odoo's core https://github.com/odoo/odoo/blob/9.0/addons/product/product.py#L679

**Comment by pedrobaeza** [comment]
Yeah, but that doesn't mean that is OK IMO. You know that Odoo doesn't do several things the right way, and the TODO is because of something. You can avoid it in this case I think.

**Comment by leemannd** [comment]
You're right, sayin it's in core isn't a suitable answer. Currently, this PR does the trick and without introducing something wrong. For the moment, I don't have the time to investigate further. :(

**Comment by guewen** [comment]
@pedrobaeza do you have a suggestion?

**Comment by pedrobaeza** [comment]
There are several:

- Remove field from template.
- Launch the write on the variants, not the rewrite of the same field. Anyway, I see no code for rewriting the field on the variants, so is this really working?

**Comment by rousseldenis** [comment]
Closing this as very old. Please feel free to reopen it if needed

**Pull request closed without merging**
