### PR TITLE
[16.0][MIG] product_price_history

### PR DESCRIPTION
**Pull request by legalsylvain**

### CODE REVIEW

**Comment by legalsylvain** [comment]
hum... it looks like the core model ``product.price.history`` disappeared after V12. Do you know if it has been replaced by other similar concept ? 
CC : @eLBati, @rousseldenis  (initial reviewers of https://github.com/OCA/product-attribute/pull/787)

thanks !

**Comment by eLBati** [comment]
Hi @legalsylvain see https://github.com/OCA/OpenUpgrade/blob/5837e173e7aa99447cc55c873941ceb4697802ea/addons/product/migrations/13.0.1.2/openupgrade_analysis_work.txt#L2

**Comment by legalsylvain** [comment]
> Hi @legalsylvain see https://github.com/OCA/OpenUpgrade/blob/5837e173e7aa99447cc55c873941ceb4697802ea/addons/product/migrations/13.0.1.2/openupgrade_analysis_work.txt#L2

... hum... Do you use this new model ``stock.valuation.layer`` ?

**Comment by eLBati** [comment]
Customers use It for stock valuation, But I never used it in a module

**Pull request closed without merging**
