### PR TITLE
[14.0][ADD] product_attribute_archive

### PR DESCRIPTION
**Pull request by kevinkhao**
This simple module allows archival of product attributes.

### CODE REVIEW

**Review by hparfr — APPROVED** [review]

**Comment by andreampiovesana** [comment]
you should add archive for values, model product.attribute.value in the same way

**Comment by kevinkhao** [comment]
@andreampiovesana done

**Review by andreampiovesana — APPROVED** [review]
test ok

**Comment by andreampiovesana** [comment]
@rousseldenis ok! do you merge?

**Pull request merged**
