### PR TITLE
[16.0] Fix build

### PR DESCRIPTION
**Pull request by simahawk**
Tackling some issues from #1513

### CODE REVIEW

**Comment by legalsylvain** [comment]
Thanks !

**Comment by simahawk** [comment]
There's an unrelated error on `abc_classification_product_level`
https://github.com/OCA/product-attribute/actions/runs/7955666562/job/21715009413?pr=1521#step:8:480

**Comment by legalsylvain** [comment]
> There's an unrelated error on abc_classification_product_level

The error is in the module ``product_abc_classification``

@rousseldenis, @lmignon @MiquelRForgeFlow, @lmarion-source

could you take a look ? 
thanks !

**Review by santostelmo — APPROVED** [review]

**Comment by simahawk** [comment]
> > There's an unrelated error on abc_classification_product_level
> 
> The error is in the module `product_abc_classification`
> 
> @rousseldenis, @lmignon @MiquelRForgeFlow, @lmarion-source
> 
> could you take a look ? thanks !

I'm on it

**Comment by simahawk** [comment]
Now the issue is on `product_supplierinfo_for_customer`

**Comment by simahawk** [comment]
To me the domain used to look for the customer info is wrong.
Failing test:

image

This means that the selected customer info should be the one w/ price = 100.0 because is the one assigned to the specific variant. However, the selection gives you back the generic price:
```
(Pdb++) product._select_customerinfo(partner=self.customer).price
30.0
```
When I look at the domain it seems wrong
```
Pdb++) product._prepare_domain_customerinfo({"partner_id": self.customer.id})
[('partner_id', '=', 49), '|', ('product_id', '=', 49), '&', ('product_tmpl_id', '=', 32), ('product_id', '=', False)]
```
By logic, I assume we should have an AND w/ partner and product and fallback w/ the OR. However I don't know this module at all...

@pedrobaeza @sergio-teruel @MiquelRForgeFlow @AaronHForgeFlow anyone can provide some feedback?

**Comment by pedrobaeza** [comment]
In a first sight, I don't see the domain incorrect. It's saying that:

- The partner should be 49
- And then, comply with one on these criteria:
  - The product is 49
  - Or the product is empty and the product template is 32, which should be the template for product 49

The only weird thing is that the partner ID and the product ID is the same, but reading the code, it seems legit.

**Comment by simahawk** [comment]
IMO there's something wrong because even if I have 2 records matching the partner and only one of them matches the variant I get the generic one (matching only the tmpl) as a result. Hence, I assume the domain is wrong.

**Comment by pedrobaeza** [comment]
But for that, there's this sort: https://github.com/OCA/product-attribute/blob/16.0/product_supplierinfo_for_customer/models/product_product.py#L138

**Comment by victoralmau** [comment]
IMO the solution for `product_supplierinfo_for_customer` is to set a `sequnce` for each element of `product.customerinfo` (sequence: 10 and sequence: 20 respectively for example).

**Comment by AaronHForgeFlow** [comment]
I think the matching of the variant is more important than the template. Perhaps the sorting is incorrect. Created PR with this: https://github.com/camptocamp/product-attribute/pull/4

**Comment by pedrobaeza** [comment]
@victoralmau see my previous comments. Anyway, you can exercise the solution in one PR if you see it's the proper one.

**Comment by pedrobaeza** [comment]
Fixed in #1528, although the solution doesn't convince me too much I have to say, as this reveals a flaw in the design.

**Comment by AaronHForgeFlow** [comment]
Tested in my local with this: https://github.com/camptocamp/product-attribute/pull/4 and test were not failing

**Comment by pedrobaeza** [comment]
But that's not very optimal in performance. We should try to avoid several filtered.

**Comment by AaronHForgeFlow** [comment]
@pedrobaeza  after @lmignon suggestion it works the same without the use of filtered: https://github.com/camptocamp/product-attribute/pull/4/files

**Comment by pedrobaeza** [comment]
Can you gather all and rebase for getting the proper solution?

**Comment by AaronHForgeFlow** [comment]
> Can you gather all and rebase for getting the proper solution?

Hi @pedrobaeza is this comment in regards my PR? I am afraid I did not get what you mean.

**Comment by pedrobaeza** [comment]
Yes, I mean to put here in this PR (by @simahawk or someone else) the needed things to get such proper code.

**Comment by simahawk** [comment]
I'll cherry-pick https://github.com/camptocamp/product-attribute/pull/4

**Comment by simahawk** [comment]
Are we all fine w/ these fixes?

**Review by pedrobaeza — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]

**Pull request merged**
