### PR TITLE
[10.0][ADD] product_code_unique module

### PR DESCRIPTION
**Pull request by chafique-delli**

### CODE REVIEW

**Review by OpenCode — APPROVED** [review]

**Review by OpenCode — COMMENTED** [review]
It doesn't work on runbot

**Review by bodedra — CHANGES_REQUESTED** [review]
runbot is  :red_circle: @chafique-delli may you fix it.

**Comment by chafique-delli** [comment]
@OpenCode , @bodedra , Ok, I'm looking to fix that.
Thank you,

**Comment by OpenCode** [comment]
@chafique-delli I tested the code on a local computer. When I install the modulo I can't find the constraint in the database on product_product table. The problem is the pre_init_product_code function. You set all the product without code as "DEFAULT_CODE" before module install but when Odoo try to create constraint in database, it found product with some code and constraint creation is interrupted. The query in pre_init_product_code function is wrong. Please, look at https://github.com/OCA/product-attribute/blob/11.0/product_code_unique/__init__.py#L9 and fix your code

**Comment by chafique-delli** [comment]
@OpenCode , You're right, I did not be careful to the query in pre_init_product_code function, it was incomplete.
I fix that.
Thank you,

**Comment by OpenCode** [comment]
@chafique-delli Travis and Runbot are red because the query is wrong. Please, try the changes on your locale installation before push them.

**Comment by OpenCode** [comment]
I restarted Travis. Now it's green. Code tested on Runbot and it's ok for me.

**Review by bodedra — APPROVED** [review]
LGTM. :+1:

**Comment by OpenCode** [comment]
@OCA/product-maintainers Can you merge it?

**Comment by bodedra** [comment]
@pedrobaeza

**Comment by lfreeke** [comment]
I get warning when enter and trying to save a product with a same product_code.

I notice that when I sneakly put a space after a same product_code it will save the product with out a unique warning. 

I still will give it a thumbs up, because it works as it should be and the space is a corner case that can be solved later if necessary. 

:+1:  (test)

**Pull request merged**
