### PR TITLE
[16.0][MIG] product_standard_price_tax_included

### PR DESCRIPTION
**Pull request by legalsylvain**
classical migration : 
- adapt to V16
- update documentation
- update french translation

### Description

this module extend Odoo Sale module to handle correctly the possibility to create and use pricelist **based on the cost Price**, if you are in a B2C configuration (VAT set with 'Price Tax inlude').

If you don't use VAT price tax Included, this module is useless.

**Typical Use Case**

You have a product :
- Cost : 1000€ (Vat Excl)
- Sale Price (Vat incl) : 2400€
- VAT : 20% (Price with Tax included)

You have a marginless pricelist based on the cost

Without this module, if you create a sale order, the price will be bad, and you will sale under your cost price.

sale_order_form_without_module

With this module installed, the price will be good and you will not loose the vat amount, when you realize this sale:

sale_order_form_with_module

This module fixes the problem,

* adding a new computed field 'Cost Price Tax Included' (``standard_price_tax_included``) on Product Product model, based on Cost Price Field and Sale Taxes Setting.

* adding a new key ``standard_price_tax_included`` on the field ``base`` of  the model ``product.pricelist.item``.

product_pricelist_item_form

### CODE REVIEW

**Comment by rousseldenis** [comment]
@legalsylvain Still WIP?

**Comment by legalsylvain** [comment]
> @legalsylvain Still WIP?

Hi @rousseldenis. Sorry I missed your remark. No it is ready for review. Made a mistake in the PR title.

thanks !

**Pull request closed without merging**
