### PR TITLE
[17.0][IMP] product_supplierinfo_for_customer: add search view

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**

### CODE REVIEW

**Review by JasminSForgeFlow — APPROVED** [review]

**Review by JoanSForgeFlow — APPROVED** [review]
LGMT!

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by Anxo82** [comment]
I've review code and it's OK, but I cant find view search. Could you say me where it is?

**Comment by JordiMForgeFlow** [comment]
@Anxo82 is in Sales > Configuration > Prices for customers. Now you can perform search in that menu:

image

**Comment by Anxo82** [comment]
@JordiMForgeFlow Sorry, I can't find it. I've review Sales > Configuration but it's not there.
imagen
Thanks

**Comment by JordiMForgeFlow** [comment]
@Anxo82 keep in mind you need https://github.com/OCA/sale-workflow/tree/16.0/product_supplierinfo_for_customer_sale

**Comment by Anxo82** [comment]
Ok, but It would be better add it in product_supplierinfo_for_customer_sale?, because if you dont have it  installed, you cant used search view.
Thanks

**Comment by JordiMForgeFlow** [comment]
@Anxo82 I added the view here as the view by itself does not depend on having the sale module, so it made sense to me to centralize it with the rest of the views in the core module. Also, if someone adds another module to add the view in a different menu outside sale, then the search view would need to be added again in the other module.

Nonetheless, this will probably not happen, so for me it wouldn't be a problem to move it to the other module.

**Review by Anxo82 — APPROVED** [review]
LGTM! @JordiMForgeFlow 
Thanks

**Pull request merged**
