### PR TITLE
Remove product_multi_company

### LINKED ISSUE #115: product-attribute/product_multi_company name conflicts with multi-company/product_multi_company
I propose to remove product-attribute/product_multi_company since it's unported from version 6.1

### PR DESCRIPTION
**Pull request by lmignon**
This fixes #115. The module is un ported from version 6.1 in product_attribute. Moreover, its name conflicts with an other module defined in OCA/multi-company

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1: 

Can you please remove it also from 9.0 branch?

**Comment by lmignon** [comment]
@pedrobaeza I'll forward port all changes from 8.0 to 9.0 once this one is merged.

**Comment by pedrobaeza** [comment]
OK, thanks.

**Comment by laetitia-gangloff** [comment]
:+1:

**Pull request merged**
