### PR TITLE
[18.0][MIG] product_manufacturer: Migration to 18.0

### PR DESCRIPTION
**Pull request by chrisb-c01**
Standard migration based on #1462

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Hi @chrisb-c01! Thanks for the PR. Can you keep the 'Migration to 17.0' commit as is and add another commit for the migration to 18.0, even if it is just the version number bump?

**Comment by chrisb-c01** [comment]
@StefanRijnhart the 17.0 migration was not merged yet before creating my PR. I have now based it on the merged version in the 17.0 branch.

**Review by StefanRijnhart — APPROVED** [review]

**Review by luc-adhoc — APPROVED** [review]
functional review

**Pull request merged**
