### PR TITLE
[13.0][IMP] product_pricelist_assortment: add index on assortment_item_id

### PR DESCRIPTION
**Pull request by acsonefho**
- Improvement: add the index;
- pre-commit: fix the `description.rst` file name and generate the `readme.rst `(separated commit).

### CODE REVIEW

**Review by Cedric-Pigeon — COMMENTED** [review]
@acsonefho Can you have a look at pre-commit please?

**Comment by rousseldenis** [comment]
@acsonefho Could you rebase ?

**Comment by acsonefho** [comment]
> @acsonefho Could you rebase ?

@rousseldenis done :)

**Review by rousseldenis — APPROVED** [review]

**Review by baimont — APPROVED** [review]

**Comment by acsonefho** [comment]
@OCA/product-maintainers Can I have some reviews here please? :)

**Pull request merged**
