### PR TITLE
[13.0][FIX]product_attribute_value_menu: Add depends on compute

### PR DESCRIPTION
**Pull request by GuillemCForgeFlow**
Add depends on compute.
cc @ForgeFlow

### CODE REVIEW

**Review by DavidJForgeFlow — APPROVED** [review]
Functional Review :+1: LGTM

**Review by JordiMForgeFlow — APPROVED** [review]

**Comment by JordiMForgeFlow** [comment]
@GuillemCForgeFlow please FW if needed :)

**Pull request merged**
