### PR TITLE
[14.0][IMP] Use parent categories to determine the prefix if the category has no …

### PR DESCRIPTION
**Pull request by khaeusler**
…settings for the prefix.

Apply the changes from [v12](https://github.com/OCA/product-attribute/pull/737) to v14.

### CODE REVIEW

**Comment by khaeusler** [comment]
I don't understand what the exact problem is here.
https://codecov.io/gh/OCA/product-attribute/pull/779/tree

Could someone explain to me why the file product_pricelist_direct_print/wizards/product_pricelist_print.py is included in the coverage calculation?
The file respectively the addon has not been changed.

**Comment by marylla** [comment]
I guess, you should have "pinged" someone for help. 
Maybe @pedrobaeza knows how to help here?

**Comment by pedrobaeza** [comment]
Just ignore such coverage glitch.

**Review by yweng8111 — APPROVED** [review]

**Review by chandni299 — APPROVED** [review]

**Review by marylla — APPROVED** [review]
I made a functional review. LGTM :+1: 

Before activation of new setting:

- Go to Inventory > Configuration > Product Categories
- Set a prefix for categorie "All / Saleable" like "Prod-"
- Create a new product with this category --> the default code was "Prod-0001"
- Create a new product with the child category "All / Saleable / Office Furniture" --> the default code was "PR/00001" (standard sequence)

And then:

- Go to Settings > General Settings
- Activate "Use parent categories to determine the prefix"
- Create a new product with the child category "All / Saleable / Office Furniture" --> the default code was "Prod-0002".

**Comment by khaeusler** [comment]
@rousseldenis Could you merge this PR as well, thank you

**Comment by khaeusler** [comment]
@pedrobaeza Could you merge this PR? Thank you

**Pull request merged**
