### PR TITLE
[17.0][MIG] product_assortment

### PR DESCRIPTION
**Pull request by Deriman-Alonso**
Standart migration

### CODE REVIEW

**Comment by christian-ramos-tecnativa** [comment]
@Deriman-Alonso Could you squash your last 2 commits together?

**Comment by Deriman-Alonso** [comment]
@Christian-RB Done.

**Review by christian-ramos-tecnativa — APPROVED** [review]

**Review by JasminSForgeFlow — APPROVED** [review]
LGTM!

**Comment by pedrobaeza** [comment]
Is there already #1540. Is there any problem with it?

**Comment by pedrobaeza** [comment]
If this one is finally used, please include #1682

**Comment by Deriman-Alonso** [comment]
> Is there already #1540. Is there any problem with it?

Absolutely missed that, as it was made earlier than this one, Im gonna proceed to close it. Ty

**Comment by pedrobaeza** [comment]
Well, let's see if it's correct first, and if not, if the author answers the requests...

**Comment by Deriman-Alonso** [comment]
> Well, let's see if it's correct first, and if not, if the author answers the requests...

Sure thing, Ill be on the lookout for reopening it again if necessary.

**Comment by dalonsod** [comment]
@Deriman-Alonso previous proposed PR #1540 seems to be dead. Could you reopen this and resume your contribution? Thanks!!

**Pull request closed without merging**
