### PR TITLE
[16.0] [MIG] product_variant_attribute_name_manager

### PR DESCRIPTION
**Pull request by Nikul-OSI**

### CODE REVIEW

**Comment by Nikul-OSI** [comment]
@dreispt @OriolVForgeFlow @AaronHForgeFlow Can you please take a look?

**Review by dreispt — APPROVED** [review]

**Comment by JordiMForgeFlow** [comment]
Hi @dreispt 

This PR was missing commits, that is why I opened https://github.com/OCA/product-attribute/pull/1463.

I will try to FW what was missing

**Comment by dreispt** [comment]
@JordiMForgeFlow Sorry about that. It was not clear to me this was superseded. 
I suggest explicitly adding a message mentioned that it is "Superseded by".
There is a change that rebasing your PR can get you only the missing commits.

**Pull request merged**
