### PR TITLE
[14.0][MIG] product_code_unique

### PR DESCRIPTION
**Pull request by watthanun**
standard migration

### CODE REVIEW

**Review by tonygalmiche — APPROVED** [review]
LGTM : Functional review only with runbot

image

**Comment by watthanun** [comment]
Thank you.

**Review by emagdalenaC2i — APPROVED** [review]
LGTM
Not blocking but I believe that a standard migration to change just the release number is not enough to add yourselt to the contributors file

**Review by flotho — APPROVED** [review]
LGTM 
Code review

**Review by newtratip — APPROVED** [review]
:+1: Functional Test
Selection_527

**Pull request merged**
