### PR TITLE
[17.0][MIG] product_secondary_unit: Migration to 17.0

### PR DESCRIPTION
**Pull request by achulii**

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@jjscarafia do you plan to continue this PR?

**Comment by alexey-pelykh** [comment]
https://github.com/OCA/product-attribute/commit/e18f69c3dfaf620f18d5548ad9d10cac0f553bc3#diff-fac4c6890301d4de5c3f4266837803d5240c84a3d8b6c735bbc6a64c39d2f94e this file was lost during  the migration probably due to the filtering by folder.

**Comment by alexey-pelykh** [comment]
I'm continuing in #1560 with inclusion of #1556

**Comment by rousseldenis** [comment]
Closing this in favor of #1560

**Pull request closed without merging**
