### PR TITLE
product_pricelist_fixed_price : allow to write only one id

### PR DESCRIPTION
**Pull request by laetitia-gangloff**
Write method can have one or many  ids.
I add a check on the write to always convert ids in a list.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:

**Comment by gurneyalex** [comment]
Hi @laetitia-gangloff I believe you work for Acsone, and therefore have an Enterprise CLA signed (@lmignon can you confirm?). I'll update the OCA database with this information once confirmed. 

Could you take the opportunity of this PR to clean the Flake8 and Pylint warnings for the `product_pricelist_fixed_price` module? While not making the build green this would definitely improve the situation of the branch.

**Comment by lmignon** [comment]
@gurneyalex I confirm that @laetitia-gangloff  is my colleague and part of Acsone.

**Comment by laetitia-gangloff** [comment]
@gurneyalex  I will check flaky8 and pylint.

**Comment by gurneyalex** [comment]
@lmignon @laetitia-gangloff OCA database updated. Next push on the branch / next PR should not be flagged by the clabot. Thanks for you time and contributions :smile_cat:

**Comment by pedrobaeza** [comment]
I merge.

**Comment by laetitia-gangloff** [comment]
Thank you !

**Pull request merged**
