### PR TITLE
[12.0][MIG] product manufacturer

### PR DESCRIPTION
**Pull request by Menestrels**
Migration of product_manufacturer from 11.0 to 12.0.

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
> Lois Rilo (no github login found)

@pedrobaeza @sbidoul it's not a big deal, but why the bot is saying that I don't have CLA signed? In all my own PRs I haven't had any problem so my CLA must be in place.

**Comment by pedrobaeza** [comment]
Have you changed the mail in the commits through this time (maybe from personal to professional one)?

**Comment by LoisRForgeFlow** [comment]
No, I didn't this github account was created with my professional mail and never changed.

**Comment by pedrobaeza** [comment]
Clone this branch and see through `git log` what is the defined email for being sure.

**Comment by LoisRForgeFlow** [comment]
Everything seems good:

image

**Comment by pedrobaeza** [comment]
Then the only hypothesis is OCA bot glitch :stuck_out_tongue:

**Comment by LoisRForgeFlow** [comment]
seems so, we have a :bug:

**Review by mlaitinen — APPROVED** [review]
:+1:

**Review by hegenator — APPROVED** [review]
LGTM

**Pull request merged**
