### PR TITLE
[15.0][MIG] product_pricelist_by_contact: Migration to 15.0

### PR DESCRIPTION
**Pull request by cesar-tecnativa**
@Tecnativa TT36497

### CODE REVIEW

**Comment by cesar-tecnativa** [comment]
@pedrobaeza please review

**Review by pedrobaeza — APPROVED** [review]
Code review + tested on runboat

**Comment by cesar-tecnativa** [comment]
@CarlosRoca13 please review

**Review by CarlosRoca13 — APPROVED** [review]

**Pull request merged**
