### PR TITLE
[17.0][MIG] product_supplierinfo_for_customer: Migration to 17.0

### PR DESCRIPTION
**Pull request by Vang-NguyenPhu**

### CODE REVIEW

**Review by xmglord — APPROVED** [review]
LGTM :+1:

**Review by desdelinux — APPROVED** [review]

**Comment by desdelinux** [comment]
Hi @simahawk this is ready :)

**Review by cuongnmtm — APPROVED** [review]
LGTM

**Comment by desdelinux** [comment]
Hi  @pedrobaeza @simahawk this is ready, please

**Review by pedrobaeza — DISMISSED** [review]
Please remove the .deb file.

**Comment by desdelinux** [comment]
@Vang-NguyenPhu Please, you can check the suggestion of @pedrobaeza

**Comment by Vang-NguyenPhu** [comment]
> @Vang-NguyenPhu Please, you can check the suggestion of @pedrobaeza

Yes sir, but I just found a defect in this module. The price is not applied when we select the variant from pop-up "Configure your product". I will try to fix it soon.

**Comment by desdelinux** [comment]
> > @Vang-NguyenPhu Please, you can check the suggestion of @pedrobaeza
> 
> Yes sir, but I just found a defect in this module. The price is not applied when we select the variant from pop-up "Configure your product". I will try to fix it soon.

Friendly Reminder @Vang-NguyenPhu

**Comment by Vang-NguyenPhu** [comment]
> > > @Vang-NguyenPhu Please, you can check the suggestion of @pedrobaeza
> > 
> > 
> > Yes sir, but I just found a defect in this module. The price is not applied when we select the variant from pop-up "Configure your product". I will try to fix it soon.
> 
> Friendly Reminder @Vang-NguyenPhu

All Done :)

**Review by cuongnmtm — APPROVED** [review]
LGTM (code review)

**Comment by pedrobaeza** [comment]
Merging as no more blockers, but not reviewed by my part:

/ocabot merge nobump

**Pull request merged**
