### PR TITLE
[13.0][CHG] product_pricelist_assortment: improve computation performance

### PR DESCRIPTION
**Pull request by Cedric-Pigeon**
Before this PR all items were always deleted and recreated even if no changes were operated.
Now database updates are more accurate and only create/update/delete what has to be.

### CODE REVIEW

**Comment by Cedric-Pigeon** [comment]
include https://github.com/OCA/product-attribute/pull/680

**Comment by Cedric-Pigeon** [comment]
@rousseldenis @acsonefho Review welcome ;-)

**Review by acsonefho — APPROVED** [review]
LGTM (code only)

**Review by ferranmateu — APPROVED** [review]
Functional review OK!

**Pull request merged**
