### PR TITLE
[MIG] product_code_mandatory: Migration to 16.0

### PR DESCRIPTION
**Pull request by matiasperalta1**

### CODE REVIEW

**Review by rvalyi — DISMISSED** [review]
LGTM (product default_code works the same in Odoo v15 and Odoo v16)

**Review by rvalyi — CHANGES_REQUESTED** [review]
Sorry I approved too fast before. So actually after testing on Runbot, I see two issues:

1. in the menu, when you edit the product.template (like Sales>Products>Products), the default_code field is not mandatory and you can save without a code. Then some default value is assigned. But I think this defeats the purpose of the module (if you edit a product.product using the Product Variant menu then the field is required). This bug is also present on v15.
2. Even if you use the Product Variant menu (Sales>Products>Product Variants) then some default value is present for the default_code field, which is not the expected and not the same behavior as in v15 (empty required field).

**Comment by andreampiovesana** [comment]
this app is important, can you merge and then fix problems like in version 15?

**Review by andreampiovesana — APPROVED** [review]
LGTM

**Pull request closed without merging**
