### PR TITLE
Remove duplicate bug tracker

### PR DESCRIPTION
**Pull request by sebastienbeau**

### CODE REVIEW

**Comment by emagdalenaC2i** [comment]
@sebastienbeau seems there is an issue with the bot.
I did this before in #583

**Comment by sebastienbeau** [comment]
In fact the issue is not in the bot but in the readme/USAGE.rst file.
The bugtracker is define here and the bot will add it again automatically.
I force the merge to solve the issue, the bot will update and fix the readme

**Comment by sebastienbeau** [comment]
The bot have remove the duplicate section in the readme https://github.com/OCA/product-attribute/commit/087b694d091acd334629ee86f2fb8b20cce95fc4
let's wait and it should be green again

**Comment by emagdalenaC2i** [comment]
ok, but there are other issues with travis. I tried to fix some in #587 and #586 
Please, could you take a look?

[Edit] Although these are not important issues like this one:
************* Module product_sequence.tests.test_product_sequence
product_sequence/tests/test_product_sequence.py:50: [E8103(sql-injection), TestProductSequence.test_pre_init_hook] SQL injection risk. Use parameters if you can. - More info https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#no-sql-injection

**Pull request merged**
