### PR TITLE
[17.0][MIG] uom category active

### PR DESCRIPTION
**Pull request by nachoserra-domatix**
Migration to 17.0 for module uom_category_active

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi @nachoserra-domatix . thanks for porting this module. Could you squash your last migration commits ?

**Comment by nachoserra-domatix** [comment]
> Hi @nachoserra-domatix . thanks for porting this module. Could you squash your last migration commits ?

Thanks, Done!

**Review by legalsylvain — APPROVED** [review]
nitpicking. commit message is not optimal. 
image

otherwise, LGTM. Thanks !

**Comment by nachoserra-domatix** [comment]
> nitpicking. commit message is not optimal. image
> 
> otherwise, LGTM. Thanks !

Sorry! I think its solved now?

**Pull request merged**
