### PR TITLE
[16.0] [MIG] product_state_history: Migration to 16.0

### PR DESCRIPTION
**Pull request by michaelslade54**
Standard migration.

### CODE REVIEW

**Comment by rousseldenis** [comment]
@michaelslade54 Could you fix this as it seems you've included another module ?

**Comment by michaelslade54** [comment]
Apologies.

It appears this commit 81a5eb6c7651c7a9ab09c43a4f064cda75ca2876 in the commit history introduced some changes to the extra module, hence it appearing here.

@rousseldenis I'm unsure of the most appropriate way to rectify this, is the preferred method to drop the commit and include any module specific changes in the migration?

Any info appreciated. Thanks.

**Comment by rousseldenis** [comment]
@michaelslade54 The best solution is to rebase interactively and don't take modifications that are outside this module.

**Review by rousseldenis — APPROVED** [review]

**Review by FrancoMaxime — APPROVED** [review]
LGTM: code review and functionnal testing

**Pull request closed without merging**
