### PR TITLE
[16.0][FIX] product_pricelist_simulation: switch tests to TransactionCase

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
SavepointCase is deprecated and it was making CI fail.

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
I would say this is just a warning, so maybe the failing is in other place, but good to change this.

**Comment by LoisRForgeFlow** [comment]
@pedrobaeza Yes, I was just realizing of that, the warning was so big and ugly that I got fooled :laughing: 

In any case, good to fix.

**Comment by pedrobaeza** [comment]
Let's merge it then:

/ocabot merge path

**Comment by LoisRForgeFlow** [comment]
@pedrobaeza you misspelled the command, could you try again?

**Pull request merged**
