### PR TITLE
[13.0][IMP] Use parent categories to determine the prefix if the category has no …

### PR DESCRIPTION
**Pull request by khaeusler**
…settings for the prefix.

Apply the changes from [v12](https://github.com/OCA/product-attribute/pull/737) to v13.

### CODE REVIEW

**Review by marylla — APPROVED** [review]
I made a functional review. LGTM :+1: 

Before activation of new setting:

- Go to Inventory > Configuration > Product Categories
- Set a prefix for categorie "All / Saleable" like "Prod-"
- Create a new product with this category --> the default code was "Prod-0001"
- Create a new product with the child category "All / Saleable / Office Furniture" --> the default code was "PR/0005" (standard sequence)

And then:

- Go to Settings > General Settings
- Activate "Use parent categories to determine the prefix"
- Create a new product with the child category "All / Saleable / Office Furniture" --> the default code was "Prod-0002".

**Review by yweng8111 — APPROVED** [review]

**Review by chandni299 — APPROVED** [review]
Looks good to me.

**Comment by khaeusler** [comment]
@rousseldenis Could you merge this PR as well, thank you

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
