### PR TITLE
[FIX] product_print_category print report name

### PR DESCRIPTION
**Pull request by nayatec**
@legalsylvain Hello, the print_report_name must be a python valid expression, can you check this fix ?

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Thanks ! 
fast tracking this trivial patch.

/ocabot merge patch

**Comment by legalsylvain** [comment]
Could you rebase @nayatec ?

**Comment by nayatec** [comment]
@legalsylvain done, and fixed a trivial mistake i made...

**Comment by legalsylvain** [comment]
/ocabot merge patch

thanks !

**Comment by nayatec** [comment]
@legalsylvain should be ok now, there was a backslash unescaped in the fr.po file, the click-odoo-makepot runs ok against it now in my local dev

**Pull request merged**
