### PR TITLE
[16.0][MIG] product_secondary_unit

### PR DESCRIPTION
**Pull request by otmanelagy**

### CODE REVIEW

**Comment by otmanelagy** [comment]
cc @emagdalenaC2i @rousseldenis

**Comment by emagdalenaC2i** [comment]
@otmanelagy Please, squash your commits

**Comment by rousseldenis** [comment]
@otmanelagy Could you attend @emagdalenaC2i comments ?

You should squash those ones into one:

image

**Comment by HugOdoo** [comment]
@otmanelagy 

Hello,

Any news on the migration of this module?

Let me know,

Thanks
Hugo

**Comment by remihb** [comment]
No news here ?

Just to draw it to your attention that this mig is based on a former version of the module in 15.0, as it doesn't include the product_product part ([https://github.com/OCA/product-attribute/tree/15.0/product_secondary_unit/models](url))

**Comment by pedrobaeza** [comment]
Superseded by #1325

**Pull request closed without merging**
