### PR TITLE
[MIG] sale_product_template_tags: Migration to 16.0

### PR DESCRIPTION
**Pull request by mohammadazeem786**
Dropping the dependency on product_template_tag because product tags are now in core Odoo 16 (but without a menu to manage them, which is what this module provides).

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]
Thanks! Code reviewed + tested.

**Review by rven — APPROVED** [review]

**Review by liebana — APPROVED** [review]

**Comment by liebana** [comment]
Functional tested, LGTM

**Pull request merged**
