### PR TITLE
[14.0][MIG] product_code_mandatory

### PR DESCRIPTION
**Pull request by watthanun**

### CODE REVIEW

**Comment by newtratip** [comment]
@watthanun Please check CI. may be pre-commit is not pass.

**Review by tonygalmiche — APPROVED** [review]
LGTM : Functional review only with runbot

image

**Comment by newtratip** [comment]
@watthanun Please remove `product_assortment` and push again.

**Comment by rousseldenis** [comment]
@watthanun I think there are problems with your commits. The last one include all files but that one should reflect migration changes. @newtratip @kittiu Could you help ?

**Comment by newtratip** [comment]
@rousseldenis, I have squash the commits and change license url from http to https.

If I add contributor and generated readme by **oca-gen-addon-readme**, Should I push on commit `black, isort, prettier` or `Migration to 14.0` ?

**Comment by rousseldenis** [comment]
> @rousseldenis, I have squash the commits and change license url from http to https.
> 
> If I add contributor and generated readme by **oca-gen-addon-readme**, Should I push on commit `black, isort, prettier` or `Migration to 14.0` ?

On migration one

**Review by newtratip — APPROVED** [review]
:+1: Functional Test

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
