### PR TITLE
[15.0][MIG]product_custom_info:Migration to V15 

### PR DESCRIPTION
**Pull request by bizzappdev**

### CODE REVIEW

**Comment by bizzappdev** [comment]
Ready for review

**Comment by bizzappdev** [comment]
Ready for Review

**Comment by bosd** [comment]
depends upon: https://github.com/OCA/server-tools/pull/2360

**Comment by bosd** [comment]
Can the tests be re-triggered?
Dependencies are migrated now.

**Comment by pedrobaeza** [comment]
There's a previous migration in #1091, so closing.

**Pull request closed without merging**
