### PR TITLE
Updated from template - Switch to Github actions

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by rousseldenis** [comment]
Development statuses dependencies issues:

- [ ] product_video_link: @sebastienbeau Do you mind retrograding this one before stabilizing the base module ?
- [ ] product_total_weight_from_packaging: @simahawk @grindtildeath Do you mind retrograding this one before stabilizing the calculator module ?

**Comment by simahawk** [comment]
`product_total_weight_from_packaging` is a dependency for other modules, we'll we likely move this issue somewhere else :sweat_smile: `stock_packaging_calculator` can be moved to beta IMO.

**Comment by pedrobaeza** [comment]
The other option is to disable status check for this repo and version.

**Comment by rousseldenis** [comment]
> The other option is to disable status check for this repo and version.

I'd prefer not doing exceptions as there are not so much modules concerned

**Pull request merged**
