### PR TITLE
[ADD][16.0] product_code_mixin

### PR DESCRIPTION
**Pull request by bealdav**
This module define a mixin to have a product code available in any model which  inherit of this mixin.

This method can be useful for exported data when you don't want deal with [ ]

Typically you may inherit it with:

- sale.order.line
- purchase.order.line
- account.move.line
- stock.move

### CODE REVIEW

**Review by hparfr — APPROVED** [review]

**Review by dora-jurcevic — APPROVED** [review]
Looks good to me

**Review by leemannd — APPROVED** [review]

**Comment by bealdav** [comment]
cc @dreispt I have rebased the PR.

Could you try a new merge ?

Thanks a lot

**Pull request merged**
