### PR TITLE
[10][MIG] product_customer_code

### PR DESCRIPTION
**Pull request by llacroix**

### CODE REVIEW

**Review by rousseldenis — CHANGES_REQUESTED** [review]
Thanks for your contribution.

Could you please follow migration guide, especially the 'git format-patch' command part ?

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

**Comment by rousseldenis** [comment]
@pedrobaeza Could you please remind me the attention points when migrating Odoo former module ?

**Comment by pedrobaeza** [comment]
Do you mean if the module was initially done by Odoo SA?

**Comment by rousseldenis** [comment]
> Do you mean if the module was initially done by Odoo SA?

Yes

**Comment by pedrobaeza** [comment]
Check this section in the contribution guidelines for that:

https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#10backporting-odoo-modules

**Comment by rousseldenis** [comment]
> Check this section in the contribution guidelines for that:
> 
> https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#10backporting-odoo-modules

Great thanks.

@llacroix Could you modify this accordingly ?

**Pull request closed without merging**
