### PR TITLE
[14.0][MIG] product_logistics_uom

### PR DESCRIPTION
**Pull request by hparfr**
Code is prettier since m³ is not longer hardcoded in odoo.

### CODE REVIEW

**Comment by hparfr** [comment]
Ping @clementmbr

**Review by rvalyi — APPROVED** [review]

**Review by PierrickBrun — APPROVED** [review]
LGTM

**Comment by hparfr** [comment]
Hi @rousseldenis , can you please merge this one ?  Thanks

**Comment by Kev-Roche** [comment]
Hi @PierrickBrun , @rousseldenis, @rvalyi 
Can you merge this PR please ? I m working on product_packaging_dimension and it will be cleaner if it depends of this module. 
Thank you

**Comment by rousseldenis** [comment]
@hparfr Could you squash your commits ?

**Comment by hparfr** [comment]
@rousseldenis done.

I get this warning from github: 

> 1 workflow awaiting approval
First-time contributors need a maintainer to approve running workflows. Learn more. 1 pending and 1 successful checks

**Comment by rousseldenis** [comment]
> @rousseldenis done.
> 
> I get this warning from github:
> 
> > 1 workflow awaiting approval
> > First-time contributors need a maintainer to approve running workflows. Learn more. 1 pending and 1 successful checks

Wasn't aware of that. Clicked

**Pull request merged**
