### PR TITLE
[16.0][MIG] product_attribute_archive

### PR DESCRIPTION
**Pull request by Rferri44-S73**
Standard migration to 16.0

### CODE REVIEW

**Comment by Rferri44-S73** [comment]
@rousseldenis could you review this pr?

**Review by FrancoMaxime — APPROVED** [review]
LGTM code and functional review

**Review by ecino — APPROVED** [review]

**Comment by ecino** [comment]
I also tested and reviewed the code, all good for me.

**Review by Jortolsa-S73 — APPROVED** [review]

**Comment by ioans73** [comment]
@rousseldenis can we merge it?

**Comment by ioans73** [comment]
@OCA/product-maintainers can we merge it?

**Comment by Rferri44-S73** [comment]
@pedrobaeza ping

**Comment by pedrobaeza** [comment]
Merging due to existing reviews

/ocabot merge nobump

**Pull request merged**
