### PR TITLE
[11.0][ADD] product_restricted_type

### PR DESCRIPTION
**Pull request by AdriaGForgeFlow**
Add module product_restricted_type to v11

This module adds 'restricted_product_type' to product_category model.
With this optional selection field 'restricted_product_type' should
have the same values as in the product.template, 'type' field.

A constrain is also established in the product so that when the 'type'
defined in the product does not match with the 'restricted_product_type'
defined in the product category it raises a Validation Error.

Also, in the product category one would not be able to change the field
'restricted_product_type' if the category has been assigned at least to
one product that already has this category, but has a different 'type' value.

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@ageficent Test are failing in travis, can you have a look?

**Review by JordiBForgeFlow — APPROVED** [review]
The PR seems to have non-related commits. Perhaps you should rebase?

**Comment by JordiBForgeFlow** [comment]
@lreficent Can you review again?

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
