### PR TITLE
[FIX] product_cost_security: apply to prices in supplier info too

### PR DESCRIPTION
**Pull request by yajo**
Sales users were able to see costs in the purchase tab of products, if seller info was added there.

https://www.loom.com/share/7219aacbc4804e2dbd2f3a3aee174af1?sid=bace01fe-6f0d-42bf-8b53-e6945c527e15

MT-6508

### CODE REVIEW

**Review by fcvalgar — APPROVED** [review]
Functional review,

LGTM thank you @yajo

**Review by Gelojr — APPROVED** [review]
@yajo nice job LGTM
image

**Review by Shide — APPROVED** [review]
Code LGTM

**Review by EmilioPascual — APPROVED** [review]

**Review by rafaelbn — APPROVED** [review]
/ocabot merge minor

**Comment by chienandalu** [comment]
This is having issues (at least) with `purchase_stock`:

- Just try to access any reordering rule (`stock.warehouse.orderpoint`)
- Access error over `product.supplier_info.price` raises:

```
The requested operation can not be completed due to security restrictions.

Document type: Supplier Pricelist (product.supplierinfo)
Operation: read
User: 2
Fields:
- price (allowed for groups 'Product costs / Read')
```

**Comment by rafaelbn** [comment]
Thank you @chienandalu , we are apply fix now! PRs will be soon! @yajo is working on it

**Comment by rafaelbn** [comment]
@chienandalu hello! we are deeply reviewing the issue you report but the BUG is not in this PR or this module as you can check testing in runbot. I have recorded my functional review 😄 so you can check it!

https://www.loom.com/share/95596119a7f84310937824d195bd0d31?sid=f189927d-0803-45ad-ba41-7f34633b0449

We are having same issue but the modules we point now and we are investigating are [`sale_product_security_price`](https://github.com/Tecnativa/extra-addons/tree/16.0/sale_product_security_price) or [`sale_tier_validation_security_price`](https://github.com/Tecnativa/extra-addons/tree/16.0/sale_tier_validation_security_price)

Could you please check the video a give your opinion about it? 😄 Thank you! ❤️ 


I cannot reproduce this:

> This is having issues (at least) with purchase_stock:
> 
>     Just try to access any reordering rule (stock.warehouse.orderpoint)
>     Access error over product.supplier_info.price raises:
> 
> The requested operation can not be completed due to security restrictions.
> 
> Document type: Supplier Pricelist (product.supplierinfo)
> Operation: read
> User: 2
> Fields:
> - price (allowed for groups 'Product costs / Read')
>

**Comment by yajo** [comment]
Please review https://github.com/OCA/product-attribute/pull/1663

**Pull request merged**
