### PR TITLE
[14.0][IMP][product_tier_validation] actions for many products to reject and validate

### PR DESCRIPTION
**Pull request by Kev-Roche**
add action for multiple product template validation / reject

### CODE REVIEW

**Review by sebastienbeau — APPROVED** [review]
LGTM (code review)

**Review by bosd — APPROVED** [review]

**Comment by legalsylvain** [comment]
@Kev-Roche. FYI, translation should be handled via OCA weblate.

/ocabot merge patch

**Comment by Kev-Roche** [comment]
> @Kev-Roche. FYI, translation should be handled via OCA weblate.
> 
> /ocabot merge patch

@legalsylvain ho ok, also if it's new terms to translate ? If I understand correctly, we have no way to have together a new function / term to translate and its translation at the same time ?

**Comment by legalsylvain** [comment]
/ocabot merge patch


@legalsylvain ho ok, also if it's new terms to translate ? If I understand correctly, we have no way to have together a new function / term to translate and its translation at the same time ?

No that's a current annoying limitation of the OCA translation system.

Note : could you port the changes upstream ?

**Pull request merged**
