### PR TITLE
[WIP] Refactor product image

### PR DESCRIPTION
**Pull request by sebastienbeau**
Hi, I refactor and simplify the module product image based on the new field ImageField
This merge depend of this one https://code.launchpad.net/~akretion-team/server-env-tools/server-env-tools

I will try to propose migration script in order to migrate the existing images

OLD MP : https://code.launchpad.net/~akretion-team/openerp-product-attributes/openerp-product-attributes-product-image/+merge/222397

### CODE REVIEW

**Comment by bwrsandman** [comment]
Is this meant to be an 8.0 version?

**Comment by sebastienbeau** [comment]
Hi, for now it will be on v7 (because I need it) but when it will be ready I will propose a merge also for 8 version.
Hum I see that my merge is for the master so I did it wrong, did it's possible to change it? or I have to propose a new merge?

**Comment by bwrsandman** [comment]
As far as I know, it needs to be closed and another needs to be opened with a different OCA branch

**Comment by sebastienbeau** [comment]
Ok I will do it

2014-07-14 18:08 GMT+02:00 Sandy notifications@github.com:

**Comment by OSguard** [comment]
where is the module gone? Is there a other pull request already created?

**Pull request closed without merging**
