### PR TITLE
[16.0] [MIG] product_category_code

### PR DESCRIPTION
**Pull request by JulyChacko1601**

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Hi @JulyChacko1601. 
First thanks for your contribution.

Could you rename the commit message ? "[IMP] product_category_code: pre-commit stuff" by something like [MIG] product_category_code : Migration to 16.0".

See OCA convention. https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

Otherwise, LGTM. Code review / no test.

**Comment by JulyChacko1601** [comment]
@legalsylvain Thanks for your feedback, I changed the commit message.

**Review by emagdalenaC2i — APPROVED** [review]
LGTM

**Review by bodedra — APPROVED** [review]
Functional review 👍

**Review by etobella — APPROVED** [review]
LGTM
/ocabot merge nobump

**Pull request merged**
