### PR TITLE
[14.0][MIG] product_manufacturer

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Superseed https://github.com/OCA/product-attribute/pull/705 due to inactivity

@bluemix @bosd @bodedra @rousseldenis @LoisRForgeFlow

### CODE REVIEW

**Comment by bosd** [comment]
Hope this one can be merged soon.
Newbie here, Why is codecov failling?

**Review by bosd — APPROVED** [review]
Functional Review on Runbot, LGTM

**Review by petrus-v — APPROVED** [review]
Thanks, reading code source, LGTM

**Comment by petrus-v** [comment]
> Thanks, reading code source, LGTM

And special thanks for tests additions :clap:

**Pull request merged**
