### PR TITLE
[ADD][12.0] product_product_template_navigation

### PR DESCRIPTION
**Pull request by Tardo**
This module adds a button in the product form to view the product template.

view_Template

cc @tecnativa TT21113

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Hi @Tardo. thanks for this module. LGTM. Code review / No test.
Not blocking point : could you add your gif in the description of the module ? 

thanks.

**Review by chienandalu — APPROVED** [review]
Thanks ;)

**Review by pedrobaeza — APPROVED** [review]
I have added the image and me as contributor due to the original design :wink:

**Pull request merged**
