### PR TITLE
[18.0][MIG] product_main_supplierinfo: Migration to 18.0

### PR DESCRIPTION
**Pull request by xaviedoanhduy**
base on: https://github.com/OCA/product-attribute/pull/1660

### CODE REVIEW

**Review by sebalix — APPROVED** [review]

**Review by ajaniszewska-dev — APPROVED** [review]
LG

**Review by bealdav — APPROVED** [review]
LGTM

**Comment by sebalix** [comment]
@xaviedoanhduy can you cherry-pick our patch on v17 https://github.com/OCA/product-attribute/pull/1812 ? :pray:

**Comment by xaviedoanhduy** [comment]
> @xaviedoanhduy can you cherry-pick our patch on v17 #1812 ? 🙏

hi @sebalix, done

**Pull request merged**
