### PR TITLE
[16.0][MIG] - product_stock_state

### PR DESCRIPTION
**Pull request by sbejaoui**
based on #1222

### CODE REVIEW

**Review by lmignon — APPROVED** [review]
LGTM (Code review)

**Review by FrancoMaxime — APPROVED** [review]
LGTM

**Review by hparfr — APPROVED** [review]
Ready for the merge

**Comment by andreampiovesana** [comment]
merge?

**Review by qgroulard — APPROVED** [review]

**Review by cyrilmanuel — APPROVED** [review]

**Comment by lmignon** [comment]
@OCA/product-maintainers Someone to merge this one ?

**Pull request merged**
