### PR TITLE
[18.0][MIG] product_dimension: Migration to 18.0

### PR DESCRIPTION
**Pull request by StefanRijnhart**
* Refactor a test class to use setUpClass.
* Remove colspan="2" from regular second level form group.
* Prevent new UoMs from being created by accident.

### CODE REVIEW

**Review by CasVissers-360ERP — APPROVED** [review]
Functional review

**Review by luc-adhoc — APPROVED** [review]
Functional test approved!

**Review by rvalyi — APPROVED** [review]

**Pull request merged**
