### PR TITLE
[15.0][MIG] product_state: Migration to 15.0

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

@BT-rfresco Thanks for your contribution.

Next time, could you follow migration guide, especially the Full Process part ? https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#technical-method-to-migrate-a-module-from-140-to-150-branch

**Review by BT-aestebanez — APPROVED** [review]

**Comment by BT-aestebanez** [comment]
@rousseldenis could you merge this, please?

**Pull request merged**
