### PR TITLE
[14.0][IMP] product_profile: refactor to improve inheritance

### PR DESCRIPTION
**Pull request by sebastienbeau**
Give the possibility to call directly with a domain the method _customize_view
with a domain so you can reuse this method in custom module to add profile filter.

In my case I want to add a filter on mrp.bom so just adding a related
field + a call to _customize_view allow to add only profile related to
manufacturing

Also add a separator to avoid mixing profile filter with existing filter

### CODE REVIEW

**Comment by sebastienbeau** [comment]
@kevinkhao @bealdav

**Review by bealdav — APPROVED** [review]

**Review by simahawk — APPROVED** [review]
LG. @sebastienbeau pls include module name in commit msg and leave long desc for the commit description :wink:

**Comment by rousseldenis** [comment]
@sebastienbeau

**Pull request merged**
