### PR TITLE
[16.0][MIG] product_supplierinfo_revision: Migration to version 16.0

### PR DESCRIPTION
**Pull request by stefan-tecnativa**
cc @Tecnativa TT44341

@Yadier-Tecnativa @pilarvargas-tecnativa please review!

### CODE REVIEW

**Review by pilarvargas-tecnativa — APPROVED** [review]
LGTM :)

**Review by Yadier-Tecnativa — APPROVED** [review]
Good, also tested on runboat.

**Comment by stefan-tecnativa** [comment]
Is this merging? @pedrobaeza

**Pull request merged**
