### PR TITLE
[17.0][MIG] product_pricelist_revision

### PR DESCRIPTION
**Pull request by MarioLM-23**
Standar migration with changes in view

### CODE REVIEW

**Review by FrancoMaxime — APPROVED** [review]
LGTM: code & functional review

**Review by traitrantrobz — APPROVED** [review]
LGTM 👍, it work correctly.
Btw, please rebase the commit history for clarity.

**Review by gurneyalex — APPROVED** [review]

**Comment by syci** [comment]
Hello, has no one found this error? #1951

**Pull request merged**
