### PR TITLE
[MIG][16.0] product_abc_classification_sale_stock

### PR DESCRIPTION
**Pull request by rousseldenis**
Migration from 10.0 PR : https://github.com/OCA/product-attribute/pull/781

Depends on:

- [ ] #1192

### CODE REVIEW

**Review by lmignon — CHANGES_REQUESTED** [review]
@rousseldenis When clicking on the smartbutton into the profile view to display the product, I've an error
image

**Comment by rousseldenis** [comment]
@lmignon fixed

**Review by lmignon — APPROVED** [review]
Thank you @rousseldenis. LGTM (Code + Functional tests)

**Review by sbejaoui — APPROVED** [review]

**Review by jbaudoux — APPROVED** [review]

**Pull request merged**
