### PR TITLE
[MIG][13.0] product_custom_info

### PR DESCRIPTION
**Pull request by Rad0van**
Fairly standard migration... Had to change the product_tmpl_custom_info_ids in product_product.py to One2Many. Otherwise the custome renderer in base_custom_info wouldn't catch it and end up with JS exception.

A question to authors if I may: how would I be able to display Category in this custom renderer?

### CODE REVIEW

**Comment by Rad0van** [comment]
@Yajo could you maybe have a look? Who else could possibly review this? Thanx.

**Comment by yajo** [comment]
Sorry, I don't use this module anymore.

**Comment by Rad0van** [comment]
@rlizana maybe?

**Comment by Rad0van** [comment]
Or maybe @pedrocasi or @claudiagn ?

**Comment by ska-ibees** [comment]
Any chance to get this merged soon?

**Comment by Rad0van** [comment]
> Any chance to get this merged soon?

Not up to me. I asked everyone I could...

**Comment by ska-ibees** [comment]
@pedrobaeza sorry for the direct ping. I was thinking of migrating this module alongwith base_custom_info to V14. Could you please help to get it merged? Thanks

**Comment by pedrobaeza** [comment]
A pull request must be reviewed:

https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#review

**Comment by Rad0van** [comment]
> A pull request must be reviewed:
> 
> https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#review

@pedrobaeza any idea whom else I should ask about review?

**Comment by pedrobaeza** [comment]
@ska-ibees can make the review for example if he's interested.

**Comment by Rad0van** [comment]
> @ska-ibees can make the review for example if he's interested.

Out of curiosity: how do I find proper people to review PRs? I usually look into history to see who approved PRs and contributed to it. Is there a better way? Should I ask people that are listed as contributors?  How about you?

**Comment by ska-ibees** [comment]
> 
> 
> @ska-ibees can make the review for example if he's interested.

Oh didn't know about the required qualification for the reviewer. I thought peers with certain rights can only review it. 

As I read in the guideline, it says:

At least one of the review above must be from a member of the PSC or having write access on the repository (here one of the OCA Core Maintainers. can do the job. You can notify them on Github using @OCA/core-maintainers)

**Review by ska-ibees — COMMENTED** [review]
It was little confusing as root menu did not show up for admin user. Shouldn't we add base.group_system to the root menu?

` <menuitem
        id="menu_base_custom_info"
        name="Custom Info"
        groups="base_custom_info.group_basic"
        web_icon="base_custom_info,static/description/icon.png"
    />`

**Comment by pedrobaeza** [comment]
> > @ska-ibees can make the review for example if he's interested.
> 
> Out of curiosity: how do I find proper people to review PRs? I usually look into history to see who approved PRs and contributed to it. Is there a better way? Should I ask people that are listed as contributors? How about you?

Old contributors may be a source, but the idea is to equitable: you review some PRs of the same repository/affinity, and ask for reviews on yours. If everyone push PRs, but no one review, you can imagine the result...

> It was little confusing as root menu did not show up for admin user. Shouldn't we add base.group_system to the root menu?

Not bad idea, but that should be for `base_custom_info` instead.

**Comment by ska-ibees** [comment]
> 
> 
> > > @ska-ibees can make the review for example if he's interested.
> > 
> > 
> > Out of curiosity: how do I find proper people to review PRs? I usually look into history to see who approved PRs and contributed to it. Is there a better way? Should I ask people that are listed as contributors? How about you?
> 
> Old contributors may be a source, but the idea is to equitable: you review some PRs of the same repository/affinity, and ask for reviews on yours. If everyone push PRs, but no one review, you can imagine the result...
> 
> > It was little confusing as root menu did not show up for admin user. Shouldn't we add base.group_system to the root menu?
> 
> Not bad idea, but that should be for `base_custom_info` instead.

Sorry, yes it should be there in `base_custom_info`. Will take care of this while migration.

**Review by ska-ibees — APPROVED** [review]
Code LGTM. Also, tested on runbot without any issue.

**Review by pedrobaeza — APPROVED** [review]
OK, let's go with this one, but the rate should be compensated :wink:

**Pull request merged**
