### PR TITLE
[9.0][FIX/MIG] product_manufacturer

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Forward port of https://github.com/OCA/product-attribute/pull/302.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You have to remove it instead of updating it.

**Comment by MiquelRForgeFlow** [comment]
Is it necessary to be removed? I like to see all the old migration folders, like if it was a record history.

**Comment by pedrobaeza** [comment]
This can cause problems migrating from v9 to v10 if you have a v8 migration scripts, as it will be also run.

**Comment by pedrobaeza** [comment]
That's the reason each migration script should be only on the corresponding version.

**Comment by MiquelRForgeFlow** [comment]
Ok.

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza Done

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
