### PR TITLE
[14.0][MIG] product_route_mto: backport from v16

### PR DESCRIPTION
**Pull request by twalter-c2c**
This module depends on `stock_route_mto`, here is the related PR: https://github.com/OCA/stock-logistics-warehouse/pull/2154

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You should respect commit history.

**Comment by twalter-c2c** [comment]
Thank you for this remark, I will take care of it.

**Comment by sebalix** [comment]
@twalter-c2c you can refer to the other PR temporarily to ensure your module is working as expected (tests + runboat) with this guide: https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29

Once the dependency is merged, you could remove this reference from the current PR.

**Review by sebalix — APPROVED** [review]

**Review by ajaniszewska-dev — APPROVED** [review]
LG, test-requirements PR is already merged

**Pull request merged**
