### PR TITLE
8.0 Add module product_categ_image

### PR DESCRIPTION
**Pull request by alexis-via**
See the README for more info.

### CODE REVIEW

**Comment by bguillot** [comment]
:+1:

**Comment by bealdav** [comment]
:+1: 
thanks

**Comment by hparfr** [comment]
👍 

PS : there is already images on "public categories" (from website_sale).

**Review by brother-bernard — APPROVED** [review]
Using in production without problem.

**Review by legalsylvain — COMMENTED** [review]
Hi @alexis-via. 
thanks for this module. LGTM.

Two questions,
- did you consider to include image_small and image_medium (like in product.template) to have the possibility to access to lighter images usefull in some cases. (specially in website context).
- don't you think it could be interesting to have a kanban view for the category, to see more easily which categ have or not an image ?

Not blocking points. Could be added in Roadmap section if it's out of the scope of your PR.

**Comment by rousseldenis** [comment]
@alexis-via Is this still applicable ?

**Comment by rousseldenis** [comment]
Closing this as very old. Please feel free to reopen it if needed

**Comment by legalsylvain** [comment]
@rousseldenis this PR is approved. So should be merged. Don't you think ?

**Comment by rousseldenis** [comment]
> @rousseldenis this PR is approved. So should be merged. Don't you think ?

Ok, let's go so.

**Pull request merged**
