### PR TITLE
[12.0] FIX product_pricelist_supplierinfo: _get_supplierinfo_pricelist_price when date is datetime

### PR DESCRIPTION
**Pull request by eLBati**
date may come from context

### CODE REVIEW

**Comment by eLBati** [comment]
I can't reproduce the travis error locally, running exactly the same commands.

It seems related to `product_weight` module.
@tbaden @florian-dacosta any hint?

**Comment by pedrobaeza** [comment]
Main branch should be gone, so let's try to merge (following the same patch proposed at #820):

/ocabot merge patch

**Comment by pedrobaeza** [comment]
Is this needed as well in v13?

**Comment by eLBati** [comment]
@pedrobaeza thanks.

Module is not available for v13

**Pull request merged**
