### PR TITLE
[13.0][FIX]product_supplierinfo_archive

### PR DESCRIPTION
**Pull request by GuillemCForgeFlow**
Added field on view and changed filters. Now only the **archived** filter will appear.

### CODE REVIEW

**Comment by JordiMForgeFlow** [comment]
The active field is missing in the form view so you can't archive supplier from there. It would be nice to add :)

**Review by AaronHForgeFlow — APPROVED** [review]
Code review LG!

**Comment by GuillemCForgeFlow** [comment]
> The active field is missing in the form view so you can't archive supplier from there. It would be nice to add :)

Done! Thanks for the review :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]

**Pull request merged**
