### PR TITLE
[15.0][MIG] product_net_weight

### PR DESCRIPTION
**Pull request by flachica**

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Thanks for porting this module. :+1:

**Comment by legalsylvain** [comment]
/ocabot migration

@flachica : could you take a look on pre-commit errors ?

**Comment by legalsylvain** [comment]
@sbidoul : ``/ocabot migration`` should work, or did I missed something ?

**Comment by flachica** [comment]
> /ocabot migration
> 
> @flachica : could you take a look on pre-commit errors ?

Sorry @legalsylvain, it is solved yet

**Review by legalsylvain — APPROVED** [review]

**Comment by sbidoul** [comment]
@legalsylvain I think you need to give a module name to the `ocabot migration` command.

**Pull request merged**
