### PR TITLE
[MIG] product_uom: migration to 11.0

### PR DESCRIPTION
**Pull request by hprasetyou**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

**Review by Trivedi-Vacha-SerpentCS — CHANGES_REQUESTED** [review]
In README.rst file every url link should be https

**Comment by pedrobaeza** [comment]
This still doesn't preserve commit history.

**Comment by MiquelRForgeFlow** [comment]
The name of the PR should be similar to "[MIG] product_uom: migration to 11.0"

**Comment by pedrobaeza** [comment]
This still doesn't preserve commit history.

**Comment by hprasetyou** [comment]
> This still doesn't preserve commit history.

hi, what is commit history? is it like list of commit message?

**Comment by pedrobaeza** [comment]
See my first comment: https://github.com/OCA/product-attribute/pull/351#issuecomment-383830027

**Comment by MiquelRForgeFlow** [comment]
Can be closed. Superseeded by https://github.com/OCA/product-attribute/pull/423.

**Pull request closed without merging**
