### PR TITLE
Init copier template

### PR DESCRIPTION
**Pull request by joao-p-marques**
Also, add the `swig` package in Travis, needed when installing `reporting-engine`.

ping @pedrobaeza @Yajo @CarlosRoca13

### CODE REVIEW

**Comment by pedrobaeza** [comment]
As said, please don't do that for all repos, but change OCA/reporting-engine

**Review by yajo — APPROVED** [review]

**Comment by pedrobaeza** [comment]
The `swig` thing should be fixed on OCA/reporting-engine, not here

**Comment by joao-p-marques** [comment]
Changed and ready to merge @pedrobaeza

**Pull request merged**
