### PR TITLE
[IMP] product_variant_attribute_name_manager: Add flag to allow no variant attributes to be displayed

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Add the possibility to display no variant attributes

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by antoniospneto** [comment]
Hi @HviorForgeFlow, could you rebase and fix pre-commit ?

**Comment by HviorForgeFlow** [comment]
@antoniospneto ready!

**Review by felipemotter — APPROVED** [review]

**Review by antoniospneto — APPROVED** [review]

**Comment by felipemotter** [comment]
@HviorForgeFlow can you bring this changes for 14.0? Or do you authorize me to cherry pick and open a PR?

**Comment by HviorForgeFlow** [comment]
@felipemotter cherry-pick them and link new PR here, thanks!

**Comment by MiquelRForgeFlow** [comment]
@HviorForgeFlow you could also squash commits :)

**Comment by HviorForgeFlow** [comment]
@MiquelRForgeFlow every commit has its purpose :)

**Comment by MiquelRForgeFlow** [comment]
but the last two could be one... 🧐

**Review by vanderleiromera — APPROVED** [review]

**Pull request merged**
