### PR TITLE
[14.0][MIG] product_product_template_navigation

### PR DESCRIPTION
**Pull request by dessanhemrayev**
Migration to 14.0

### CODE REVIEW

**Review by rvalyi — APPROVED** [review]
tested

**Review by francesco-ooops — APPROVED** [review]
Functional ok!

**Comment by francesco-ooops** [comment]
@OCA/product-maintainers merge? :)

**Comment by francesco-ooops** [comment]
@rousseldenis what do you think?

**Comment by francesco-ooops** [comment]
@OCA/product-maintainers gentle reminder

**Comment by francesco-ooops** [comment]
@rousseldenis merge too? :)

**Pull request merged**
