### PR TITLE
[14.0][ADD] product_attribute_value_price_import module

### PR DESCRIPTION
**Pull request by ilyasProgrammer**
This module adds a menu item in sales > configuration where user can see/edit all extra prices set for each attribute value in each product template.

It also allows extra prices to be imported via standard csv/xlsx import.

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
Functional review ok

**Review by olgamarcocb — APPROVED** [review]
LGTM :+1:

**Comment by francesco-ooops** [comment]
@OCA/crm-sales-marketing-maintainers could you take a look?

**Comment by francesco-ooops** [comment]
@OCA/crm-sales-marketing-maintainers any feedback? :)

**Comment by francesco-ooops** [comment]
@OCA/crm-sales-marketing-maintainers hi, could someone take a look?

**Comment by francesco-ooops** [comment]
ping ping @pedrobaeza @rousseldenis :)

**Comment by pedrobaeza** [comment]
@francesco-ooops the rate of other PRs that you and your team review against the reviews you ask for is not balanced. You have to balance it and not ask always for the same wildcards.

**Comment by elvise** [comment]
Hi @pedrobaeza thanks so much for your reply!
I’m a bit confused, in this specific case the PR has both reviews what i should do if not ping OCA ?
Please let me know.

**Comment by pedrobaeza** [comment]
Please read again https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#review

One of the review must come from a PSC or maintainer.

Rules can be relaxed if the module is declared as Alpha.

Anyways, I insist that you are not reviewing any other PR except yours, so that's not fair.

**Comment by elvise** [comment]
> Anyways, I insist that you are not reviewing any other PR except yours, so that's not fair.

Hi @pedrobaeza  
thanks a lot for your reply! 
These are just some PR (that are not ours) where i’m contributing: 

[[ADD] 14.0 pos_product_multi_barcode by PierrickBrun · Pull Request #768 · OCA/pos](https://github.com/OCA/pos/pull/768)

https://github.com/OCA/reporting-engine/pull/591

https://github.com/OCA/sale-reporting/pull/130

https://github.com/OCA/reporting-engine/pull/574

https://github.com/OCA/sale-reporting/pull/130

https://github.com/OCA/account-invoice-reporting/pull/211

https://github.com/OCA/stock-logistics-reporting/pull/177

https://github.com/OCA/reporting-engine/pull/502

So now I have some questions:
how can you track my balance ?
how can you track the balance of our team ? (12 people)

I’m asking because this is really useful for us (and maybe also for others) for get the balance.

**Comment by elvise** [comment]
> One of the review must come from a PSC or maintainer.

That’s the reason why we need ping OCA :)

**Comment by pedrobaeza** [comment]
I judge it looking at the contributor profile: https://github.com/ilyasProgrammer?tab=overview&from=2022-02-01&to=2022-02-28 that there's no review there.

Thanks anyway for your involvement in other PRs. You can ping people from that PRs to review this one.

In a quick review, I would rename the module to `product_attribute_value_menu` and indicate in the README that this allows to import them. Anyways, why don't you import it in the "Attributes" menu entry through the one2many field?

**Comment by elvise** [comment]
> I judge it looking at the contributor profile: https://github.com/ilyasProgrammer?tab=overview&from=2022-02-01&to=2022-02-28 that there's no review there.
> 
> 
> 
> Thanks anyway for your involvement in other PRs. You can ping people from that PRs to review this one.
> 
> 
> 
> In a quick review, I would rename the module to `product_attribute_value_menu` and indicate in the README that this allows to import them. Anyways, why don't you import it in the "Attributes" menu entry through the one2many field?

Hi @pedrobaeza 
and thank you for not leaving me alone in this jungle! :)

Maybe we need to fix some things in our organisation too…
So let me share to you how we organised the activities.

Developers: 
- Porting modules from previous versions 
- Backport modules from the newest versions 
- Open PRs for new modules
- Code reviews (we need to increase it for sure)

Consultants:
- Take care for not get the P.R. in stale (ours or not)
- Functional review (ours or not)
- Check if needed to squash (for save the PSC time)
- Check for the basic checks: Runboat - Travis - Coverage Tests (for save the PSC time)
- Translate (ours or not)
- Stress PSC for get the final merge :)

Workflow:
- Open task [Consultant]
- Code [Developer]
- Open new P.R. [Developer]
- Functional review [Consultant]
- Fix functional review [Developer]
- Functional review [Consultant]
- Code review [Developer]
- Fix code review [Developer]

So we iterate this flow until to get:
- Functional review > Ok
- Code review > Ok
- All checks > Green (Runboat, Travis, Coverage Test etc)

Now when we have these 3 points done we getting tags:
- Approved
- Ready to Merge

So now we expect someone from the PSC to arrive to do the final review (as this is the only way) and then merge.
For sure we understand that there is to wait as we are talking about a community one, two, three, four, five and if you want also one week, but for sure not months.
Check this case: this PR is ready for the PSC 24 days ago, but nobody is here, despite we ping constantly.
Check this case: [14.0][ADD] sale_commission_agent_restrict by ilyasProgrammer · Pull Request #354 · OCA/commission stuck from 24 days, despite we ping constantly.

I have a lot of this cases even worse than these. 

Please don't take this conversation as a controversy, we are trying to figure out how to improve ourselves or how to improve the OCA flow or anyway how we can fortify the collaboration with OCA ecosystem.

For last but not least thanks again for your patience :)

**Comment by francesco-ooops** [comment]
> In a quick review, I would rename the module to `product_attribute_value_menu` and indicate in the README that this allows to import them. Anyways, why don't you import it in the "Attributes" menu entry through the one2many field?

Hi @pedrobaeza , I'm not sure what you are referring to, maybe the module's goal is not too clear, use case: 

For product template "Configurable Desk", attribute value "Legs: steel" has an extra price of 100, "Legs: aluminum" has an extra price of 50; 
for product template "Configurable Chair", attribute value "Legs: steel" has an extra price of 30, "Legs: aluminum" has an extra price of 15

in vanilla odoo you can only set these extra prices manually for each product template by clicking "configure variants", clicking on the single attribute value, edit, change price (not even bulk change, which wouldn't even be so useful); this is not convenient when importing products data for a new customer or new products. 

Hence this module, which allows you to set the prices in bulk by filtering/grouping by attribute value and product template, or use the csv import for these PTAV extra price fields

in light of this, what do you think should be changed/improved? 

thanks :)

**Comment by rousseldenis** [comment]
> > In a quick review, I would rename the module to `product_attribute_value_menu` and indicate in the README that this allows to import them. Anyways, why don't you import it in the "Attributes" menu entry through the one2many field?
> 
> Hi @pedrobaeza , I'm not sure what you are referring to, maybe the module's goal is not too clear, use case:
> 
> For product template "Configurable Desk", attribute value "Legs: steel" has an extra price of 100, "Legs: aluminum" has an extra price of 50; for product template "Configurable Chair", attribute value "Legs: steel" has an extra price of 30, "Legs: aluminum" has an extra price of 15
> 
> in vanilla odoo you can only set these extra prices manually for each product template by clicking "configure variants", clicking on the single attribute value, edit, change price (not even bulk change, which wouldn't even be so useful); this is not convenient when importing products data for a new customer or new products.
> 
> Hence this module, which allows you to set the prices in bulk by filtering/grouping by attribute value and product template, or use the csv import for these PTAV extra price fields
> 
> in light of this, what do you think should be changed/improved?
> 
> thanks :)

That's a good reason to do it.

**Review by rousseldenis — APPROVED** [review]
Functionnaly tested

**Review by elvise — APPROVED** [review]

**Comment by elvise** [comment]
> In a quick review, I would rename the module to `product_attribute_value_menu` and indicate in the README that this allows to import them

@ilyasProgrammer can you check this review ?

**Comment by francesco-ooops** [comment]
@pedrobaeza better now?

**Comment by pedrobaeza** [comment]
Yes, thanks

/ocabot merge nobump

**Comment by pedrobaeza** [comment]
> Hi @pedrobaeza and thank you for not leaving me alone in this jungle! :)
> 
> Maybe we need to fix some things in our organisation too… So let me share to you how we organised the activities.
> 
> Developers:
> 
>     * Porting modules from previous versions
>     * Backport modules from the newest versions
>     * Open PRs for new modules
>     * Code reviews (we need to increase it for sure)
> 
> Consultants:
> 
>     * Take care for not get the P.R. in stale (ours or not)
>     * Functional review (ours or not)
>     * Check if needed to squash (for save the PSC time)
>     * Check for the basic checks: Runboat - Travis - Coverage Tests (for save the PSC time)
>     * Translate (ours or not)
>     * Stress PSC for get the final merge :)
> 
> Workflow:
> 
>     * Open task [Consultant]
>     * Code [Developer]
>     * Open new P.R. [Developer]
>     * Functional review [Consultant]
>     * Fix functional review [Developer]
>     * Functional review [Consultant]
>     * Code review [Developer]
>     * Fix code review [Developer]
> 
> So we iterate this flow until to get:
> 
>     * Functional review > Ok
>     * Code review > Ok
>     * All checks > Green (Runboat, Travis, Coverage Test etc)
> 
> Now when we have these 3 points done we getting tags:
> 
>     * Approved
>     * Ready to Merge
> 
> So now we expect someone from the PSC to arrive to do the final review (as this is the only way) and then merge. For sure we understand that there is to wait as we are talking about a community one, two, three, four, five and if you want also one week, but for sure not months. Check this case: this PR is ready for the PSC 24 days ago, but nobody is here, despite we ping constantly. Check this case: [14.0][ADD] sale_commission_agent_restrict by ilyasProgrammer · Pull Request #354 · OCA/commission stuck from 24 days, despite we ping constantly.
> 
> I have a lot of this cases even worse than these.
> 
> Please don't take this conversation as a controversy, we are trying to figure out how to improve ourselves or how to improve the OCA flow or anyway how we can fortify the collaboration with OCA ecosystem.
> 
> For last but not least thanks again for your patience :)

About this, first of all, thanks for your involvement around OCA. I hope all the companies around working with Odoo make the same as you.

For OCA ecosystem to be sustainable, all the companies involved should balance the work to be done inside  it, and this includes both contributing code (migrations, new modules, etc), with the review of the code contributed by yourself or others. And this review is both technical and functional side. Is the technical review side which I see that you lack a bit, so it's convenient that your developers also perform such reviews, first on your pull requests to assure your quality (OCA CI indicators is just the tip of the iceberg), and also on others.

It's also advisable to indicate in your reviews that it has been a functional or a code review.

Your pipeline seems good and well organized. Your next logical step is to scale your involvement requesting to be PSC of the repositories for being self-independent. This is a meritocracy, and you have to request such inclusion in contributors at odoo-community.org. You can do it in a minor scale declaring a maintainer on your new modules, so you can perform patches in a quick way without requiring a PSC.

In any case, continue with this excellent trend and hope you to see in person in Odoo experience event.

**Comment by francesco-ooops** [comment]
@pedrobaeza @rousseldenis I think in this PR a new module was merged in v.14 using the same technical name as another existing module in v.13 (product_attribute_value_menu, see #997 )

was that intentional? looks confusing to me, they also have different features and purposes

odoo store even sees them as the same module [link](https://apps.odoo.com/apps/modules/13.0/product_attribute_value_menu/)

**Comment by pedrobaeza** [comment]
It was an accidental name collapsing it seems.

**Comment by francesco-ooops** [comment]
> It was an accidental name collapsing it seems.

shall we fix it somehow? maybe add a note in roadmap for both modules?

**Comment by pedrobaeza** [comment]
Is the other module going to be migrated to 14? If not, we can continue this way.

**Comment by francesco-ooops** [comment]
> Is the other module going to be migrated to 14? If not, we can continue this way.

how could I predict that? 😅

and what happens if both modules need to be migrated to 15? 

I think editing known issues/roadmap is the fastest way to make users aware that the one in v.13 and the one in v.14 are different modules and take necessary steps

**Comment by pedrobaeza** [comment]
OK, as you prefer.

**Comment by pedrobaeza** [comment]
Can't be both functionalities included in the module?

**Comment by francesco-ooops** [comment]
@pedrobaeza doesn't sound like the worst idea :)

**Comment by JordiMForgeFlow** [comment]
Hi @pedrobaeza and @francesco-ooops 

We are in fact going to migrate the module (https://github.com/OCA/product-attribute/pull/997) to V14 and V15.

However, I think that this module you have renamed should in fact be named `product_template_attribute_value_menu`, as it is what it is adding.

Another option, as Pedro suggests, could be to add both functionalities in the module.

Please, let me know your thoughts so we can fix this collapse in the names :)

CC @GuillemCForgeFlow

**Comment by francesco-ooops** [comment]
Hi @JordiMForgeFlow

I agree with both options, renaming (the name you suggest is the correct one) and "merging" both modules into one, but I would go for the latter

we can not work on this before a couple weeks, if you want to proceed please go ahead and keep us posted :)

**Comment by JordiMForgeFlow** [comment]
Hi @francesco-ooops 

Thank you for getting back :) We will take care of adding the features from the module in V13 to your module in next versions

**Comment by francesco-ooops** [comment]
great thanks a lot!

**Comment by francesco-ooops** [comment]
> Hi @francesco-ooops
> 
> Thank you for getting back :) We will take care of adding the features from the module in V13 to your module in next versions

Hi @JordiMForgeFlow , any ETA? just for scheduling. Thanks!

**Comment by JordiMForgeFlow** [comment]
Hi @francesco-ooops 

We have now opened a PR to add the features: https://github.com/OCA/product-attribute/pull/1132 :)

**Pull request merged**
