### PR TITLE
[15.0] [MIG] product_code_unique

### PR DESCRIPTION
**Pull request by nedaszilinskas**

### CODE REVIEW

**Comment by nedaszilinskas** [comment]
Ping @OCA/oca-contributors. Looking for a friend to review this :)

**Review by gaikaz — APPROVED** [review]
LGTM

**Review by bizzappdev — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
It works. It would be nice if multicompany features are added to the module (unique code by company), but I guess that would require a complete refactor.

**Review by jcdrubay — APPROVED** [review]
LGTM

**Review by leemannd — APPROVED** [review]

**Comment by nedaszilinskas** [comment]
@simahawk is there something I should do to make this work?

**Comment by simahawk** [comment]
pre-commit failed on the merge build. Is a race condition that should have been fixed recently. We need to sync this repo w/ the addon template. Meanwhile...

/ocabot merge nobump

**Pull request merged**
