### PR TITLE
[14.0] product_supplierinfo_archive: add a cron task to disable expired vendor pricelists

### PR DESCRIPTION
**Pull request by sebalix**
The cron task is disabled by default.

ref 4126

### CODE REVIEW

**Review by mmequignon — APPROVED** [review]

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM! 👍🏽

**Review by TDu — APPROVED** [review]

**Comment by sebalix** [comment]
@GuillemCForgeFlow could you merge this one please? (as you are one of the maintainer :) )

**Comment by GuillemCForgeFlow** [comment]
done @sebalix 😄

**Pull request merged**
