### PR TITLE
[16.0][MIG] product_pricelist_direct_print_website_sale: Migration to version 16.0

### PR DESCRIPTION
**Pull request by carolinafernandez-tecnativa**
- Add new dependency to product_pricelist_direct_print_xlsx 
- Change inherit name report

@Tecnativa

TT44340

@pedrobaeza @CarlosRoca13

### CODE REVIEW

**Comment by pedrobaeza** [comment]
/ocabot migration product_pricelist_direct_print_website_sale

**Review by pedrobaeza — APPROVED** [review]

**Comment by legalsylvain** [comment]
Hi @carolinafernandez-tecnativa. 

I don't understand why porting this module. I see it as obsolete.
If I read correctly the readme, this module allow to group by website category, instead of internal categories. But since recent refactor, it is possible by UI, to select the field you want to group by.


Ref : https://github.com/OCA/product-attribute/tree/16.0/product_pricelist_direct_print#usage

image

Note : just a non blocking question.

**Comment by carolinafernandez-tecnativa** [comment]
> Hi @carolinafernandez-tecnativa.
> 
> I don't understand why porting this module. I see it as obsolete. If I read correctly the readme, this module allow to group by website category, instead of internal categories. But since recent refactor, it is possible by UI, to select the field you want to group by.
> 
> Ref : https://github.com/OCA/product-attribute/tree/16.0/product_pricelist_direct_print#usage
> 
> image
> 
> Note : just a non blocking question.

Please check behaviour of this module, you will see it adds some columns in report xlsx

**Comment by carolinafernandez-tecnativa** [comment]
ping @CarlosRoca13

**Review by CarlosRoca13 — APPROVED** [review]
Code review :+1:  Thanks!

**Pull request merged**
