### PR TITLE
[12.0] Move state on the same header - product_state 

### PR DESCRIPTION
**Pull request by ypapouin**
This module add a second header in the product form view.
I propose to move the state field in the existing header.

### CODE REVIEW

**Comment by rousseldenis** [comment]
Indeed. On runbot :

image

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by emagdalenaC2i** [comment]
This is part of the #574 improvements. See https://github.com/OCA/product-attribute/pull/574/files?file-filters%5B%5D=.xml#r389313050

**Comment by ypapouin** [comment]
- Is there an alias to ping the PSC team or do I need to ping each members ?
- Is there a way to retrieve all PSC team members from the github repository somewhere ? (I manually found https://odoo-community.org/psc-teams/product-27 on OCA website).
- If not, then the Bot should at least give these informations.

By the way, the link is returning a 404
image

**Pull request closed without merging**
