### PR TITLE
[15.0][MIG] product_variant_attribute_name_manager: Migration to 15.0

### PR DESCRIPTION
**Pull request by OriolVForgeFlow**
Standard migration.
@ForgeFlow

### CODE REVIEW

**Review by BernatPForgeFlow — APPROVED** [review]

**Review by mariadforgeflow — APPROVED** [review]
Functional review. LGTM!

**Review by albariera — APPROVED** [review]

**Review by Daniel-CA — APPROVED** [review]
LGTM

**Comment by mariadforgeflow** [comment]
Hi @pedrobaeza! Could you merge this please?

**Pull request merged**
