### PR TITLE
[13.0][FIX] product_medical: add fields

### PR DESCRIPTION
**Pull request by i-vyshnevska**
add fields to product.template and form view

### CODE REVIEW

**Comment by etobella** [comment]
I know now thuis comment is too late, but I think I have to tell something.

What you are proposing is not medical product, this are medical device products. A medical product can be a lot of things: A medication, a medical service... So, IMO, maybe we need to change some things here. I know that the module name, shouldn't be changed now, as it is merged, but maybe the name of the fields (`is_medical` --> `is_medical_device`). If you want, I can make the migration script. 

Also, just to clarify some things. This kind of devices are usually created by hospitals? If true, this module should need to be on OCA/vertical-medical, WDYT?

Also, If these are for devices shouldn't it be managed by `maintenance.equipment`s? Just wondering, because we are currently managing this kind of devices as equipments.

**Comment by i-vyshnevska** [comment]
@etobella this can be a big discussion about implementation, the introduced addon is to handle medical products for retail that is why it is not on vertical-medical

**Comment by etobella** [comment]
Ok! good for me, then might be possible to change the field `is_medical` for `is_medical_device`? At least in order to avoid confusion? 

The module name already exists so it cannot be changed, but would be interesting to propose the change for v14 on ROADMAP.

**Comment by simahawk** [comment]
@i-vyshnevska ping

**Comment by carlosserratoro** [comment]
This has been modified by https://github.com/OCA/product-attribute/pull/783. There, among other changes, we remove the field ```is_medical```.

**Pull request closed without merging**
