### PR TITLE
[MIG][10.0] product_uom

### PR DESCRIPTION
**Pull request by lasley**
* Bump version
* Rename manifest

### CODE REVIEW

**Review by max3903 — APPROVED** [review]

**Comment by rafaelbn** [comment]
Runbot fails, I cannot test it

**Review by leemannd — APPROVED** [review]
Code review only

**Comment by pedrobaeza** [comment]
Please squash conveniently before merging.

**Comment by lasley** [comment]
I squashed my PR commit into the migration one.

I didn't squash my medical units addition into the migration commit though because they are different logical changesets. Anyone disagree?

**Pull request merged**
