### PR TITLE
[15.0] [MIG] product_code_mandatory

### PR DESCRIPTION
**Pull request by nedaszilinskas**

### CODE REVIEW

**Comment by nedaszilinskas** [comment]
@OCA/community-maintainers , I'm looking for a friend to review this one :) And maybe help/explain why runbot is failing?

**Comment by simahawk** [comment]
you can ignore runbot, it will be killed in the next future. We use only runboat on v15 :wink:

**Comment by nedaszilinskas** [comment]
Ping @OCA/oca-contributors. Can anyone help with the review? :)

**Comment by jcdrubay** [comment]
hello @nedaszilinskas 
as a requirement for your work to be merged, you will need to adjust the commit history:
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0
This will help a lot for code review as well.
good luck

**Review by jcdrubay — APPROVED** [review]

**Review by gaikaz — APPROVED** [review]

**Review by bizzappdev — APPROVED** [review]

**Review by matteoopenf — APPROVED** [review]

**Comment by leemannd** [comment]
@nedaszilinskas Thank you for the migration.
For this repo @OCA/product-maintainers may help to merge it

**Review by celm1990 — COMMENTED** [review]
I think is need replace all reference 14 > 15 (readme, index.html, etc) or oca-bot doing automatically???

**Comment by AaronHForgeFlow** [comment]
@celm1990 oca-bot will do that automatically

**Pull request merged**
