### PR TITLE
[16.0][IMP] `product_template_tag`: add parent tags

### PR DESCRIPTION
**Pull request by SilvioC2C**
Forward port of https://github.com/OCA/product-attribute/pull/1504

EDIT: some tests seem to be failing for reasons unrelated to this PR, as they are also currently failing on branch `16.0`.

### CODE REVIEW

**Review by yankinmax — APPROVED** [review]

**Review by gurneyalex — APPROVED** [review]

**Comment by simahawk** [comment]
tests fixed. Rebase pls

**Review by legalsylvain — CHANGES_REQUESTED** [review]
need rebase.

**Review by legalsylvain — APPROVED** [review]

**Pull request merged**
