### PR TITLE
[13.0][MIG] product_pricelist_simulation: Migration to 13.0

### PR DESCRIPTION
**Pull request by ernestotejeda**
Migration of this module: https://github.com/OCA/product-attribute/pull/222

Main changes:
- Add smart-button to show the prices on a wizard.

### CODE REVIEW

**Comment by ernestotejeda** [comment]
ping @pedrobaeza

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Hi @ernestotejeda. 

I just tested your new module. At a first sight, it looks very similar to an existing V12 module named ``product_pricelist_margin``. https://github.com/OCA/margin-analysis/tree/12.0/product_pricelist_margin#readme

**common features**
- add a button in the product form view
- simulate prices for each pricelist

**Feature present in existing module and not in your proposal**
- add the real margin, that is great in my opinion.
- display color depending on the margin. With red color, if the sale price is lower than the standard price for a pricelist. (negative margin).
- allow to set date and quantity in the wizard, to make full simulation

**Feature present in your proposal module and not in the existing OCA module**
- checkbox on the pricelist, to enable the feature.

What about to base your work on the existing module, and add the checkbox, to avoid to have 2 OCA modules with similar feature.

Note : let me know if features are not covered in the existing module.

thanks !

**Comment by pedrobaeza** [comment]
Yes, it's similar, but the module name is very awful for the real purpose. We want also to not depend in any extra module. Why are you depending on `sale`?

**Comment by legalsylvain** [comment]
> but the module name is very awful for the real purpose

Yeah I forgot to ping pedrobot regarding the name ;-) sorry. What could you propose ? maybe ``product_margin_pricelist_simulation`` ? I'm ok to change. (maybe for a migration, if it's ok for you to keep the name for V12 branch ?)

> Why are you depending on sale?

I don't know. See : https://github.com/OCA/margin-analysis/pull/135

Ref : original PR : https://github.com/OCA/margin-analysis/pull/96 and original reviewer @sergiocorato @quentinDupont @JordiMForgeFlow

**Comment by pedrobaeza** [comment]
Closing in favor of #1114

**Pull request closed without merging**
