### PR TITLE
[17.0][MIG] product_code_unique: migration to 17.0

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Review by bizzappdev — APPROVED** [review]
Code and Functional Both LGTM

**Review by nguyenminhchien — APPROVED** [review]

**Review by DorianMAG — APPROVED** [review]
easy code review.
LGTM
something seems to be wrong with the runabout, can't be tested on this one

**Review by PCatinean — APPROVED** [review]

**Comment by DorianMAG** [comment]
Hi @astirpe 
Can you make a rebase plz

**Pull request merged**
