### PR TITLE
[FIX] add instruction to migrate product_code_builder

### PR DESCRIPTION
**Pull request by bealdav**
ping @eLBati @pedrobaeza @sebastienbeau  thanks

### CODE REVIEW

**Comment by astirpe** [comment]
LGTM

**Comment by espo-tony** [comment]
:+1:

**Comment by lasley** [comment]
Isn't this more suited for OpenUpgrade? IMO migrations between Odoo major versions are out of scope for modules.

**Comment by bealdav** [comment]
Modules must be improve version after version whatever using openugrade or not.
Yes it would be better to add a migration script but I have no time for now.
Then, it's just a reminder for future porting

**Comment by bealdav** [comment]
@gurneyalex what is your opinion there ?

**Review by gurneyalex — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
