### PR TITLE
[15.0][MIG] product_packaging_dimension

### PR DESCRIPTION
**Pull request by flachica**
Dependencies

https://github.com/OCA/product-attribute/pull/1151

### CODE REVIEW

**Comment by rousseldenis** [comment]
@flachica Could you add depending PR's in your migration ones descriptions? It would help reviewer doing his job. Thanks

**Comment by flachica** [comment]
Sorry @rousseldenis 

This is one
https://github.com/OCA/product-attribute/pull/1151

**Comment by ghost** [comment]
Is there still something missing to upgrade it to V15?

**Review by rousseldenis — APPROVED** [review]

**Pull request closed without merging**
