### PR TITLE
[16.0][ADD] product_supplierinfo_code

### PR DESCRIPTION
**Pull request by clementmbr**
Based on #832 
Add a `supplier_product_code` computed field on products :
image

cc @florian-dacosta @rousseldenis

### CODE REVIEW

**Review by flotho — APPROVED** [review]
usefull module,
easy code review
LGTM

**Review by florian-dacosta — APPROVED** [review]
LGTM

**Review by AungKoKoLin1997 — APPROVED** [review]
LGTM.

**Pull request merged**
