### PR TITLE
[15.0][MIG] product category code

### PR DESCRIPTION
**Pull request by Rad0van**
Standard migration

### CODE REVIEW

**Comment by rolandojduartem** [comment]
Hi, @Rad0van, please, may you rebase and ask review of this pull request?

**Comment by Rad0van** [comment]
> Hi, @Rad0van, please, may you rebase and ask review of this pull request?

@rolandojduartem should be done. Please review. Also please if @rousseldenis, @sergio-teruel or anyone else. Thank you.

**Review by sergio-teruel — APPROVED** [review]

**Comment by rolandojduartem** [comment]
Hi, @hugho-ad and @luisg123v, may you support here?, this is related to #1085

**Comment by Rad0van** [comment]
@rolandojduartem you can review as well. 2 reviews are enough AFAIK.

**Review by luisg123v — APPROVED** [review]
LGTM :+1: 

CC @moylop260

**Pull request merged**
