### PR TITLE
[14.0] [ADD] new product_sale_manufactured_for module

### PR DESCRIPTION
**Pull request by hailangvn**
Allows to indicate in products that they were made
(i.e. manufactured) specifically for some customers.

In a sale order, allow to only select products from
the UI that were manufactured for the chosen customer.

### CODE REVIEW

**Review by sebalix — APPROVED** [review]
LG

**Review by ajaniszewska-dev — APPROVED** [review]

**Comment by hailangvn** [comment]
I've just squashed all commits into one.

**Review by santostelmo — APPROVED** [review]
LG

**Pull request merged**
