### PR TITLE
[15.0][MIG] purchase_product_template_tags: Migration to 15.0

### PR DESCRIPTION
**Pull request by dhx**
Standard migration

### CODE REVIEW

**Comment by dhx** [comment]
Hi @ivantodorovich looks good in our setup - would be happy to get a review / it merged :)

**Review by ivantodorovich — APPROVED** [review]

**Comment by ivantodorovich** [comment]
Well.. weird. I am the module maintainer but ocabot doesn't allow me to merge it.
We need a PSC member to do it, then

**Comment by dhx** [comment]
Hi @pedrobaeza it seems you did merge the latest PRs in the repo, do you have an idea why @ivantodorovich is not able to do it here (and also in https://github.com/OCA/product-attribute/pull/1118  )?

**Comment by pedrobaeza** [comment]
Maintainers can only merge for now patches over an existing module, not the migration PR.

/ocabot migration purchase_product_template_tags
/ocabot merge nobump

**Comment by dhx** [comment]
@pedrobaeza thanks for the fast response and clarification.

**Pull request merged**
