### PR TITLE
ADD product_feature

### PR DESCRIPTION
**Pull request by rubencabrera**
ADD a module to add product features with an image.

Product features are added to the template and common to all variants. The relationship is a M2M and the name of the feature must be unique. 

Related to #215

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Looking at the code, this overlaps a lot with _product_custom_info_ module, that only needs to add an image field to their templating structure, so :-1: for this. It also lacks all the OCA guidelines conventions on the code.

**Comment by rubencabrera** [comment]
All the guidelines conventions? Seriously? Give me a hint so I can solve it, because I used another module from the repo as template.

product_custom_info_module is very complete and I tried to demo it to the client so we could just add an image and make it work, but it needs too many steps for such a simple task that the customer asked for a custom development, the result is what I shared, hoping someone would find it useful.

**Comment by pedrobaeza** [comment]
product_custom_info is not complicated. Check OCA guidelines here: https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md

**Comment by lasley** [comment]
@rubencabrera - a lot of the 8.0 modules don't comply with current guidelines. In the same repo Pedro linked, there is a template module that has some excellent samples in it of essentially anything you need: https://github.com/OCA/maintainer-tools/tree/master/template/module

We keep the samples updated to the guides, so it is much easier than using pre-existing modules that may have aged.

Regarding this module - I dunno if it's necessarily a duplication because we are missing the image feature in the `product_custom_info`. I think though that this might lead to a dangerous data path.

I feel like this data/images are going to be far from Odoo core, so it's always going to be an outlier that has to be designed around & causing kind of an N+1 module proliferation. An example would be integration of this into something like `website_sale`, showing the features in an invoice, etc.

Do you mind explaining a bit of use case for context here?

**Comment by rubencabrera** [comment]
Thanks for your thorough answer, @lasley 

I'll use the templates to check the modules and change wherever I see differences. 

The use case for this module is oriented towards web_sale and mobile apps connecting to odoo. Besides product images, which show different relevant images about each particular product or product variant, some use cases require more general attributes. 

Things like "100% cotton" if we sell clothes, "Water resistant" for watches or "handcrafted" for something else. The image attached to the feature is intended to be shown to customers and maybe some reports, as you suggest. 

The thing about product_custom_info is that we set values per each product, which is not needed for this more straight forward feature idea. Also, when defining a new template for custom info, we can add properties with the same name as existing one(s). I don't think product_custom_info is overcomplicated _per se_, it's just that this use case is way more simple than what it covers. 

Also, I found where I saw this module: at 2 different clients. They already have similar developments from different partners, so I still think someone will find this simple solution suitable for already existing needs.

**Pull request closed without merging**
