### PR TITLE
[MIG] product_multi_image: Migration to 12.0

### PR DESCRIPTION
**Pull request by shepilov-vladislav**
Did a migration for 12.0(based on https://github.com/OCA/product-attribute/pull/358)

### CODE REVIEW

**Comment by FFernandez-PlanetaTIC** [comment]
Please, preserve commit history. Thanks!

**Comment by rafaelbn** [comment]
Hi @shepilov-vladislav , plese follow the Guidelines, thanks!

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

**Comment by rafaelbn** [comment]
Hi @shepilov-vladislav  I think you could close this PR. Odoo v11 by default has multi-images. Or Any @OCA/product-maintainers

**Comment by FFernandez-PlanetaTIC** [comment]
Before closing this PR see https://github.com/OCA/product-attribute/pull/358#issuecomment-528880199

**Comment by FFernandez-PlanetaTIC** [comment]
Hi @shepilov-vladislav ,

Could you preserve commit history as you did in OCA/server-tools#1650?

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0#user-content-technical-method-to-migrate-a-module-from-110-to-120-branch

Thank you!

**Comment by shepilov-vladislav** [comment]
So old

**Pull request closed without merging**
