### PR TITLE
[14.0][MIG]product pricelist assortment

### PR DESCRIPTION
**Pull request by xavier-bouquiaux**

### CODE REVIEW

**Review by hparfr — APPROVED** [review]

**Comment by francesco-ooops** [comment]
@xavier-bouquiaux could you rebase in order to test on runboat?

**Comment by xavier-bouquiaux** [comment]
> @xavier-bouquiaux could you rebase in order to test on runboat?

Done

**Review by francesco-ooops — APPROVED** [review]
Functional review ok!

@OCA/product-maintainers good for merge?

**Pull request merged**
