### PR TITLE
[15.0][MIG] product_pricelist_direct_print: Migration to 15.0

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT36498

please @ernestotejeda @cesar-tecnativa review this

### CODE REVIEW

**Comment by cesar-tecnativa** [comment]
Change commit message [[IMP] product_pricelist_direct_print: black, isort, prettier](https://github.com/OCA/product-attribute/pull/1117/commits/88015ee9b625778d9ec1c4812705d18ccfde6b68) to [[MIG] product_pricelist_direct_print: black, isort, prettier](https://github.com/OCA/product-attribute/pull/1117/commits/88015ee9b625778d9ec1c4812705d18ccfde6b68)

**Review by cesar-tecnativa — APPROVED** [review]

**Comment by CarlosRoca13** [comment]
> Change commit message [[IMP] product_pricelist_direct_print: black, isort, prettier](https://github.com/OCA/product-attribute/pull/1117/commits/88015ee9b625778d9ec1c4812705d18ccfde6b68) to [[MIG] product_pricelist_direct_print: black, isort, prettier](https://github.com/OCA/product-attribute/pull/1117/commits/88015ee9b625778d9ec1c4812705d18ccfde6b68)

It is set as the guidelines say: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#user-content-technical-method-to-migrate-a-module-from-140-to-150-branch

**Comment by cesar-tecnativa** [comment]
> > Change commit message [[IMP] product_pricelist_direct_print: black, isort, prettier](https://github.com/OCA/product-attribute/pull/1117/commits/88015ee9b625778d9ec1c4812705d18ccfde6b68) to [[MIG] product_pricelist_direct_print: black, isort, prettier](https://github.com/OCA/product-attribute/pull/1117/commits/88015ee9b625778d9ec1c4812705d18ccfde6b68)
> 
> It is set as the guidelines say: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#user-content-technical-method-to-migrate-a-module-from-140-to-150-branch

ok

**Review by sergio-teruel — APPROVED** [review]

**Comment by sergio-teruel** [comment]
ping @carlosdauden

**Comment by pedrobaeza** [comment]
Let's merge it

/ocabot migration product_pricelist_direct_print
/ocabot merge nobump

**Pull request merged**
