### PR TITLE
[17.0][MIG] sale_product_template_tags: Migration to 17.0

### PR DESCRIPTION
**Pull request by lef-adhoc**

### CODE REVIEW

**Comment by lav-adhoc** [comment]
@ivantodorovich hi Ivan, may you check this? 
Thanks

**Review by ivantodorovich — APPROVED** [review]
LGTM 👍🏻 straightforward migration 
Thanks for taking care of this 🙏🏻 !

**Comment by peluko00** [comment]
Can you push again for the runboat build? @lef-adhoc

**Comment by lef-adhoc** [comment]
@peluko00 It's ready

**Review by peluko00 — APPROVED** [review]
Works good, tested in runboat

**Comment by peluko00** [comment]
> @peluko00 It's ready

Thanks!

**Review by mpascuall — APPROVED** [review]
Working correctly, checked in runboat

**Comment by peluko00** [comment]
Seems it's ready to merge @HaraldPanten?

**Comment by HaraldPanten** [comment]
@lef-adhoc Could yu rebase, please?

**Comment by lef-adhoc** [comment]
@HaraldPanten It is ready

**Comment by peluko00** [comment]
Squash administrive commits please @lef-adhoc

**Review by HaraldPanten — APPROVED** [review]

**Pull request merged**
