### PR TITLE
add chinese translation

### PR DESCRIPTION
**Pull request by digitalsatori**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please use Weblate for this: https://odoo-community.org/blog/the-oca-blog-1/post/translations-platform-81

**Comment by digitalsatori** [comment]
> Please use Weblate for this: https://odoo-community.org/blog/the-oca-blog-1/post/translations-platform-81

I wish I could. There is no Chinese language option for the module. I'm not able to start a translation. Probably permission issue.

**Comment by pedrobaeza** [comment]
Have you requested the access to that language? Please read the post about how to do it (in a nutshell, send an email). Any way, I have already added you to the Chinese translators.

**Comment by digitalsatori** [comment]
@pedrobaeza Thank you. I confirm I can do the translation now.

**Pull request closed without merging**
