### PR TITLE
[16.0] MIG product_pricelist_direct_print

### PR DESCRIPTION
**Pull request by legalsylvain**
- [x] Port ``product_pricelist_direct_print`` from 15.0 to 16.0. (Fix new way to compute pricelist price, adapt test)
- [x] Possbility to display Product UoM (from https://github.com/OCA/product-attribute/pull/1177)
- [x] Possibility to display pricelist prices vat excl or vat incl (from https://github.com/OCA/product-attribute/pull/1177)
- [x] Possibility to group by any product field
- [x] improve wizard display, grouping fields by concept
- [x] harmonize fields names : Use only 'positive' option 'show' and remove 'hide' option
- [x] set date as required, simplifying algorithm. Replace date by datetime, because date_start and date_end are datetime on ``product.pricelist.item`` model.
- [x] split module into ``product_pricelist_direct_print`` and ``product_pricelist_direct_print_xlsx`` to avoid to force to install ``report_xlsx`` if we want the main feature
- [x] add credits and set legalsylvain as maintainer of the main module 

wizard_form

### CODE REVIEW

**Comment by legalsylvain** [comment]
This one is ready for review.
CC : original contributors : @carlosdauden , @chienandalu, @ernestotejeda, @alexey-pelykh, @sergio-teruel, @joao-p-marques, @CarlosRoca13

CC : @ferran-S73 (ref : https://github.com/OCA/product-attribute/pull/1231)

Thanks !

**Review by sergio-teruel — APPROVED** [review]
Great!!!
@legalsylvain Can you add the last commit on v13 (https://github.com/OCA/product-attribute/pull/1346/commits/3fa6d46f43d4ba721ae5aaad9879ff293a0d7025)

Thanks

**Comment by ferran-S73** [comment]
> This one is ready for review. CC : original contributors : @carlosdauden , @chienandalu, @ernestotejeda, @alexey-pelykh, @sergio-teruel, @joao-p-marques, @CarlosRoca13
> 
> CC : @ferran-S73 (ref : #1231)
> 
> Thanks !

Do you plan on adding https://github.com/OCA/product-attribute/pull/1231? Other than that LGTM. Thanks for the great work!

**Comment by ferran-S73** [comment]
> > This one is ready for review. CC : original contributors : @carlosdauden , @chienandalu, @ernestotejeda, @alexey-pelykh, @sergio-teruel, @joao-p-marques, @CarlosRoca13
> > CC : @ferran-S73 (ref : #1231)
> > Thanks !
> 
> Do you plan on adding #1231? Other than that LGTM. Thanks for the great work!

**Comment by legalsylvain** [comment]
Hi @ferran-S73, @sergio-teruel, Thanks for your feedback.
regarding #1231 and https://github.com/OCA/product-attribute/commit/3fa6d46f43d4ba721ae5aaad9879ff293a0d7025 I have no time in the next week sfor that task. (I spend too much time migrating / improving the module).
we can do it in a second time once this one is merged or if you want, you can make a PR against my branch and I'll merge it quickly. Let me know ! 
Note : as the refactor is quite big, cherry-pick will have to be adapted.

**Comment by sergio-teruel** [comment]
Perfect @legalsylvain When the module is merged we can add the commits...

**Review by ferran-S73 — APPROVED** [review]

**Pull request merged**
