### PR TITLE
[15.0] [MIG] product_assortment: Migration to 15.0

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT36491

please @sergio-teruel @carlosdauden review this

### CODE REVIEW

**Comment by CarlosRoca13** [comment]
Cherry picked https://github.com/OCA/product-attribute/commit/d90db2c58e26d81a82fd39ddc8cb3e43d2aafb49

**Review by cesar-tecnativa — APPROVED** [review]

**Review by victoralmau — APPROVED** [review]
Code review ok

**Pull request merged**
