### PR TITLE
[13.0][MIG]product_category_code: backport from 14.0

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
No changes required.

Ping @ForgeFlow

### CODE REVIEW

**Review by albariera — COMMENTED** [review]
LGTM :+1:

**Review by albariera — APPROVED** [review]

**Review by Rad0van — APPROVED** [review]
LGTM. No testing though.

**Comment by AaronHForgeFlow** [comment]
@rousseldenis you are the maintainer of the module. Is this fine to you?

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
