### PR TITLE
[FIX] lenght name consistency migration

### PR DESCRIPTION
**Pull request by Kev-Roche**
Rename  "packaging_length" to the original name "lnght" in order to keep consistency with other modules.

### CODE REVIEW

**Comment by hparfr** [comment]
Module : product_packaging_dimension

**Review by hparfr — CHANGES_REQUESTED** [review]
You have to rename the field in  odoo.

**Review by hparfr — CHANGES_REQUESTED** [review]
You have to rename the field in odoo too.

**Review by hparfr — APPROVED** [review]
LGTM thanks

**Comment by Kev-Roche** [comment]
Hi @rvalyi, @clementmbr, we did a little revert fix about packaging_length and the original name "lnght"

**Review by clementmbr — APPROVED** [review]
Perfect !

**Review by hparfr — CHANGES_REQUESTED** [review]
Wait before merge, I need time to investigate side effects

**Comment by hparfr** [comment]
This patch is not needed. In v14 (delivery) length is renamed to packaging_length.
@Kev-Roche please close this PR.

**Pull request closed without merging**
