### PR TITLE
product_m2mcategories: 8.0 migration + PEP8 cleanup; doesn't consider website_sale compatibilit...

### PR DESCRIPTION
**Pull request by rvalyi**
...y for now

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Hi, Raphäel. We already have this module migrated in OdooMRP and I'm going to propose it to OCA even today. As I see you have some troubles yet, I can propose mine against your branch or directly to OCA. What do you prefer?

**Comment by omar7r** [comment]
Hi,

I also have got this module migrated, check https://github.com/OCA/product-attribute/pull/20

**Comment by pedrobaeza** [comment]
Mine is migrated to new API, so I think it's better to have it new fashioned way, don't you think?

**Comment by omar7r** [comment]
Hi Pedro,

Of course, I didn't have time for that, I could remove this module for my PR.

**Comment by pedrobaeza** [comment]
Thanks, I proceed then to make the PR. Don't you mind, @rvalyi?

**Comment by pedrobaeza** [comment]
Here it is: https://github.com/OCA/product-attribute/pull/21

**Comment by rvalyi** [comment]
Hello @pedrobaeza I don't mind

**Comment by pedrobaeza** [comment]
I close this PR then.

Thanks.

**Pull request closed without merging**
