### PR TITLE
[16.0][MIG] product_supplierinfo_stock_picking_type: Migration to 16.0

### PR DESCRIPTION
**Pull request by victoralmau**
Migration to 16.0

Please @pedrobaeza and @chienandalu can you review it?

@Tecnativa TT47849

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
Functional test :+1: 

It seems there's some module that makes tests fail

**Comment by victoralmau** [comment]
Tests of `product_supplierinfo_for_customer` fixed with https://github.com/OCA/product-attribute/pull/1521

**Review by pedrobaeza — APPROVED** [review]
Just waiting for solving the repo CI

**Pull request merged**
