### PR TITLE
[MIG] product_custom_info

### PR DESCRIPTION
**Pull request by rlizana**
Migrate product_custom_info from 10.0

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0.

If the jump is between several versions, you have to modify the source branch in the main command to accommodate it to this circumstance.

**Comment by rlizana** [comment]
@pedrobaeza thanks for information.
History preserved

**Comment by pedrobaeza** [comment]
Please add `server-tools` to oca_dependencies.txt.

**Comment by rlizana** [comment]
added depend

**Review by pedrobaeza — APPROVED** [review]

**Review by jctrey — APPROVED** [review]
+1

**Pull request merged**
