### PR TITLE
[IMP] refactor message calls

### PR DESCRIPTION
**Pull request by bealdav**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:

**Comment by bealdav** [comment]
Thanks for merge

**Comment by pedrobaeza** [comment]
We need one more approval or wait 5 days, sorry.

**Comment by bguillot** [comment]
:+1:

**Comment by pedrobaeza** [comment]
OK, I merge :wink:

**Pull request merged**
