### PR TITLE
[10.0][ADD] product_state_history

### PR DESCRIPTION
**Pull request by rousseldenis**
This module allows to build product state history in order to retrieve statistics about it.

product_state_history_form

product_state_history_tree

product_state_history_pivot

product_state_history_report

### CODE REVIEW

**Comment by rousseldenis** [comment]
@emagdalenaC2i This would be your interest :smiley:

**Review by acsonefho — APPROVED** [review]
LGTM (Code only)

**Review by emagdalenaC2i — APPROVED** [review]
LGTM

**Comment by Cedric-Pigeon** [comment]
@OCA/product-maintainers could anyone merge this one please?

**Pull request merged**
