### PR TITLE
10.0 mig product custom info

### PR DESCRIPTION
**Pull request by fanha99**

### CODE REVIEW

**Comment by fanha99** [comment]
this module is depend on base custom info which is merged yesterdays.
the runbot and travis is failed because of missing module base custom info.

**Comment by pedrobaeza** [comment]
Add server-tools to oca_dependencies.txt file in root.

**Comment by pedrobaeza** [comment]
Conflicting file

**Comment by fanha99** [comment]
almost nothing change, please help to review.

**Review by pedrobaeza — APPROVED** [review]
OK, as easy one, I fast-track it

**Pull request merged**
