### PR TITLE
[13.0][IMP] product_manufacturer: Manage Manufacture Info for Variants

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
CC @ForgeFlow

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM code review

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:  Functional tests

**Review by AdriaGForgeFlow — APPROVED** [review]

**Comment by HviorForgeFlow** [comment]
Ready to merge: migration script is meant to work on 13.0.2.0.0, so major merge required

Thanks!

**Review by bodedra — APPROVED** [review]
LG :+1:

**Review by rousseldenis — APPROVED** [review]

**Comment by juppe** [comment]
@HviorForgeFlow I tested this out and it seems that it does not work when creating a new product template. template.product_variant_ids is empty when the inverse-function is triggered.

**Comment by bodedra** [comment]
> @HviorForgeFlow I tested this out and it seems that it does not work when creating a new product template. template.product_variant_ids is empty when the inverse-function is triggered.

@juppe would you please create a [new issue](https://github.com/OCA/product-attribute/issues/new) and are you able to create it on the runbot?

**Pull request merged**
