### PR TITLE
[MIG][16.0] product_net_weight

### PR DESCRIPTION
**Pull request by RabbitJon-S73**
Standard migration to 16.0

### CODE REVIEW

**Comment by RabbitJon-S73** [comment]
@legalsylvain

**Review by legalsylvain — COMMENTED** [review]
Hi. Thanks for porting this module. Diff review OK.

However, in another PR, @sergio-teruel said that the design of the net_weight was bad. (for the time being related field -> should be trivial computed field).
could you take a look on [that message](https://github.com/OCA/product-attribute/pull/1241#issuecomment-1378719018) and take advantage of the migration to correct this point ?
@sergio-teruel : you said you'll do a PR. Did you do it ? 

thanks !

**Comment by sergio-teruel** [comment]
Sorry @legalsylvain Done here: https://github.com/OCA/product-attribute/pull/1288

@RabbitJon-S73 Can you wait to merge the last one and do the migration... ?? Sorry ...

**Comment by RabbitJon-S73** [comment]
@sergio-teruel I cherry-picked your commit and I did some modifications in README version, but runboat isn't working, could you check it?

**Comment by sergio-teruel** [comment]
Hi.
Only one question...
In older version the podition of net_weight field is before than weight... 
Can you keep this?

image

**Comment by RabbitJon-S73** [comment]
I had to depend on stock and the inherit since `Responsible` is in the middle of both weights because of this xpath https://github.com/odoo/odoo/blob/755c517fcab89df51e8b0ee4529894372b4d4ec1/addons/stock/views/product_views.xml#L448
@sergio-teruel

**Comment by legalsylvain** [comment]
> I had to depend on stock and the inherit since Responsible is in the middle of both weights because of this xpath https://github.com/odoo/odoo/blob/755c517fcab89df51e8b0ee4529894372b4d4ec1/addons/stock/views/product_views.xml#L448
@sergio-teruel

that's annoying.
what do you think @sergio-teruel ? 

For me, it's not a problem  that a "weight" module depends on stock. It is a very basic module, and I don't see use case where we want net weight without stock.

OK for all ?

**Comment by RabbitJon-S73** [comment]
> > I had to depend on stock and the inherit since Responsible is in the middle of both weights because of this xpath https://github.com/odoo/odoo/blob/755c517fcab89df51e8b0ee4529894372b4d4ec1/addons/stock/views/product_views.xml#L448
> > @sergio-teruel
> 
> that's annoying. what do you think @sergio-teruel ?
> 
> For me, it's not a problem that a "weight" module depends on stock. It is a very basic module, and I don't see use case where we want net weight without stock.
> 
> OK for all ?

First I tried to modify the view to keep like v14.0 without adding any additional dependency, but its true that this module and stock will be installed always together. Its OK for me

**Review by legalsylvain — APPROVED** [review]

**Comment by rvalyi** [comment]
we also use if the Brazil for electronic invoicing and the module where we use it (l10n_br_nfe,_delivery) also depends on stock, so ok for us too.

**Comment by sergio-teruel** [comment]
Ok for me too

**Comment by RabbitJon-S73** [comment]
Hey @sergio-teruel, could you approve?

**Review by sergio-teruel — APPROVED** [review]

**Comment by sergio-teruel** [comment]
@RabbitJon-S73 Done!! Thanks

**Review by ferran-S73 — APPROVED** [review]

**Comment by RabbitJon-S73** [comment]
@pedrobaeza

**Comment by ferran-S73** [comment]
@pedrobaeza this should be ready to merge now

**Pull request merged**
