### PR TITLE
[16.0][MIG] product_pricelist_simulation: Migration to 16.0

### PR DESCRIPTION
**Pull request by hugo-cordoba**
[16.0][MIG] product_pricelist_simulation: Migration to 16.0

### CODE REVIEW

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Hi @HugoCordobaLeal. 

Thanks for porting this module. 
playing on runboat. most of things looks OK

Error A : 
- Create the following configuration : 
image
- Go to the product and set a value below 100. 
- Expected result 295. Display result : 45

Error B : 
- Go to template > Customizable Desk and click on the button.
```
  File "/mnt/data/odoo-addons-dir/product_pricelist_simulation/wizards/wizard_preview_pricelist.py", line 61, in _prepare_simulation_lines_vals
    price = pricelist._price_get(variant, pricelist.item_ids.min_quantity)
  File "/opt/odoo/odoo/fields.py", line 1153, in __get__
    record.ensure_one()
  File "/opt/odoo/odoo/models.py", line 5132, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: product.pricelist.item(2, 1)
```

Thanks !

**Comment by hugo-cordoba** [comment]
Good morning @legalsylvain.

I have just checked what you are saying and, indeed, you are right. I have uploaded the module update. It should now work as expected. 

Thanks for the review. Best regards.

**Review by navarrorico — APPROVED** [review]
Functional review

**Review by legalsylvain — APPROVED** [review]
Thanks a lot ! 

Diff review : LGTM.
Functional review : looks OK ! 

@pedrobaeza : do you want to test ? (and merge if all is OK).

@HugoCordobaLeal : please ping me on the second PR ``product_pricelist_simulation_margin``

Regards.

**Review by legalsylvain — APPROVED** [review]
Thanks a lot ! 

Diff review : LGTM.
Functional review : looks OK ! 

@pedrobaeza : do you want to test ? (and merge if all is OK).

@HugoCordobaLeal : please ping me on the second PR ``product_pricelist_simulation_margin``

Regards.

**Comment by legalsylvain** [comment]
Hi @hugo-cordoba 

Could you take a look on bug introduced in that PR ?

https://github.com/OCA/product-attribute/issues/1466

Thanks !

**Pull request merged**
