### PR TITLE
[MIG] product_sequence: Migration to 15.0

### PR DESCRIPTION
**Pull request by BertVGroenendael**

### CODE REVIEW

**Review by CasVissers-360ERP — APPROVED** [review]
Functional test.

**Review by jjscarafia — APPROVED** [review]
LGTM

**Comment by jjscarafia** [comment]
@BertVGroenendael 
can you please consider to add the improvement suggested here https://github.com/OCA/product-attribute/pull/1076 ? (and also review that PR)

Thanks

**Pull request merged**
