### PR TITLE
[14.0][IMP] product_state: move access to Sales + Inventory Manager

### PR DESCRIPTION
**Pull request by HekkiMelody**
https://github.com/OCA/product-attribute/issues/1121

### CODE REVIEW

**Comment by HekkiMelody** [comment]
Had to modify the tests of a dependent module, as a result.

**Review by lfreeke — APPROVED** [review]
Functional test :+1:

**Review by emagdalenaC2i — APPROVED** [review]

**Review by Kev-Roche — APPROVED** [review]

**Comment by HekkiMelody** [comment]
@OCA/product-maintainers sorry for the ping, but could you please merge this?

**Comment by dreispt** [comment]
Shouldn't this access be given to the Inventory Manager, rather than the Sales Manager?

**Comment by Kev-Roche** [comment]
> Shouldn't this access be given to the Inventory Manager, rather than the Sales Manager?

Indeed, it's a good question. Maybe the answer is both because some products with service type are not in stock and some projects are more focused on sale than stock (and opposite).

**Comment by HekkiMelody** [comment]
> > Shouldn't this access be given to the Inventory Manager, rather than the Sales Manager?
> 
> Indeed, it's a good question. Maybe the answer is both because some products with service type are not in stock and some projects are more focused on sale than stock (and opposite).

That was my reasoning as well. I've added both.

**Comment by legalsylvain** [comment]
/ocabot merge patch

thanks for your contribution. Feel free to port this patch upstream, if necessary.

regards.

**Comment by natuan9** [comment]
Hi @aleuffre , I noticed you moved access to Inventory Manager but didn’t add a dependency on the `stock` module. Doesn’t this cause any issues? I also see that the migration PRs don’t mention this either.
Currently, I’m migrating this module to version 18.0, and I’m uncertain whether I should add a dependency on the stock module. Could you clarify this for me?

**Comment by HekkiMelody** [comment]
> Hi @aleuffre , I noticed you moved access to Inventory Manager but didn’t add a dependency on the `stock` module. Doesn’t this cause any issues? I also see that the migration PRs don’t mention this either. Currently, I’m migrating this module to version 18.0, and I’m uncertain whether I should add a dependency on the stock module. Could you clarify this for me?

I think you're correct. I thought there was an indirect dependency based on the module's existing dependencies, but it seems I was wrong (or maybe I just missed it at the time, I don't remember after almost a year). You should definitely add this fix when migrating. Thank you!

**Comment by simahawk** [comment]
Guys, this change is breaking the module. The dependency on `stock` has not been declared.
**EDIT:** I've just seen the msg by @natuan9, sorry for the repetition :)

Sounds like it was never tested in isolation (= install only this module).
Also is arguable that we have to add a full dep on `stock` just to use its group.
IMO it should be done like this:
* add a specific group in this module
* add an auto-installable module that depends on stock that add this group as implied on inv manager

BTW even the dep on sale could be ripped out as it's needed only for the menu...

**Comment by simahawk** [comment]
> > Hi @aleuffre , I noticed you moved access to Inventory Manager but didn’t add a dependency on the `stock` module. Doesn’t this cause any issues? I also see that the migration PRs don’t mention this either. Currently, I’m migrating this module to version 18.0, and I’m uncertain whether I should add a dependency on the stock module. Could you clarify this for me?
> 
> I think you're correct. I thought there was an indirect dependency based on the module's existing dependencies, but it seems I was wrong (or maybe I just missed it at the time, I don't remember after almost a year). You should definitely add this fix when migrating. Thank you!

I would proceed the other way around. We remove the need for the dep in v18 and you can backport the fix here :wink:

**Comment by HekkiMelody** [comment]
Apologies again for the mistake on my part.

I don't have a strong opinion on how to fix it either way, in fact I like your solution best @simahawk , but I've definitely seen small modules blocked to avoid multiplying the number of modules in OCA...

**Pull request merged**
