### PR TITLE
[MIG] product_template_tags: Migration to 15.0

### PR DESCRIPTION
**Pull request by BT-dmontull**

### CODE REVIEW

**Review by BT-aestebanez — APPROVED** [review]
LGTM

**Comment by BT-aestebanez** [comment]
@ivantodorovich can you review it please?

**Review by ivantodorovich — APPROVED** [review]
LG. Thanks!

**Comment by BT-aestebanez** [comment]
@ivantodorovich can you merge it as maintainer?

**Comment by ivantodorovich** [comment]
> @ivantodorovich can you merge it as maintainer?

I don't think I can. I believe it doesn't work for migrations.
Have you solved the CLA issue though?: https://github.com/OCA/product-attribute/pull/1029#issuecomment-1059229474

**Comment by BT-aestebanez** [comment]
@ivantodorovich Thanks, I did not know. I am not the author @BT-dmontull have you done it?

**Comment by BT-dmontull** [comment]
Thanks @ivantodorovich and @BT-aestebanez for comments. 
Yes, I have already signed the CLA and sent it in. is there anything else I should do?

**Comment by BT-aestebanez** [comment]
@rousseldenis could you merge this? I saw you merged the migration to 14.0: https://github.com/OCA/product-attribute/pull/803

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
