### PR TITLE
[UPD] Brainbean Apps => CorporateHub

### PR DESCRIPTION
**Pull request by alexey-pelykh**

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@pedrobaeza and this one if possible

**Comment by alexey-pelykh** [comment]
@OCA/product-maintainers would it be possible to merge this?

**Comment by alexey-pelykh** [comment]
Travis fails due to:
```
product_sequence/tests/test_product_sequence.py:50: [E8103(sql-injection), TestProductSequence.test_pre_init_hook] SQL injection risk. Use parameters if you can. - More info https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#no-sql-injection
```

**Comment by pedrobaeza** [comment]
No, Travis failed was another and solved in 9fae87a62ade6ad7496b9264fa0e1139bdae36e1

/ocabot merge patch

**Pull request merged**
