### PR TITLE
[12.0][IMP] product_brand: save logo as attachment

### PR DESCRIPTION
**Pull request by GSLabIt**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This change can't be done without migration script. See an example here: https://github.com/OCA/bank-payment/commit/640f31e0277199f8b5cec7c0026db456aee55630

**Comment by GSLabIt** [comment]
@pedrobaeza ooopss ..sorry will add the script.

**Comment by GSLabIt** [comment]
@pedrobaeza not sure if done correctly ..but at least done 😬

**Comment by pedrobaeza** [comment]
You must change module version number (to `12.0.2.0.0`), and name the folder that way

**Comment by GSLabIt** [comment]
thought version number change would be done while merging ..probably i misunderstood ..will do

**Comment by pedrobaeza** [comment]
Well, I can do that bump on merge, but it won't work any way as you have put the migrations folder with `12.0.1.0.0`, so better you do all together.

**Comment by GSLabIt** [comment]
@pedrobaeza do it work now?

**Comment by pedrobaeza** [comment]
Well, I have asked you to put `12.0.2.0.0`, as it's a huge change that requires a migration script (see https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#version-numbers)

**Comment by GSLabIt** [comment]
@pedrobaeza sorry didn't get it ..i'm getting quite confused with all this rules .. 😬

**Comment by pedrobaeza** [comment]
It's just to follow my comment :wink:

**Comment by GSLabIt** [comment]
@pedrobaeza 3rd attempt ... 😬

**Review by pedrobaeza — APPROVED** [review]
And here it goes!

**Comment by pedrobaeza** [comment]
Well, commit message puts 11.0 instead of 12.0, but I'll squash on merge removing the version.

**Comment by GSLabIt** [comment]
@pedrobaeza oh sorry i was initially doing for 11 because i back ported import image from url to 11 😬

**Pull request merged**
